### ISSUE TITLE
Cannot sign in, no add-ons listed

### ISSUE THREAD

**Issue by schmatzler** [supertuxkart/stk-code#2031] opened 2015-03-09 10:18 UTC
I just compiled the latest codebase on Slackware64-current. I can't login online.

This means:
- I enter my username and password
- I click Login
- A message about my password being wrong appears.

My password is correct, since I can login with a browser on addons.supertuxkart.net.
I also can't see any addons available for download, but the "latest post on stkblog" thingy is working.

There aren't any error messages in the log either:

    [info   ] HTTPRequest: Sending username=schmatzler&password=*************&save-session=false to https://addons.supertuxkart.net/api/v2/user/connect/
    [info   ] HTTPRequest: Sending username=schmatzler&password=*************&save-session=false to https://addons.supertuxkart.net/api/v2/user/connect/
    [info   ] HTTPRequest: Sending username=schmatzler&password=*************&save-session=false to https://addons.supertuxkart.net/api/v2/user/connect/
    [info   ] HTTPRequest: Sending username=schmatzler&password=*************&save-session=false to https://addons.supertuxkart.net/api/v2/user/connect/

**Comment by leyyin** [comment] 2015-03-09 13:34
Hi @schmatzler.
I can not reproduce your login problem.
Also the username 'schmatzler' does not exist in the database, maybe you have a typo in your username. I am not sure how you could log in from the browser.

And I couldn't reproduce your addons problem. You can't see any addons listed in the tracks tab or arena?

**Comment by schmatzler** [comment] 2015-03-09 13:43
That is very strange. I was able to login with my username schmatzler last week on the website. Today it is gone.

I registered it again and was able to login. And I can see 3 addons now. Don't know what happened here, but this can be closed, I guess.

**Comment by auriamg** [comment] 2015-03-09 23:24
Closing since bug cannot be reproduced, please reopen if more information is found

**Closed** 2015-03-09 23:23 UTC
