### ISSUE TITLE
Little things to add to the help

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#3598] opened 2018-11-20 01:44 UTC
## Description
I suggest to add the following little pieces of information into the help menu:

* Bomb: If you carry a bomb, and collide with another kart while the hand is in the red area, the other kart will explode immediately.
* General: If you press and hold down the “accellerate” from the moment the “Set!” phase begins, you will get an initial speed boost. But if you accellerate too early (before “Set!”), you get a time penalty

Probably needs to be rewritten a bit, but you get the idea.

Version: 95ecd55ce8f5c004f02642e41ba1cfaef0f21ec8

**Comment by Alayan-stk-2** [comment] 2018-11-20 02:45
The second part is a duplicate of #3561.

For the bomb, in all cases, the timer loses 5 seconds when passed to another kart. I would focus the information on this first, and then add the bit about immediate explosion when in the red area.

**Comment by Alayan-stk-2** [comment] 2018-11-20 03:09
The bomb timer change when passing the bomb to another kart has been removed, as it has been evaluated that it did not improve gameplay.

With the second part of this issue already tracked by another one, I'm closing this ticket.

**Closed by Alayan-stk-2** 2018-11-20 03:09 UTC

**Comment by Wuzzy2** [comment] 2018-11-20 11:29
Oh. Sorry. I did not realize you removed it *today*. xD
Nevermind.
