### ISSUE TITLE
Brief noise when looking back

### ISSUE THREAD

**Issue by Arthur-D** [supertuxkart/stk-code#2360] opened 2015-10-26 14:20 UTC
Whenever I start to look back, there's a brief noise, as if the sound buffer isn't cleared when looking back and thus there's a duplicated motor sound due to the new camera. That would be my guess as to what's happening, but in any case it should be easy to reproduce.

**Comment by cap44** [comment] 2015-10-26 14:22
Can confirm the bug under 0.9.1 in Windows 8.1/OpenSUSE 13.2
On Oct 26, 2015 4:20 PM, "Arthur-D" <notifications@github.com> wrote:
>
> Whenever I start to look back, there's a brief noise, as if the sound
buffer isn't cleared when looking back and thus there's a duplicated motor
sound due to the new camera. That would be my guess as to what's happening,
but in any case it should be easy to reproduce.

**Comment by VOTProductions** [comment] 2015-10-26 14:42
Can reproduce the bug under 0.9.1, Arch Linux.

**Comment by auriamg** [comment] 2015-11-02 01:23
I tried to reproduce but I don't think I heard anything. Anyone could record so I know what it sounds like?

**Comment by cap44** [comment] 2015-11-02 03:28
Afaik, it's static noise,  but I can't record it for now
On Nov 2, 2015 3:23 AM, "auriamg" <notifications@github.com> wrote:
>
> I tried to reproduce but I don't think I heard anything. Anyone could
record so I know what it sounds like?

**Comment by Arthur-D** [comment] 2015-11-02 22:16
Recording of the issue and how it manifests at various points in time:
https://www.mediafire.com/?hsx1xh2lj6r1pkz

**Comment by auriamg** [comment] 2015-11-04 00:16
Could you please test branch "2360_fix_attempt" ? I think it's better with this branch

**Comment by Arthur-D** [comment] 2015-11-04 01:39
Tested it and now I don't hear any sound at all when looking backwards. Could anyone else test?

**Comment by Arthur-D** [comment] 2015-11-06 21:11
It works now, and @leyyin confirms the branch fixes the original issue. Thanks. :)

**Comment by auriamg** [comment] 2015-11-09 01:13
Thanks, this confirms what I thought though we may need to do further testing, what I did could change the balance of sounds
The branch basically moves the listener from the camera to the kart, which means it doesn't jump around when looking back, But that also means some sounds may now be louder, like the engine noises, this should be properly tested to make sure we don't upset sound balance too much

**Comment by auriamg** [comment] 2015-11-09 23:22
Branch merged, this issue should now be fixed. Please report any issue

**Closed by auriamg** 2015-11-09 23:22 UTC
Labels: P4: minor, T: defect
