### ISSUE TITLE
Minimal graphics settings make shadows flash

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#3824] opened 2019-04-07 12:13 UTC
## Description

If you set all graphics settings to the lowest possible value except Improved Graphics and shadow (low or high), the shadows flash like crazy.

## Steps to reproduce

1. Set all graphics settings to the minimal possible value
2. Enable Improved Graphics
3. Set shadows to low or high
4. Restart STK
5. Play any track

### EXPECTED BEHAVIOUR
No visual glitches.

### ACTUAL RESULT
Most shadows are flashing at a high rate. It's very annoying and looks horrible.

## Configuration

STK release version: 0.10-rc1
STK Source (PPA, distribution package, official binary, etc.): Git

## System specifications

* Computer: Dell Inspiron 7537
* Processor: Intel Core i7-4510U CPU @ 2.00GHz with 4 cores
* RAM: 8 GiB
* Graphics: Haswell-ULT Integrated Graphics Controller
* Operating system: GNU/Linux

**Comment by auriamg** [comment] 2019-04-07 22:31
I cannot reproduce this issue, so my first guess would be that it's a driver 'peculiarity'

**Comment by qwertychouskie** [comment] 2019-04-08 18:58
I get the issue with Intel HD 4000 (Ivy Bridge), I assumed it was related to samuncle's LOD changes, but those were reverted.

**Comment by deveee** [comment] 2019-04-08 20:45
I can reproduce it on intel HD4000 with current git mesa too. For me it happens on highest settings too and only grass shadow is flickering.

After very quick look it seems to be related to uniform variables. I moved wind_direction in sp_grass_shadow.vert to the first line and then it doesn't flicker anymore.

**Comment by Benau** [comment] 2019-04-08 22:22
i think it's too hacky.... maybe something in mesa caused a regression

**Comment by Wuzzy2** [comment] 2019-04-09 05:02
FYI: I have Mesa 18.3.4.

**Comment by deveee** [comment] 2019-04-10 21:11
https://bugs.freedesktop.org/show_bug.cgi?id=110395

**Comment by janesma** [comment] 2019-04-11 17:40
I see all kinds of STK flickering with 0.9.3 from debian testing.  I see the same behavior on mesa master and 18.1.

This is on my Intel skylake system (HD520).

Since the behavior is consistent on our Mesa driver, it seems likely to me that a change to STK is causing this.

Is anyone able to test on an older STK?

**Comment by DenKos363** [comment] 2019-04-16 15:53
hi, could you please check this patch? https://gitlab.freedesktop.org/mesa/mesa/merge_requests/660
I tested this issue on SNB, HSW, BDW, SKL and KBL. In my case I reproduced it on SNB and HSW (and on these machines patch helped). Issue didn't reproduce on higher generations.

**Comment by deveee** [comment] 2019-04-16 20:02
As said in mesa bug report, I tested the patch https://gitlab.freedesktop.org/mesa/mesa/merge_requests/660 with both first bad commit and current git version on my intel HD4000 and it solves the issue for me.

**Comment by schirmeier** [comment] 2019-05-03 20:07
Not fixed for me, as [described in the Mesa bug report](https://bugs.freedesktop.org/show_bug.cgi?id=110395#c20). Detail levels 4 and 5 flicker both with and without the patch, level 3 is OK with both.

**Comment by Benau** [comment] 2019-06-23 16:12
You can try edit in your stk-code/data/graphical_restrictions.xml
change
```
  <card contains="Intel"          os="linux"    version="<11.2"    disable="ComputeShader"/>

to

  <card contains="Intel"          os="linux"     disable="ComputeShader"/>
```
and see if this help...

**Comment by janesma** [comment] 2019-09-09 21:54
The mesa bug report that I opened has been fixed.  I found the bug on skylake, but a separate bug was opened for older hardware (with a different bisection).  I can't reproduce the flickering on broadwell, so I think this is fixed.

**Comment by Benau** [comment] 2019-09-10 01:31
So can we close this ticket?

**Comment by DenKos363** [comment] 2019-09-10 08:07
I would say yes. I also tested this issue and couldn't reproduce it anymore

**Closed** 2019-09-10 08:56 UTC
Labels: C:Graphics, R:Waiting for feedback
