### ISSUE TITLE
Last round sound does not work

### ISSUE THREAD

**Issue by GreenLunar** [supertuxkart/stk-code#1873] opened 2015-01-02 17:47 UTC
Last round sound does not work when music is disabled.

**Comment by Flakebi** [comment] 2015-01-02 18:53
Duplicate of #1613.

**Comment by auriamg** [comment] 2015-01-02 22:55
@Flakebi I don't think it's a duplicate, I think he's talking about the little jingle that plays when starting the last lap

However, since it's a little music, I don't think it's a bug that disabling music should remove it

**Closed by auriamg** 2015-01-02 22:55 UTC

**Comment by GreenLunar** [comment] 2015-01-03 02:10
> However, since it's a little music, I don't think it's a bug that disabling music should remove it

Then disable the start music, too.
