### ISSUE TITLE
wayland: resolution is compared against the wrong monitor

### ISSUE THREAD

**Issue by myfreeweb** [supertuxkart/stk-code#3995] opened 2019-07-10 21:54 UTC
## Description

The wrong monitor is used for resolution limit checks.

## Steps to reproduce

- have a dual-monitor setup, first one smaller than the second one (e.g.: first 1280x1024, second 3840x2160 with 1.5 scale (2560x1440 logical pixels))
- start the game on the second (larger) monitor
- try to set larger resolution
- resolution stays limited to the size of the first (smaller) monitor (1280x1024)

## Configuration

STK release version: 1.0

STK Source (PPA, distribution package, official binary, etc.): FreeBSD Ports

System: FreeBSD 13-CURRENT

Graphics card: AMD Radeon RX Vega

CPU: AMD Ryzen 7 1700

## Additional information

Error message:
```
[warn   ] irr_driver: The window size specified in user config is larger than your screen!
```

**Comment by Alayan-stk-2** [comment] 2019-07-15 11:42
Duplicate of #2995

**Closed by Alayan-stk-2** 2019-07-15 11:42 UTC

**Comment by cashcashcashcash** [comment] 2019-07-15 15:35
Huh
