### ISSUE TITLE
no colision on bumpers in "cocoa temple"

### ISSUE THREAD

**Issue by rogue-spectre** [supertuxkart/stk-code#2015] opened 2015-03-02 08:24 UTC
beta 0.8.2
There is no colision with yellow bumpers placed on road forks in the "cocoa temple" track.

**Comment by Flakebi** [comment] 2015-03-02 20:49
Maybe a duplicate, I'm not sure if we want a separate ticket for that. I mentioned it in #1757 too.

**Comment by samuncle** [comment] 2015-03-04 04:24
Hi
These impact attenuator were mainly created as one of the first object that will be affected by scripting. The idea is, if you are driving slowly you can move them a bit, but if you have enough speed you can destroy them just like in real life.

Since scripting isn't enabled, I decided to just try to enable physic: movable by the player. And there is an issue. It seems the physical shape and the visual one aren's sync :(. I'm not sure what's causing this here is a screenshot of the issue

![screenshot - 04 03 2015 - 05 17 18](https://cloud.githubusercontent.com/assets/6406045/6478210/22afbe34-c22e-11e4-8a64-f7fba717e696.jpg)
![screenshot - 04 03 2015 - 05 22 11](https://cloud.githubusercontent.com/assets/6406045/6478229/88cd4e52-c22e-11e4-80c6-5aa9b525ba83.jpg)

You can clearly see the physical shape and the actual object are separated. However it's mainly visible when you start moving them.

I have commited so tests can be done. If it's too difficult to correct the bug,for the release I will simply enable physic and static so at least you can't go inside them.

**Comment by hiker** [comment] 2015-03-04 05:42
Reproduced, it is somehow connected to setting hpr (with hpr=0 it works fine) - and I can see in a test case the further I move the barrel from the origin, the bigger the displacement becomes.

**Comment by auriamg** [comment] 2015-03-04 23:45
Thre area to check is probably PhyiscalObject::update. I must say that so far I see nothing obviously wrong, though

**Comment by auriamg** [comment] 2015-03-05 02:00
Potential fix pusheds to bvranch "MovablesAlwaysAtSceneRoot"

**Comment by samuncle** [comment] 2015-03-07 02:37
The fix is merged. Barrels are now movable by the player. Once scripting will be enabled they will be hopefully destroyable.

Thank you auria for your fix

**Closed by samuncle** 2015-03-07 02:37 UTC
Labels: C: Physics
