### ISSUE TITLE
Full screen mode uses wrong aspect ratio when game is restarted

### ISSUE THREAD

**Issue by keijokalervo** [supertuxkart/stk-code#5184] opened 2024-10-15 20:37 UTC
Full screen mode only works properly on the actual screen resolution when adjusted in the settings but does not work when the game is restarted. This issue is not present when smaller resolutions are used. For example my laptop is 1920x1080 and the fullscreen works on lower resolutions even after restarting the game manually but when 1920x1080 is chosen the aspect ratio goes to 4:3 upon restart of the game

Opening the application -> Goin to options -> Switching to full screen mode 1920x1080 -> Exiting the game -> Starting the game

STK release version: 1.4

STK Source (PPA, distribution package, official binary, etc.): 

System: Windows 

Graphics card: Intel(R) HD Graphics 620

CPU: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz   2.71 GHz

**Comment by CodingJellyfish** [comment] 2024-10-22 12:09
Duplicate of #4971

**Closed by CodingJellyfish** 2024-10-22 12:09 UTC
