### ISSUE TITLE
Rescue point in reverse Ravenbridge Mansion respawns you on banana

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#3846] opened 2019-04-16 13:26 UTC
https://satoshiupload.com/images/dNfmeckA7y.jpg

If you drive Ravenbridge Mansion in reverse mode and you reset behind the banana in above screenshot, you will respawn on the banana and collect it immediately.

The banana is on the big curvy cobblestone serpentines that lead up to the road, 2nd level.

**Comment by Alayan-stk-2** [comment] 2019-04-16 13:59
Duplicate of #3779

**Closed by Alayan-stk-2** 2019-04-16 13:59 UTC
Labels: R: duplicate
