### ISSUE TITLE
android: tracks/cards unlocked

### ISSUE THREAD

**Issue by trance-babe** [supertuxkart/stk-code#5050] opened 2024-04-13 01:46 UTC
Hi

In the android version all tracks/cards are unlocked without doing anything, while in windows they are locked.

**Comment by Alayan-stk-2** [comment] 2024-04-13 11:02
Duplicate of #3109 

For the longest time, Android didn't have all tracks because of package size limitations, which would have caused issues to complete Story Mode if the tracks were locked.

**Closed by Alayan-stk-2** 2024-04-13 11:02 UTC
Labels: R: duplicate
