### ISSUE TITLE
Basket ball can explode on 2nd player in a race

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#3718] opened 2019-01-17 18:10 UTC
This is before the 1st player finished the race. Just happened on me in an online race. I don't know if it is specific to online races or not, nor what is the cause.

**Comment by deveee** [comment] 2019-02-12 21:45
Maybe not a regression, because basket ball was doing strange things at the beginning of hacienda before 0.9.3, eg. see https://github.com/supertuxkart/stk-code/issues/2735

**Comment by hiker** [comment] 2019-02-12 23:46
I have started to have a look - while I found a potential minor bug (I think basketball are not deleted properly if a target can not be found ... which should only happen at the end animation, and so doesn't really matter), nothing obvious. I am adding debug output and will push it to a separate branch so we can hopefully diagnose this.

Note that #2735 indeed listed cases where the ball got confused about where it was, I don't think this is the case here. There are two potential triggers for a basketball explosion - once when updating the ball and it is 'close' to the target, once from the physics collision handling. So first we need to find out which triggers the explosion (and some other stuff that will be included in the debug output)

**Comment by hiker** [comment] 2019-02-13 04:35
I've just pushed a debug-ball branch, which includes additional debug output for basket balls (which is also enabled by default) and also only giving out basket balls all the time. I will try to reproduce the problem with this debug output, but would be great if someone else could try as well (note you should be using --log-buffer=100000 or even more (we get two lines per ball per frame), since it prints a LOT, potentially causing a significant slowdown). It will also take some time when exiting to flush the buffer out - as in might be half a minute or so, depending on amount of data.

**Comment by Benau** [comment] 2019-02-20 07:59
https://www.youtube.com/watch?v=aLugJlzlTDI
Fouks disconnected, so he was eliminated, and finished race
```
    for(unsigned int p = race_manager->getFinishedKarts()+1;
                     p < world->getNumKarts()+1; p++)
```
just p = 1? (you will skip the kart if m_target->hasFinishedRace true anyway)

**Comment by hiker** [comment] 2019-02-20 12:50
So if a player leaves the race, the kart is marked as 'finished'? That sounds wrong, but it would indeed explain this issue (and this was the case in Alayan's video, too). Then running the loop from 1 would fix this issue, but I wonder if this could have other side effects. Hmm - a quick grep did not show any significant use of getFinishedKart (only in profile and demo mode), and I am happy to to use this work around - but there is this nagging feeling that there might be other places that might have the assumption that any finished kart or player has a rank (there is getFinishedPlayers() ... but this function is apparently not even used anymore - one more thing to clean up ;) ).
Hmm - what about getNumKarts() - this remains unchanged, i.e. it does always include players left? Otherwise (I think) the loop might be one too short in case of players exciting.

**Closed** 2019-02-21 02:14 UTC
Labels: C: Race Events, P3: normal, T: defect, T: regression
