### ISSUE TITLE
Adding specific weights list for Follow the Leader

### ISSUE THREAD

**Issue by Alayan-stk** [supertuxkart/stk-code#1688] opened 2014-11-10 02:24 UTC
With weights list tuned for a given number of kart incoming, and since there are a number of gameplay differences between normal race and FTL anyway, FTL should get its own weights list.

**Comment by deveee** [comment] 2015-11-18 11:19
More or less duplicate of #1667

**Closed by deveee** 2015-11-18 11:19 UTC
