### ISSUE TITLE
Bomb passing behaves wrong in network play

### ISSUE THREAD

**Issue by Mrxx99** [supertuxkart/stk-code#3736] opened 2019-02-02 12:33 UTC
The mechanism to prevent passing the bomb back to the player you got it from seems not to work on online/local network multiplayer. 
Here is a video: https://youtu.be/K2p29Ohw4EI

## Steps to reproduce
Start an online/network multiplayer
Get an bomb
Pass it to another player
Hit that player again with you kart and you will get the bomb back.

## Configuration

STK Source (PPA, distribution package, official binary, etc.): latest master

**Comment by Benau** [comment] 2019-02-05 07:43
```
            // if there are only two karts, let them switch bomb from one to other
            if (getPreviousOwner() != other ||
                World::getWorld()->getNumKarts() <= 2)
```
void Attachment::handleCollisionWithKart(AbstractKart *other)

**Comment by deveee** [comment] 2019-02-06 21:12
It works in the same way in offline game when there are only two karts and it's intended, so I'm closing as not a bug.

**Closed by deveee** 2019-02-06 21:12 UTC
Labels: C: Race Events, C:Networking, P3: normal, T: defect

**Comment by Alayan-stk-2** [comment] 2019-02-07 00:29
Somehow I misunderstood the description of the ticket...

Not being able to pass back the bomb to the kart which gave it is normal behavior.
