### ISSUE TITLE
(LOW PRIORITY) Cannot run game on secondary display

### ISSUE THREAD

**Issue by psypherium** [supertuxkart/stk-code#3346] opened 2018-07-20 03:25 UTC
Maybe not a bug, but an issue. Again, I have a problem that is only experienced in the minority of use cases.

Missing option to run game on secondary display (or tertiary or quaternary etc etc...)

I've looked online and in the .config file and asked around but I cannot find a solution. (Switching displays at the OS level is not an option in my use case.)

If this feature already exists, the documentation is lacking or non-existent.

STK-GIT/ARCH/GNOME3

**Comment by deveee** [comment] 2018-07-20 05:32
Duplicate of #2995

**Closed by deveee** 2018-07-20 05:32 UTC
