### ISSUE TITLE
Arrow key: computer mouse

### ISSUE THREAD

**Issue by Pantyhose-X** [supertuxkart/stk-code#4903] opened 2023-07-30 03:26 UTC
## Description
Support computer mouse slide control (left and right) arrow keys. 

PC play supertuxkart turns have to slow down or else I'll hit the wall, if I use computer mouse control (left and right) I don't have this problem.

Please add the switch option of this function: to the settings

## Configuration

STK release version: 1.4

STK Source (PPA, distribution package, official binary, etc.): 

System: win10

Graphics card: GTX 1060 3G

CPU: i5

Gamepads/keyboards models if related to the issue: 

## Additional information

stdout.log:
```

```

input.xml:
```xml

```

Error message:
```

```

**Comment by qwertychouskie** [comment] 2023-08-04 05:41
Appears to be a duplicate of https://github.com/supertuxkart/stk-code/issues/1832

**Closed** 2023-08-15 02:08 UTC
