### ISSUE TITLE
Assertion failed when clicking on "Solo game" (main menu)

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#1183] opened 2014-02-24 23:46 UTC
**Author: funto66**

I did a race, cancelled, went back to the main menu, and got an assertion failure upon clicking on "Solo game"

In FocusDispatcher::setRootID:
assert(reservedID != -1);
-> I got reservedID == 100

>	supertuxkart.exe!FocusDispatcher::setRootID(const int reservedID) Line 94	C++
 	supertuxkart.exe!KartSelectionScreen::init() Line 946	C++
 	supertuxkart.exe!GUIEngine::AbstractStateManager::pushScreen(GUIEngine::Screen * screen) Line 132	C++
 	supertuxkart.exe!MainMenuScreen::eventCallback(GUIEngine::Widget * widget, const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & name, const int playerID) Line 278	C++
 	supertuxkart.exe!GUIEngine::EventHandler::sendEventToUser(GUIEngine::Widget * widget, std::basic_string<char,std::char_traits<char>,std::allocator<char> > & name, const int playerID) Line 617	C++
 	supertuxkart.exe!GUIEngine::EventHandler::onWidgetActivated(GUIEngine::Widget * w, const int playerID) Line 660	C++
 	supertuxkart.exe!GUIEngine::EventHandler::onGUIEvent(const irr::SEvent & event) Line 702	C++
 	supertuxkart.exe!GUIEngine::EventHandler::OnEvent(const irr::SEvent & event) Line 143	C++
 	supertuxkart.exe!irr::gui::CGUIEnvironment::OnEvent(const irr::SEvent & event) Line 399	C++
 	supertuxkart.exe!irr::gui::CGUIButton::OnEvent(const irr::SEvent & event) Line 225	C++
 	supertuxkart.exe!irr::gui::CGUIButton::OnEvent(const irr::SEvent & event) Line 215	C++
 	supertuxkart.exe!irr::gui::CGUIEnvironment::postEventFromUser(const irr::SEvent & event) Line 570	C++
 	supertuxkart.exe!irr::CIrrDeviceStub::postEventFromUser(const irr::SEvent & event) Line 220	C++
 	supertuxkart.exe!WndProc(HWND__ * hWnd, unsigned int message, unsigned int wParam, long lParam) Line 728	C++

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/1127

**Comment by deveee** [comment] 2015-01-09 13:22
Duplicate of  #1262

**Closed by deveee** 2015-01-09 13:22 UTC
Labels: P3: normal, R: worksforme, R:Waiting for feedback, T: defect
