### ISSUE TITLE
Trophy in unlock cutscene spins off-center

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#3092] opened 2018-01-12 20:06 UTC
See https://jacobspctuneup.tk/STK/featunlocked_spinbug.webm

Tested with `master`, still valid as of 6/10/18.

**Comment by Alayan-stk-2** [comment] 2018-06-12 20:29
I've had a look at the code, the rotation code is straightforward and doesn't seem to do anything special in case n == 0 (the trophy is first in the unlocked feature list).

I suspect the issue is in the trophy .spm model.

**Comment by qwertychouskie** [comment] 2018-06-12 22:46
Here's a fixed blend: [trophy.blend.zip](https://github.com/supertuxkart/stk-code/files/2096035/trophy.blend.zip)

I also subsurfed it once to make it a bit less low-poly.

**Comment by auriamg** [comment] 2018-06-12 23:55
Fixed in SVN

**Comment by Alayan-stk-2** [comment] 2018-11-13 14:21
For some reason, I get this bug again with latest svn and code.

I mentioned in #3542 that another issue had become apparent after this fix, but I did not ask at all to revert this.

**Comment by Alayan-stk-2** [comment] 2018-11-16 04:56
Happened only with the SuperTux cup (the filler platinum model).

Fixed in SVN.

**Closed by Alayan-stk-2** 2018-11-16 04:56 UTC
Labels: R: fixed
