### ISSUE TITLE
STK-0f56a4f6d344d6db8357e614cca0bd04fe93cf2b crashes - IrrLicht?

### ISSUE THREAD

**Issue by cap44** [supertuxkart/stk-code#1996] opened 2015-02-22 15:14 UTC
Got the latest STK git commit (0f56a4f6d344d6db8357e614cca0bd04fe93cf2b), fired up STK. Clicked on single player, and it crashed:

#0  0x0000000000786b6c in IrrDriver::getTexture(std::string const&, bool, bool, bool) () 
#1  0x0000000000787a14 in IrrDriver::getTexture(FileManager::AssetType, std::string const&, bool, bool, bool) ()
#2  0x0000000000719bfd in GUIEngine::Skin::drawBadgeOn(GUIEngine::Widget const*, irr::core::rect<int> const&) ()
#3  0x00000000007216cb in GUIEngine::Skin::process3DPane(irr::gui::IGUIElement*, irr::core::rect<int> const&, bool) ()
#4  0x0000000000b76b00 in irr::gui::CGUIButton::draw() ()
#5  0x0000000000b76962 in irr::gui::CGUIButton::draw() ()
#6  0x00000000006e380a in irr::gui::IGUIElement::draw() ()
#7  0x0000000000ae2d81 in irr::gui::CGUIEnvironment::drawAll() ()
#8  0x00000000006d0292 in GUIEngine::render(float) ()
#9  0x0000000000787991 in IrrDriver::update(float) ()
#10 0x00000000006c4734 in MainLoop::run() ()
#11 0x00000000006380ee in main ()

**Comment by hiker** [comment] 2015-02-22 20:54
I assume that this is reproducible? Are there any messages to stdout.log?

If there is nothing: The commit you pointed out is very very unlikely to cause a problem, could you perhaps git bisect to find out which commit triggered the problem?

**Comment by cap44** [comment] 2015-02-23 12:16
yes, it is reproducible via GDB. No there's nothing in stdout.log that points to this issue

**Comment by hiker** [comment] 2015-02-24 22:24
Can you try a debug build so we can get line number information and post the full stdout.log file. Also in gdb use "thread apply bt all", so we can see what all threads are doing.

**Comment by cap44** [comment] 2015-02-25 13:11
Actually? I could not reproduce this issue for a strange reason

**Comment by hiker** [comment] 2015-03-01 21:07
Closing this since it appears non reproducible.

Thanks for the report!
   Joerg

**Closed by hiker** 2015-03-01 21:07 UTC
Labels: P1: critical
