### ISSUE TITLE
New ideas for SuperTuxKart

### ISSUE THREAD

**Issue by qaugustijn** [supertuxkart/stk-code#2407] opened 2015-12-20 09:21 UTC
I have some new ideas for SuperTuxKart:
- Soccer and 3 strikes battle for single player
- Egg hunt for multiplayer (who find the most eggs wins the game)
- Internet multiplayer (worldwide)
- Groep management for karts and tracks (you can make your own groeps for karts and tracks and save then in the main data for supertuxkart if you have write access or in the settings file of that user)
- SuperTuxKart for mobile phones and tablets

Are there more things that need to edit or make for guidelines, object in blender and pictures for the program?

I thinks the speed number of version 0.8.1 is funny than the place number in the speedometer of version 0.9 and 0.9.1.

**Comment by deveee** [comment] 2015-12-20 09:39
> Soccer and 3 strikes battle for single player
It doesn't have a sense, but you can play it in single player mode if you will enable artist debug mode in configuration file.

> Egg hunt for multiplayer (who find the most eggs wins the game)
Duplicate of https://github.com/supertuxkart/stk-code/issues/1103

> Internet multiplayer (worldwide)
Network multiplayer is WIP, see this branch: https://github.com/supertuxkart/stk-code/tree/refactor_networking

> SuperTuxKart for mobile phones and tablets
This has been discussed for example here:
http://forum.freegamedev.net/viewtopic.php?f=17&t=6118&p=64752&hilit=android#p64752
Generally everyone wants to have it, but nobody wants to do it :P

And for discussing general ideas, please use IRC or the forum:
http://forum.freegamedev.net/viewforum.php?f=16
They are better places for it than bug reports.

**Closed by deveee** 2015-12-20 09:39 UTC

**Comment by Benau** [comment] 2015-12-20 09:52
hi,

From your recent comments, (u mentioned amazonian journey which is old version stk,  requested purple skin which is close to ruby skin in git stk) it seems that u don't so catch up with the current development pace. If so, i strongly recommend building current git and try it, i'm sure u will be surprised.

Regarding your idea, 3 strikes single player is done in current git,  network multiplayer is on the way

**Comment by qwertychouskie** [comment] 2016-10-28 23:27
@qaugustijn Also, the Android port is being worked on now: http://forum.freegamedev.net/viewtopic.php?f=17&t=7122&sid=eb2a5b64b5926c5115d071726b40462c&p=71266#p70576
