### ISSUE TITLE
Check  ARB_draw_elements_base_vertex instead of GL_ARB_base_instance

### ISSUE THREAD

**Issue by deveee** [supertuxkart/stk-code#2726] opened 2017-01-05 09:18 UTC
It looks that we are checking the wrong extension.

As far as I see, we need:
```glDrawElementsBaseVertex```
which is guaranteed by ARB_draw_elements_base_vertex or OpenGL 3.2.

Currently we check GL_ARB_base_instance instead, but I don't see any ```glDraw...BaseInstance``` in code, so I assume that the intention was to check if it's possible to use base vertex.

Additionally we probably need ARB_instanced_arrays or OpenGL 3.2 for ```glVertexAttribDivisor```

I just created this ticket as a reminder, because it must be checked more carefully, maybe tested on older drivers etc. And it's actually not that important, because it generally works as it is.

**Comment by Benau** [comment] 2017-10-16 01:02
glVertexAttribDivisor use glVertexAttribDivisor"ARB" in stk, last time I try use glVertexAttribDivisor in intel hd3000 in windows will crash

So, if we use glVertexAttribDivisor"ARB" it should work, than we can think of port my old-sp-way drawdrawelementsinstanced for you to use in android

**Comment by deveee** [comment] 2017-10-16 07:37
As far as I see:
glVertexAttribDivisor is in: ARB_instanced_arrays / GL 3.3 / GLES 3.0
glDrawElementsBaseVertex is in: ARB_draw_elements_base_vertex / GL 3.2 / GLES 3.2
glDraw*Indirect: ARB_draw_indirect / GL 4.0 / GLES 3.1

The  GL_ARB_base_instance is for glDraw*BaseInstance and we don't use it.

But probably not safe enough to change it for 0.9.3?

And for instanced rendering in GLES 3.1 only glDrawElementsBaseVertex seems to be missing. It should be possible to apply the offset in glVertexAttribPointer instead.

**Comment by Benau** [comment] 2017-10-16 07:40
maybe for next release we can switch to instancing rendering for all cards

**Comment by deveee** [comment] 2017-10-18 09:37
Actually using eglGetProcAddress for functions that are not extensions is allowed only if EGL_KHR_get_all_proc_addresses is available or if EGL >= 1.5 (that is not widely used yet).

So it would require seperate #ifdef USE_GLES2/USE_GLES3/USE_GLES31 and then compile separate apk with API21. It's not a big problem though.

**Comment by Benau** [comment] 2018-01-11 07:58
https://github.com/supertuxkart/stk-code/commit/49568f3fd9dc3c2ba59831ef0fbddef842fe15b4

Good for you?

Also can u check if texture compression in your windows hd4000 is working, if so we can remove the GR for TC in windows(now only the skybox are compressed by GPU internally while the mesh textures can done by libsquish)

**Comment by deveee** [comment] 2018-01-11 08:18
If you set "UserConfigParams::m_force_legacy_device = true", then it will
be probably saved in config file. So that if someone runs STK with buggy
drivers, software acceleration fallback, portable installation, he will
have "force legacy device" forever (or he has to manually change
config.xml).

And after a quick look, the rest is ok. I will make some tests with texture
compression in the evening.

And the https://github.com/supertuxkart/stk-code/issues/2787 will be fixed
too by your sp.

**Comment by Benau** [comment] 2018-01-11 17:38
https://github.com/supertuxkart/stk-code/commit/7f3722d90b1b422dbe87e2d4f08924b148bf97cc better for you?

And do you want to try to make etc2 texture compression in sp_texture for android?

basically we can copy code from https://github.com/google/etc2comp, and compress in the same format as squish and save the cache (1 byte header, u32 total mipmap sizes, for i in total mipmap sizes : 4 + 4 + 4 width height and each level bytes, and the total "void*" data.

than in glcompressteximage2d just use etc2 format should be enough.

**Comment by deveee** [comment] 2018-01-11 20:08
@Benau What I mean is try to run for example:

```MESA_GL_VERSION_OVERRIDE="3.1" MESA_EXTENSION_OVERRIDE="-GL_ARB_instanced_arrays" ./build/bin/supertuxkart```

and then try to run
```
./build/bin/supertuxkart
```

In second case you still run legacy pipeline because of ```UserConfigParams::m_force_legacy_device = true;``` in irr_driver.

For example someone has GL 3.1 drivers and gets a message "Your drivers are too old, please update". And then he updated to GL 3.3 or higher, but he still runs legacy pipeline.

I also know few people that run linux with STK from pendrive on different machines.

IMO we shouldn't change UserConfigParams::m_force_legacy_device, because we don't know if user wants it and there is no way to change it back to false in STK GUI.

And btw probably ```m_supports_sp = m_supports_sp && isARBUniformBufferObjectUsable()``` is true too?

Atm. I won't experiment with etc2, maybe after wayland.

**Comment by Benau** [comment] 2018-01-12 00:42
i forget to remove the line UserConfigParams::m_force_legacy_device = true; sorry

and since we always create context with 3.1, so uniform buffer object is always present?

**Comment by Benau** [comment] 2018-01-12 04:25
ok https://github.com/supertuxkart/stk-code/commit/9ccb34c2a129d56965fe1f6d6ad788b1aa328115 this should be better?

because for osx ubo cannot be detected, but it is actually usable (confirmed by ozoneone)
and now shadow in osx is working too

**Comment by deveee** [comment] 2018-01-12 07:27
Thanks a lot!

And indeed ubo is GL 3.1, I forgot about it.

**Comment by Benau** [comment] 2018-01-13 07:49
Fixed by SP

**Closed by Benau** 2018-01-13 07:49 UTC
Labels: C:Graphics
