### ISSUE TITLE
Handle sRGB image correction in different way

### ISSUE THREAD

**Issue by deveee** [supertuxkart/stk-code#2787] opened 2017-02-12 11:57 UTC
The current solution of sRGB image correction causes too much issues:
- the ```grep -r "2\.2" | grep pow | wc -l``` command gives ```34``` for data/shaders directory and ```5``` for src directory
- GUI elements don't use sRGB correction, but karts in kart selection screen use it, so this specific case must be handled
- we must handle the case when bindless textures are used
- it needs ugly hack for intel graphics cards on linux, for which the default visual is not srgb-capable
- IIRC it causes some issues for intel HD3000 on windows
- sRGB correction in OpenGL ES renderer is done somehow automatically, depending on texture format. So glEnable(GL_FRAMEBUFFER_SRGB); doesn't take any effect there
- sRGB framebuffer in GLES renderer is available only as an EGL extension on most devices (needs EGL >= 1.5)

I think that we should pre-compute all sRGB textures in our texture manager. We already do some computations there:
```
    if (m_premul_alpha && !m_single_channel)
    {
        for (unsigned int i = 0; i < w * h; i++)
        {
            float alpha = data[4 * i + 3];
            if (alpha > 0.0f)
                alpha = pow(alpha / 255.f, 1.f / 2.2f);
            data[i * 4] = (uint8_t)(data[i * 4] * alpha);
            data[i * 4 + 1] = (uint8_t)(data[i * 4 + 1] * alpha);
            data[i * 4 + 2] = (uint8_t)(data[i * 4 + 2] * alpha);
        }
    }
```

If you need a pixel-perfect solution, we can use real sRGB correction and not just power of 2.2.

There are some adventages of this solution. For example user can choose the gamma correction factor in options, or we can assign a non-typical gamma for some tracks/textures if it's needed.

**Comment by Benau** [comment] 2017-02-12 12:08
There is a m_srgb, should be enough?

Currently srgb is set when new stktexture in stkmeshloader for layer 1 texture

**Comment by Benau** [comment] 2017-02-12 12:29
So maybe we only convert when m_srgb is true which will be made false if gles is on, intel in linux(windows hd3000 too?)

Btw i no longer need bindless workground in amd radeon in windows with recent driver, but the bindless sampler created is hard-coded to use pass 2 shader sampler, so the parameters are all the same, not sure if this should be avoided

Also make layer2 default srgb too for detail mat (if srgbable) in stkmeshloader

**Comment by Benau** [comment] 2017-02-12 16:12
Btw col.xyz *= pow(color.xyz, vec3(2.2)) from *object*pass* means mixing the "vertex color (color.xyz)" from vertex shader with the current fragment, which may not be easily avoided

**Comment by deveee** [comment] 2017-02-13 10:56
This is mostly what I mean and how it works in GLES now:
[srgb.txt](https://github.com/supertuxkart/stk-code/files/770768/srgb.txt)
sorry for whitespaces.

I don't say it's proper solution and it's not 100% identical with this what we currently have. But the general idea is to use linear colorspace and then apply gamma correction during final rendering, or convert everything at the beginning and then work on already converted values.

It would allow to remove hacks for intel on linux, HD3000 on windows and for bindless textures.

Btw. getLightFactor is probably not a good place for color correction, but only these two textures (DiffuseMap and SpecularMap) were darker than expected in GLES renderer and I couldn't find where they are prepared :p

And one thing is that I don't know if using sRGB textures gives some benefits in image quality, or it just automatically handles the color correction and nothing more?

And even with this quick and ugly hack, the images in OpenGL renderer are not that bad:
![bez tytulu](https://cloud.githubusercontent.com/assets/5108558/22880569/f4e0928a-f1e2-11e6-9e92-142dfa6b456e.png)
![bez tytulu2](https://cloud.githubusercontent.com/assets/5108558/22880570/f51d0620-f1e2-11e6-8609-53bbda83e6b6.png)
![bez tytulu3](https://cloud.githubusercontent.com/assets/5108558/22880571/f5252bde-f1e2-11e6-8911-95b2e4de2844.png)

**Comment by deveee** [comment] 2017-03-19 21:27
@Benau Any ideas how to handle it globally?

I can at least confirm that sRGB textures work for GLES renderer. Previously I messed it with GL_BGRA format and that's why it wasn't working (it requires RGBA format).

When I use sRGB textures, I can just apply pow(col, 1./2.2) on final color in getLightFactor() and in skybox shader, which gives better results for advanced lighting (though it makes non-advanced lighting too dark).

I think that we could use a linear framebuffer and manually apply gamma correction, which would allow to drop all srgb framebuffer hacks and allow to set custom gamma factor.

**Comment by Benau** [comment] 2017-03-20 00:43
give me time, too many todo now

**Comment by deveee** [comment] 2017-03-27 22:13
Here is the patch that allows to remove all ```glEnable(GL_FRAMEBUFFER_SRGB);``` calls. So that it allows to avoid the hacks for intel graphics cards and also makes it closer to GLES renderer.
[srgb3.patch.txt](https://github.com/supertuxkart/stk-code/files/873928/srgb3.patch.txt)

As far as I tested, when advanced lighting is enabled, it looks exactly the same as before. 

There are only some minor differences when advanced lighting is disabled - karts in kart selection screen are more bright than before (though maybe it's better than before). And also transparent textures (bubblegum shield, nitro particles) seem to look slightly darker (or maybe less transparent?), but I couldn't find the reason.

Also the color in ```col.xyz *= pow(color.xyz, vec3(2.2));``` could be pre-computed before rendering, so that we can remove the power of 2.2 from shaders.

And @Benau do you know where can we correct diffuse/specular values for non-advanced lighting? The getLightFactor() is not a good place for it and the b3d loader is not a good place either. And I couldn't find where this data is prepared for rendering.

**Comment by Benau** [comment] 2017-03-28 01:41
grass use non-linear "r" value of vertex color for movement, so I don't think you can pre-calculate the value

sorry I have no idea about the next question

**Comment by deveee** [comment] 2017-03-28 20:20
Heh, after looking at maybe 20 different files I discovered that it simply uses the same diffuse/specular rtts as in advanced lighting ;p

**Comment by Benau** [comment] 2017-06-20 09:21
In sp now all vertex color are pre-converted to srgb if needed, no more 2.2 in shader.

And grass seems to be ok too

**Comment by deveee** [comment] 2017-10-09 19:32
Can someone test if this workaround works better for intel HD3000 on windows?
https://github.com/supertuxkart/stk-code/tree/srgb_fb

It needs additional line in graphics restrictions:
```
<card is="Intel(R) HD Graphics 3000" os="windows" disable="FramebufferSRGB"/>
```

It uses GLES path for desktop OpenGL too, so it doesn't need srgb framebuffer at all.

And for intel on linux, I hope that if will be eventually fixed in mesa:
https://lists.freedesktop.org/archives/mesa-dev/2017-September/169979.html
This patch works just fine with both glx and egl.

**Comment by Benau** [comment] 2017-10-11 03:28
https://github.com/supertuxkart/stk-code/commit/839142b752ba991c42d4e68d43e65182c0a14846
devee actually I can run stk with advanced pipeline on with all additional settings on (even mlaa)
in hd3000 windows, and I think you want to use FramebufferSRGB as the only workaround if it works?

I think in theory you can do the same to hd2000 (not sure)

**Comment by deveee** [comment] 2017-10-11 20:19
@Benau Thanks for testing! Additionally I added a fallback for intel on linux when our workaround with alpha_channel=true failed, so the screen shouldn't be too dark anymore. At least as long as GL_FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING gives correct value.

And maybe I will look if it's easy to move the ```pow(color.xyz, vec3(2.2));``` outside of shaders.

**Comment by auriamg** [comment] 2017-10-12 00:59
After some delay, I managed to get STK to build again on my old laptop, and I can confirm that it also works fine for me on HD3000

**Comment by Benau** [comment] 2018-01-13 07:49
Fixed by SP

**Closed by Benau** 2018-01-13 07:49 UTC
Labels: C:Graphics
