### ISSUE TITLE
Win/lose animations not showing

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#823] opened 2014-02-24 23:44 UTC
**Author: hikerstk**

As reported in the forum:
http://forum.freegamedev.net/viewtopic.php?f=17&t=3725&sid=2fd9a4a007a1cd331be6b3c582880ad9

I have seen this once as well, though I need to verify that I didn't disable the animations.

**Comment by RQWorldblender** [comment] 2015-10-18 18:39
In the latest release 0.9.1, almost every mode but follow-the-leader does not have kart animations, specifically the win and lose ones, playing, even when kart animations are enabled for all. However, the human players do have their animations playing, but that is not my main concern. In the follow-the-leader mode, if the player gets eliminated, win and lose animations still play only in that mode, as displayed in the 6 screenshots below.
![addon_coyote-canyon-2015 10 18_13 28 30](https://github-cloud.s3.amazonaws.com/assets/13372387/10565712/28cd1b04-759d-11e5-8055-f49fd386fdaf.png)
![addon_coyote-canyon-2015 10 18_13 28 44](https://github-cloud.s3.amazonaws.com/assets/13372387/10565711/28cca76e-759d-11e5-8917-6cdc4d6089e3.png)
![addon_coyote-canyon-2015 10 18_13 28 47](https://github-cloud.s3.amazonaws.com/assets/13372387/10565713/28d0eb08-759d-11e5-81e6-18b212341f54.png)
![addon_coyote-canyon-2015 10 18_13 28 48](https://github-cloud.s3.amazonaws.com/assets/13372387/10565714/28d210be-759d-11e5-8d79-e2b2e0e4d19f.png)
![addon_coyote-canyon-2015 10 18_13 28 54](https://github-cloud.s3.amazonaws.com/assets/13372387/10565716/28d826ca-759d-11e5-8fb4-fdcfd947bb47.png)
![addon_coyote-canyon-2015 10 18_13 28 57](https://github-cloud.s3.amazonaws.com/assets/13372387/10565715/28d4f536-759d-11e5-953d-7fc25b079a14.png)
I wonder if not playing win and lose animations for other karts in other modes is intentional, or just a bug that I missed to get fixed in this release.

**Comment by auriamg** [comment] 2015-10-18 22:06
Hi,

I am not fully sure what you mean (not quite sure what your sentence " In the follow-the-leader mode, if the player gets eliminated, win and lose animations still play only in that mode" means). If I understand correctly, when outside of follow the leader mode, there are no win-lose animations? If that is what you mean, I cannot reproduce, I just did a regular race and my character did have a win/lose animation

**Comment by RQWorldblender** [comment] 2015-10-18 22:10
Human players still have their win/lose animations play; it is the animations of the AI karts that are not playing in all other modes. But even in the follow-the-leader mode, some AI karts still do not play win and lose animations.

**Comment by auriamg** [comment] 2015-10-25 01:48
I am unsure if there is any link with follow the leader, but in any case non-player karts indeed do not seem to play the win or lose animations

**Comment by Benau** [comment] 2015-12-31 08:01
I think I can fix this altogether with win/lose music handling

**Comment by Benau** [comment] 2016-01-01 05:40
https://github.com/supertuxkart/stk-code/commit/2aaab61f9330af229994de8ebef44c8cba93fb4f

Should be fixed, now just need proper win / lose music

**Comment by Benau** [comment] 2016-01-03 02:32
Branch merged

**Closed by Benau** 2016-01-03 02:32 UTC
Labels: P4: minor, T: defect
