### ISSUE TITLE
Game doesn't start on Windows 7

### ISSUE THREAD

**Issue by microspace** [supertuxkart/stk-code#2210] opened 2015-06-04 04:03 UTC
Video driver is up to date. Some png files are broken.
Hereis content of stdout.txt:
https://gist.github.com/microspace/bdd24b3c07c78eed7801#file-gistfile1-txt

```
---------------------------
SuperTuxKart crashed :/
---------------------------
SuperTuxKart crashed!
Please hit Ctrl+C to copy to clipboard and signal the problem
to the developers on our forum: http://forum.freegamedev.net/viewforum.php?f=16

Call stack:

 <no symbol available>
 <no symbol available>
 <no symbol available>
 <no symbol available>
 <no symbol available>
 <no symbol available>
 <no symbol available>
 <no symbol available>
 <no symbol available>
 <no symbol available>
 <no symbol available>
 <no symbol available>
 asCreateLockableSharedBool
 BaseThreadInitThunk
 RtlInitializeExceptionChain
 RtlInitializeExceptionChain
---------------------------
ОК   
---------------------------

```

**Comment by hiker** [comment] 2015-06-06 02:25
Did you compile this version yourself? We know that some png cause a warning with newer libpng, but not a crash. And the windows version comes with its own lib-png. Are you sure all assets are correct (stk-assets and the files in data)?

**Comment by cap44** [comment] 2015-07-26 15:12
@microspace Can  you provide more information about the crash?

**Comment by hiker** [comment] 2015-08-02 13:47
If you compiled yourself, could you please try our binaries? Closing this now since we can't reproduce it, and I suspect an incorrect libpng version - but please reopen if this should not be the case and you have new info.

**Closed by hiker** 2015-08-02 13:47 UTC
Labels: C:Graphics, R: worksforme
