### ISSUE TITLE
Add “malus” page in help

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#2221] opened 2015-06-23 23:38 UTC
This is a suggestion and a follow-up of #2173.

I suggest to add a new page into the help which explains the all the bad items a items can get by collecting a banana, i.e. anchor, bomb, parachute.

**Comment by hiker** [comment] 2015-08-02 14:07
Duplicate of #2174.

**Closed by hiker** 2015-08-02 14:07 UTC
Labels: C:GUI, P4: minor, R: duplicate
