### ISSUE TITLE
Speedometer is messed up (for me) 

### ISSUE THREAD

**Issue by cap44** [supertuxkart/stk-code#2001] opened 2015-02-23 18:54 UTC
This is mostly a GUI bug but the speedometer is messed up (for me) - the speedometer mask and the speedometer itself don't line up at all.

**Comment by cap44** [comment] 2015-02-23 19:08
![snapshot9](https://cloud.githubusercontent.com/assets/8017401/6334869/04b0daba-bba0-11e4-87e1-12a12316dff7.png)

**Comment by deveee** [comment] 2015-02-23 19:20
Duplicate of #1954

**Comment by hiker** [comment] 2015-02-23 22:38
Hmm - I might reopen this. I agree, the missing part of the speedometer is #1954, but still the two textures should at least align properly. It might be that one computation is based on different coordinates (e.g. lower right corner for one, upper right for the other??)

**Comment by cap44** [comment] 2015-02-24 09:28
This sounds weird, but if I increase the resolution to 4:3 1024x768  or 16:9 1366x768 the speedometer gets misaligned 

1366x768 is the highest resolution my monitors  support

**Comment by hiker** [comment] 2015-02-24 10:24
Can you confirm that the problem goes away if you use fullscreen mode?

**Comment by cap44** [comment] 2015-02-24 11:00
it goes away in full screen mode, not windowed mode

**Comment by hiker** [comment] 2015-03-01 20:45
Why did you close that ticket - was it fixed/worked around? While the main reason is a duplicate of #1954 , I want a work around for this (#1954 is too difficult to fix in the remaining time) for the next release.

**Comment by deveee** [comment] 2015-03-01 21:05
This bug is non-trivial too... It uses two different methods to draw shadow and main speedometer. These are functions draw2DImage and draw2DVertexPrimitiveList. 

Maybe there is something wrong in vertices definitions (drawSpeedEnergyRank function). It looks like it was workarounded by ```P.y *= -1;``` line in primitive2dlist.vert. Without this line it is displayed in upper right corner.

**Comment by auriamg** [comment] 2015-03-01 23:46
Possibly we could use draw2DVertexPrimitiveList to draw both

**Comment by auriamg** [comment] 2015-03-02 00:59
Could anyone with the bug try branch "SpeedometerFix"? I used draw2DVertexPrimitiveList  to draw the background too, so foreground and background should now match

**Comment by auriamg** [comment] 2015-03-02 02:14
After more investigation, it turns out that draw2DVertexPrimitiveList renders correctly because it relies on  irr_driver->getVideoDriver()->getCurrentRenderTargetSize(); and not on UserConfigParams::m_width/height. So probably the solution is to replace every use of UserConfigParams with getCurrentRenderTargetSize when we want to know the screen size...

**Comment by auriamg** [comment] 2015-03-02 02:42
Okay I've pushed a new version of the fix to branch SpeedometerFix, could people please test?

**Comment by deveee** [comment] 2015-03-02 06:21
Both branches SpeedometerFix and 1954-fix work fine for me. Branch 1954-fix solves problem with  speedometer too.

**Comment by auriamg** [comment] 2015-03-03 23:59
The "1954-fix" branch has been merged, this should now be fixed

**Closed by auriamg** 2015-03-03 23:59 UTC
