### ISSUE TITLE
Can't configure gamepad properly.

### ISSUE THREAD

**Issue by BramKaandorp** [supertuxkart/stk-code#3955] opened 2019-06-08 14:49 UTC
## Description

When changing the keybinds for a gamepad, the screen quickly flashes the prompt to press a button, the is gone, with the same input every time, namely Axis 7 reversed (translated from Dutch). It does this every time, and I can't revert it, so I have multiple keybinds set to this "key". First I thought it was due to a known issue with the gamepad I used at the moment, but It happens with all gamepads I own, irrespective of brand.

## Steps to reproduce

Start game with gamepad plugged in, go to options, select gamepad in controls. Try to change a keybind for the gamepad.

## Configuration

STK release version: 1.0.0 64-bit

STK Source (PPA, distribution package, official binary, etc.): STK Download page.

System: Windows 8.1 64-bit

Graphics card: NVIDIA GeForce GTX 1050 Ti

CPU: Intel Core i5-3350P Quad

Gamepads/keyboards models if related to the issue: 

## Additional information

stdout.log: 
```
[info   ] [FileManager]: Data files will be fetched from: '../data/'
[info   ] [FileManager]: User directory is 'C:\Users\Bram\AppData\Roaming/supertuxkart/config-0.10/'.
[info   ] [FileManager]: Addons files will be stored in 'C:\Users\Bram\AppData\Roaming/supertuxkart/config-0.10/../addons/'.
[info   ] [FileManager]: Screenshots will be stored in 'C:\Users\Bram\AppData\Roaming/supertuxkart/config-0.10/screenshots/'.
[info   ] [FileManager]: User-defined grand prix will be stored in 'C:\Users\Bram\AppData\Roaming/supertuxkart/config-0.10/grandprix/'.
[info   ] [FileManager]: Asset 0 will be loaded from '../data/challenges/'.
[info   ] [FileManager]: Asset 1 will be loaded from '../data/gfx/'.
[info   ] [FileManager]: Asset 2 will be loaded from '../data/grandprix/'.
[info   ] [FileManager]: Asset 3 will be loaded from '../data/gui/icons/'.
[info   ] [FileManager]: Asset 4 will be loaded from '../data/gui/screens/'.
[info   ] [FileManager]: Asset 5 will be loaded from '../data/gui/dialogs/'.
[info   ] [FileManager]: Asset 6 will be loaded from '../data/library/'.
[info   ] [FileManager]: Asset 7 will be loaded from '../data/models/'.
[info   ] [FileManager]: Asset 8 will be loaded from '../data/music/'.
[info   ] [FileManager]: Asset 9 will be loaded from '../data/replay/'.
[info   ] [FileManager]: Asset 10 will be loaded from '../data/tracks/'.
[info   ] [FileManager]: Asset 11 will be loaded from '../data/sfx/'.
[info   ] [FileManager]: Asset 12 will be loaded from '../data/shaders/'.
[info   ] [FileManager]: Asset 13 will be loaded from '../data/skins/'.
[info   ] [FileManager]: Asset 14 will be loaded from '../data/textures/'.
[info   ] [FileManager]: Asset 15 will be loaded from '../data/ttf/'.
[info   ] [FileManager]: Asset 16 will be loaded from '../data/po/'.
[verbose  ] translation: GetLocaleInfo langname returns 'nl'.
[verbose  ] translation: GetLocaleInfo tryname returns 'NL'.
[verbose  ] translation: Env var LANGUAGE = 'nl_NL'.
[verbose  ] translation: Language 'Dutch (Netherlands)'.
[info   ] tinygettext: Adding language fallback nl

[info   ] IrrDriver: OpenGL version: 4.3
[info   ] IrrDriver: OpenGL vendor: NVIDIA Corporation
[info   ] IrrDriver: OpenGL renderer: GeForce GTX 1050 Ti/PCIe/SSE2
[info   ] IrrDriver: OpenGL version string: 4.3.0 NVIDIA 430.39
[info   ] GLDriver: ARB Buffer Storage Present
[info   ] GLDriver: ARB Compute Shader Present
[info   ] GLDriver: ARB Arrays of Arrays Present
[info   ] GLDriver: ARB Texture Storage Present
[info   ] GLDriver: ARB Texture View Present
[info   ] GLDriver: ARB Image Load Store Present
[info   ] GLDriver: ARB Shader Atomic Counters Present
[info   ] GLDriver: ARB Shader Storage Buffer Object Present
[info   ] GLDriver: EXT Texture Compression S3TC Present
[info   ] GLDriver: ARB Uniform Buffer Object Present
[info   ] GLDriver: ARB Explicit Attrib Location Present
[info   ] GLDriver: EXT Texture Filter Anisotropic Present
[info   ] GLDriver: Geometry Shaders Present
[info   ] GLDriver: ARB Texture Buffer Object Present
[info   ] GLDriver: ARB Texture Swizzle Present
[info   ] GLDriver: ARB Pixel Buffer Object Present
[info   ] GLDriver: ARB Sampler Objects Present
[info   ] GLDriver: ARB Vertex Type 2_10_10_10_rev Present
[info   ] GLDriver: ARB Instanced Arrays Present
[info   ] SharedGPUObjects: Hardware Skinning enabled, method: TBO, max bones: 1024
[info   ] ShaderFilesManager: Compiling shader: C:/Program Files/SuperTuxKart 1.0.0/data/shaders/sp_pass.vert
[info   ] ShaderFilesManager: Compiling shader: C:/Program Files/SuperTuxKart 1.0.0/data/shaders/sp_solid.frag
[info   ] ShaderFilesManager: Compiling shader: C:/Program Files/SuperTuxKart 1.0.0/data/shaders/sp_shadow.vert
[info   ] ShaderFilesManager: Compiling shader: C:/Program Files/SuperTuxKart 1.0.0/data/shaders/white.frag
[info   ] ShaderFilesManager: Compiling shader: C:/Program Files/SuperTuxKart 1.0.0/data/shaders/sp_skinning.vert
[info   ] ShaderFilesManager: Compiling shader: C:/Program Files/SuperTuxKart 1.0.0/data/shaders/sp_skinning_shadow.vert
[info   ] ShaderFilesManager: Compiling shader: C:/Program Files/SuperTuxKart 1.0.0/data/shaders/sp_normal_map.frag
[info   ] ShaderFilesManager: Compiling shader: C:/Program Files/SuperTuxKart 1.0.0/data/shaders/sp_alpha_test.frag
[info   ] ShaderFilesManager: Compiling shader: C:/Program Files/SuperTuxKart 1.0.0/data/shaders/sp_shadow_alpha_test.frag
[info   ] ShaderFilesManager: Compiling shader: C:/Program Files/SuperTuxKart 1.0.0/data/shaders/sp_decal.frag
[info   ] ShaderFilesManager: Compiling shader: C:/Program Files/SuperTuxKart 1.0.0/data/shaders/sp_grass_pass.vert
[info   ] ShaderFilesManager: Compiling shader: C:/Program Files/SuperTuxKart 1.0.0/data/shaders/sp_grass.frag
[info   ] ShaderFilesManager: Compiling shader: C:/Program Files/SuperTuxKart 1.0.0/data/shaders/sp_grass_shadow.vert
[info   ] ShaderFilesManager: Compiling shader: C:/Program Files/SuperTuxKart 1.0.0/data/shaders/sp_unlit.frag
[info   ] ShaderFilesManager: Compiling shader: C:/Program Files/SuperTuxKart 1.0.0/data/shaders/sp_transparent.frag
[info   ] ShaderFilesManager: Compiling shader: C:/Program Files/SuperTuxKart 1.0.0/data/shaders/sp_ghost.frag
[info   ] ShaderFilesManager: Compiling shader: C:/Program Files/SuperTuxKart 1.0.0/data/shaders/sp_dynamic_night_bloom.frag
[info   ] ShaderFilesManager: Compiling shader: C:/Program Files/SuperTuxKart 1.0.0/data/shaders/sp_tilling_mitigation.frag
[info   ] ShaderFilesManager: Compiling shader: C:/Program Files/SuperTuxKart 1.0.0/data/shaders/sp_vertical_mapping.frag
[info   ] ShaderFilesManager: Compiling shader: C:/Program Files/SuperTuxKart 1.0.0/data/shaders/sp_road_blending.frag
[info   ] ShaderFilesManager: Compiling shader: C:/Program Files/SuperTuxKart 1.0.0/data/shaders/sp_displace.frag
[info   ] ShaderFilesManager: Compiling shader: C:/Program Files/SuperTuxKart 1.0.0/data/shaders/colorize.frag
[info   ] ShaderFilesManager: Compiling shader: C:/Program Files/SuperTuxKart 1.0.0/data/shaders/sp_normal_visualizer.vert
[info   ] ShaderFilesManager: Compiling shader: C:/Program Files/SuperTuxKart 1.0.0/data/shaders/sp_normal_visualizer.geom
[info   ] ShaderFilesManager: Compiling shader: C:/Program Files/SuperTuxKart 1.0.0/data/shaders/sp_normal_visualizer.frag
[info   ] ShaderFilesManager: Compiling shader: C:/Program Files/SuperTuxKart 1.0.0/data/shaders/screenquad.vert
[info   ] ShaderFilesManager: Compiling shader: C:/Program Files/SuperTuxKart 1.0.0/data/shaders/motion_blur.frag
[info   ] ShaderFilesManager: Compiling shader: C:/Program Files/SuperTuxKart 1.0.0/data/shaders/lightning.frag
[info   ] ShaderFilesManager: Compiling shader: C:/Program Files/SuperTuxKart 1.0.0/data/shaders/primitive2dlist.vert
[info   ] ShaderFilesManager: Compiling shader: C:/Program Files/SuperTuxKart 1.0.0/data/shaders/transparent.frag
[info   ] ShaderFilesManager: Compiling shader: C:/Program Files/SuperTuxKart 1.0.0/data/shaders/texturedquad.vert
[info   ] ShaderFilesManager: Compiling shader: C:/Program Files/SuperTuxKart 1.0.0/data/shaders/uniformcolortexturedquad.frag
[info   ] ShaderFilesManager: Compiling shader: C:/Program Files/SuperTuxKart 1.0.0/data/shaders/texturedquad.frag
[info   ] ShaderFilesManager: Compiling shader: C:/Program Files/SuperTuxKart 1.0.0/data/shaders/coloredquad.vert
[info   ] ShaderFilesManager: Compiling shader: C:/Program Files/SuperTuxKart 1.0.0/data/shaders/coloredquad.frag
[info   ] ShaderFilesManager: Compiling shader: C:/Program Files/SuperTuxKart 1.0.0/data/shaders/colortexturedquad.vert
[info   ] ShaderFilesManager: Compiling shader: C:/Program Files/SuperTuxKart 1.0.0/data/shaders/colortexturedquad.frag
[info   ] irr_driver: GLSL supported.
[info   ] HTTPRequest: Downloading https://online.supertuxkart.net/dl/xml/online_news.xml
[warn   ] track: Music information file 'amazon_jungle.music' not found for track 'Amazonian Journey' - ignored.

[warn   ] track: Music information for track 'Amazonian Journey' replaced by default music.

[warn   ] TrackManager: Track 'addon_bebelious-circuit-1' is not supported by this binary, ignored. (Track is version 5, this executable supports from 6 to 7).
[warn   ] TrackManager: Track 'addon_bebelious-circuit-2' is not supported by this binary, ignored. (Track is version 5, this executable supports from 6 to 7).
[warn   ] Track: NavMesh is not found for arena Circle of friends, disable AI for it.

[warn   ] TrackManager: Track 'addon_circle-of-friends' is not supported by this binary, ignored. (Track is version 5, this executable supports from 6 to 7).
[warn   ] track: Music information file 'jumping_to_the_stars.music' not found for track 'Las Dunas Stadium' - ignored.

[warn   ] track: Music information for track 'Las Dunas Stadium' replaced by default music.

[warn   ] track: Music information file 'TheDeadRocks-GreenSecretFromAmazonia.music' not found for track 'Lost Speedway' - ignored.

[warn   ] track: Music information for track 'Lost Speedway' replaced by default music.

[warn   ] TrackManager: Track 'addon_lost-speedway' is not supported by this binary, ignored. (Track is version 5, this executable supports from 6 to 7).
[warn   ] TrackManager: Track 'addon_nostalgia' is not supported by this binary, ignored. (Track is version 5, this executable supports from 6 to 7).
[warn   ] TrackManager: Track 'addon_old-star-track' is not supported by this binary, ignored. (Track is version 5, this executable supports from 6 to 7).
[warn   ] TrackManager: Track 'addon_paradise-peaks' is not supported by this binary, ignored. (Track is version 5, this executable supports from 6 to 7).
[info   ] addons: Downloading updated addons.xml.
[info   ] HTTPRequest: Downloading https://online.supertuxkart.net/dl/xml/online_assets.xml
[warn   ] Track: NavMesh is not found for arena STK Mercury, disable AI for it.

[warn   ] track: Music information file 'dance_cleopatra.music' not found for track 'The Old Island' - ignored.

[warn   ] track: Music information for track 'The Old Island' replaced by default music.

[info   ] GrandPrixManager: Loading Grand Prix files from ../data/grandprix/
[info   ] GrandPrixManager: Loading Grand Prix files from C:\Users\Bram\AppData\Roaming/supertuxkart/config-0.10/grandprix/
[info   ] HTTPRequest: Downloading https://online.supertuxkart.net/dl/images/32999604857af930517f49.png
[info   ] HTTPRequest: Downloading https://online.supertuxkart.net/dl/images/17205966105cf7810ab8ca4.png
[info   ] HTTPRequest: Downloading https://online.supertuxkart.net/dl/images/10636385195cf6ed6d742de.png
[warn   ] KartProperties: Can't find kart type '' for kart 'F1(ish)', defaulting to 'light'.
[warn   ] KartProperties: Can't find kart type '' for kart 'KonqiV1', defaulting to 'light'.
[info   ] HTTPRequest: Downloading https://online.supertuxkart.net/dl/images/2457019345cf781eedde04.png
[warn   ] KartProperties: Can't find kart type '' for kart 'Lamborghini LP400', defaulting to 'light'.
[warn   ] Material: Cannot determine texture full path: body.jpg
[warn   ] Material: Cannot determine texture full path: mosteztmiért.jpg
[info   ] HTTPRequest: Downloading https://online.supertuxkart.net/dl/images/17577740465cf6ecff04fac.png
[warn   ] LayoutManager: Statically sized widgets took all the place!!
[warn   ] LayoutManager: Statically sized widgets took all the place!!
[warn   ] LayoutManager: Statically sized widgets took all the place!!
[warn   ] LayoutManager: Statically sized widgets took all the place!!
[warn   ] GamepadConfig: Missing action string for pad 'Controller (XBOX 360 For Windows)' action '2'
[warn   ] GamepadConfig: Missing action string for pad 'Controller (XBOX 360 For Windows)' action '10'
[warn   ] GamepadConfig: Missing action string for pad 'Controller (XBOX 360 For Windows)' action '14'
[warn   ] GamepadConfig: Missing action string for pad 'Controller (XBOX 360 For Windows)' action '10'
[warn   ] GamepadConfig: Missing action string for pad 'Controller (XBOX 360 For Windows)' action '14'
[warn   ] GamepadConfig: Missing action string for pad 'Controller (XBOX 360 For Windows)' action '10'
[warn   ] GamepadConfig: Missing action string for pad 'Controller (XBOX 360 For Windows)' action '2'
[warn   ] GamepadConfig: Missing action string for pad 'Controller (XBOX 360 For Windows)' action '10'
[warn   ] GamepadConfig: Missing action string for pad 'Controller (XBOX 360 For Windows)' action '14'
[warn   ] GamepadConfig: Missing action string for pad 'Controller (XBOX 360 For Windows)' action '10'
[warn   ] GamepadConfig: Missing action string for pad 'Controller (XBOX 360 For Windows)' action '14'
[warn   ] GamepadConfig: Missing action string for pad 'Controller (XBOX 360 For Windows)' action '10'
[info   ] Singleton: Destroyed singleton.
[info   ] Singleton: Destroyed singleton.
[info   ] Singleton: Destroyed singleton.
[info   ] Singleton: Destroyed singleton.
[info   ] Singleton: Destroyed singleton.
[info   ] Singleton: Destroyed singleton.
[info   ] Singleton: Destroyed singleton.
[info   ] Singleton: Destroyed singleton.
[info   ] Singleton: Destroyed singleton.
```

input.xml:
```xml
<input version="1">

<!--
Event 1 : Keyboard button press
    'id' indicates which button, as defined by irrlicht's EKEY_CODE enum
    'character' contains the associated unicode character.
        Only used as fallback when displaying special characters in the UI.
Event 2 : Gamepad stick motion
    'id' indicates which stick, starting from 0
    'direction' 0 means negative, 1 means positive
Event 3 : Gamepad button press
    'id' indicates which button, starting from 0
-->

<keyboard enabled="true">
    <action name="steerLeft" event="1" id="37" character="48" />
    <action name="steerRight" event="1" id="39" character="48" />
    <action name="accel" event="1" id="38" character="48" />
    <action name="brake" event="1" id="40" character="48" />
    <action name="nitro" event="1" id="78" character="53" />
    <action name="drift" event="1" id="86" character="53" />
    <action name="rescue" event="1" id="8" character="53" />
    <action name="fire" event="1" id="32" character="53" />
    <action name="lookBack" event="1" id="66" character="53" />
    <action name="pauserace" event="1" id="27" character="53" />
    <action name="menuUp" event="1" id="38" character="53" />
    <action name="menuDown" event="1" id="40" character="53" />
    <action name="menuLeft" event="1" id="37" character="53" />
    <action name="menuRight" event="1" id="39" character="53" />
    <action name="menuSelect" event="1" id="13" character="53" />
    <action name="menuCancel" event="1" id="27" character="53" />
</keyboard>

<gamepad name ="Controller (XBOX 360 For Windows)" deadzone="4096" desensitize="0" analog="1"
         enabled="true">
    <action name="steerLeft" event="2" id="0" direction="0" range="0" />
    <action name="steerRight" event="2" id="0" direction="1" range="0" />
    <action name="accel" event="2" id="7" direction="0" range="1" />
    <action name="brake" event="3" id="3" />
    <action name="nitro" event="3" id="4" />
    <action name="drift" event="3" id="5" />
    <action name="rescue" event="3" id="8" />
    <action name="fire" event="3" id="1" />
    <action name="lookBack" event="3" id="6" />
    <action name="pauserace" event="3" id="9" />
    <action name="menuUp" event="2" id="7" direction="0" range="1" />
    <action name="menuDown" event="2" id="1" direction="1" range="0" />
    <action name="menuLeft" event="2" id="0" direction="0" range="0" />
    <action name="menuRight" event="2" id="0" direction="1" range="0" />
    <action name="menuSelect" event="2" id="7" direction="0" range="1" />
    <action name="menuCancel" event="3" id="3" />
</gamepad>

</input>
```

Error message:
```

```

**Comment by Benau** [comment] 2019-06-08 16:33
From your log you probably opened 0.9.2 of stk

**Comment by BramKaandorp** [comment] 2019-06-08 16:38
Must be an old folder. I'll see if I can find the right one.

**Comment by qwertychouskie** [comment] 2019-06-08 17:44
@BramKaandorp The folder would be `C:\Users\Bram\AppData\Roaming\supertuxkart\0.10-config\`.  Though I think this may be a dupe of https://github.com/supertuxkart/stk-code/issues/3061.

**Comment by BramKaandorp** [comment] 2019-06-08 17:57
I've updated the info. Hope it helps.

It does sound like the issue you linked to.

In addition, the gamepad name in the controls tab is always red. That's not the case on my Android tablet, so it may be related to the issue.

Also get this with a third party ps3 controller for what it's worth.

**Comment by Alayan-stk-2** [comment] 2019-07-16 10:21
Closing as duplicate of #3061

**Closed by Alayan-stk-2** 2019-07-16 10:21 UTC
