### ISSUE TITLE
Can Go Out-Of-Bounds in Snow Peak

### ISSUE THREAD

**Issue by kitokofox** [supertuxkart/stk-code#2714] opened 2016-12-31 01:41 UTC
![supertuxkart_2016-12-30_20-40-02](https://cloud.githubusercontent.com/assets/11599732/21575124/38387b50-ced0-11e6-9e6f-cd7070ceabea.png)

you have to fly off the track very fast in order to do this, via the ledge I'm looking at.

**Comment by Benau** [comment] 2016-12-31 01:42
duplicate of #2696

**Closed by Benau** 2016-12-31 01:42 UTC
Labels: R: duplicate
