### ISSUE TITLE
You can get access to magma in the arena "temple" in multiplayer mode

### ISSUE THREAD

**Issue by ianclever** [supertuxkart/stk-code#2155] opened 2015-05-01 15:17 UTC
Throughout the interior of the temple is possible fall into magma without being rescued and without losing life, sometimes the rescue works, sometimes not. However higher the speed greater the possibility from rescue does not work. see:

https://drive.google.com/file/d/0B-kzH29nQAeOSlk4YVMyN2hGd1E/view?usp=sharing

tested in arch linux (current version) and SuperTuxKart (0.9)

**Comment by Flakebi** [comment] 2015-05-01 15:58
I think the problem in @stkanon's arena is that the reset plane is slightly under the magma plain. Only if you have enough down-speed, you hit the reset plane. Otherwise the kart only touches the magma plane but it doesn't get reset.

**Comment by stkAnon** [comment] 2015-05-23 21:06
Oh yeah, this is a known issue. It's not caused by a misplaced reset plane though, because the reset is set in the material and object properties of the magma itself. IIRC, I might have mentioned it around the time I uploaded the final version of the track. After spending some time testing various ways to try and fix this, I just assumed that it was caused by a bug in the game and decided to leave it to the main team to sort out.

One thing that I think might be relevant is that I've set the lava to be an "Object". This is to enable the (admittedly barely noticeable) glow around the edges.

**Comment by Benau** [comment] 2016-04-15 13:05
When my kart fell into the lava,   const Material* material=m_terrain_info->getMaterial() material is NULL  :confused:

Seems that the "trianglemesh" for raycast doesn't includes the lava / or something else?

**Comment by hiker** [comment] 2016-04-28 02:09
The rescue 'mostly' works, triggered by a collision with the physics mesh. But in some cases it just happens that the chassis does not collide (I guess wheel suspension strong enough to prevent it), and then for reasons unknown it does not find a mesh (even though the wheels obviously do).

**Comment by hiker** [comment] 2016-04-29 15:12
Could someone re-export the temple track, and change the physical shape of the lava quad/plane in the temple from 'box' to 'exact'? A box shape in bullet does not have triangle information, so stk can not get the index of the irrlicht mesh triangle, and so can not get the texture the kart is driving on - and therefore does not detect that the kart is driving on a reset material. While this could be fixed by adding some material information to bullet, the much easier solution is to make the material exact (which means it is a triangle mesh, so bullet gets a triangle index and can then access the material properties).

To verify that it works test that the rescue animation is triggered from kart.cpp, line 1387:
```
        if     (material->isDriveReset() && isOnGround())
            new RescueAnimation(this);
```
It might in some cases still get triggered from physics.cpp line 213:
```
            if (obj->isCrashReset())
            {
                new RescueAnimation(kart);
            }
```
which is also correct. But typically the rescue in kart.cpp should be detected earlier (except for the unlikely case that the kart wheel fall through the lava, in which case the physic collision detection in line 213 will get triggered).

**Comment by Benau** [comment] 2016-04-29 16:11
Bad news:
Seems that after re-export, there are some objects (library object)? missing from the arena. So the "mini-temple" are missing, or i'm not sure if i have configured my blender correctly for library object.
Also some texture is missing in the arena. Maybe @stkAnon has an original copy of blend file?

Anyway, even i set it to "exact", still drivable on lava :/

**Comment by hiker** [comment] 2016-04-30 01:24
Oops - I just checked, the lava also needed to be set to be 'driveable'. I've just committed a manually patched scene.xml to svn, hopefully @samuncle  (or @stkAnon ) can update the .blend.

**Comment by Benau** [comment] 2016-04-30 01:53
Fun fact:
Actually setting the lava "driveable" in blend and re-export the track will not make it work. The blend itself may be broken...

So we really need the original copy from @stkAnon for complete fix.. It facilitates further works on the arena too, if someone wants to add / remove object / improving the arena

Anyway, the patched scene.xml works for me!

**Comment by hiker** [comment] 2016-05-02 02:09
As the lava in the temple does not move anymore at all, there is no reason to make it a separate physics object in the first place. So just remove the settings for the lava should solve the problem much better (less separate physical objects, of which that track has too many already ;) )

**Comment by Benau** [comment] 2016-05-02 03:28
Notice: I updated navmesh and starting position for temple arena in meda repo (revision r16591)

**Comment by Benau** [comment] 2016-05-10 04:58
http://forum.freegamedev.net/viewtopic.php?f=18&t=5771&start=25

The blend there can still be downloaded, but i'm not smart to fix the blend...

**Comment by qwertychouskie** [comment] 2016-05-10 23:29
> Anyway, the patched scene.xml works for me!

Can this be closed for now?

**Comment by Benau** [comment] 2016-05-11 00:14
The blend file needs to be fixed before closing this ticket

**Comment by qwertychouskie** [comment] 2016-05-11 00:19
OK, but maybe the milestone should be modified for 0.9.3 or later.

**Comment by auriamg** [comment] 2016-05-11 01:18
The temple blend has finally been fixed and can be cleanly exported again. However the original issue is still present, even when applying the fix described by @hiker

**Comment by qwertychouskie** [comment] 2016-05-11 01:52
In my testing, it seems to be fixed, at least mostly, as I could not reproduce the issue.

**Comment by Benau** [comment] 2016-05-11 01:56
We mean the newest model from svn, try svn up on stk-assets and stk-media repo.

**Comment by qwertychouskie** [comment] 2016-05-12 01:32
Now it seems in-between, rescue doesn't always work right away, but seems to trigger as soon as the kart runs into a wall.

**Comment by auriamg** [comment] 2016-05-13 23:58
Fixed in SVN

**Closed by auriamg** 2016-05-13 23:58 UTC
