### ISSUE TITLE
Game gets choopy sometimes while playing

### ISSUE THREAD

**Issue by aadityabagga** [supertuxkart/stk-code#1968] opened 2015-02-08 16:43 UTC
Hi,

I have had this issue since 0.8.2-beta was released (now I am on 0.8.2-beta2), on Linux.

[Youtube video](https://www.youtube.com/watch?v=Qp8F7-eieUw&feature=youtu.be) (about 1 min into the video).

What happens is that sometimes when playing a level, the game gets kind of choppy, and the framerate starts to drop (once or twice before it had crashed too, but after disabling texture compression I dont think it has crashed since ([forum link](http://forum.freegamedev.net/viewtopic.php?f=17&t=6045&start=25#p61604)) (now with 0.8.2-beta2 texture compression option is grayed out by default and cant be activated)).

Once it gets this choppy behaviour, it can be reproduced in multiple tracks (not all the time though, at some parts of the track it is choppy and at other parts its not).

System specs: http://paste2.org/I65jYt1p (I have upgraded the kernel though to 3.18)
(Intel HD 4000 inbuilt graphics, Intel-3210M processor, laptop)

Terminal output: http://paste2.org/_AxH6gn9h

I could try to run it through gdb, but I dont know if it would be any use as it rarely crashes.

**Comment by auriamg** [comment] 2015-02-11 23:46
What graphical level are you using? Intel igpus are not really designed for gaming so lower framerates are expected on demaning tracks or if the graphics options are configured on medium-to-high quality

**Comment by hiker** [comment] 2015-02-12 01:33
My suspicion is that this is related to the audio issues reported by samuncle - it has similar symptoms, and the messages (music not playing) are in stdout here as well.

**Comment by aadityabagga** [comment] 2015-02-12 04:18
Using graphical level 3 with resolution 1366x768

<a href="http://i.imgur.com/ebXzmxC.png">
  <img src="http://imgur.com/ebXzmxCl.png" />
</a>

I dont think that it is related to low-powered Intel graphics, if you look at the video in the OP I get frame rate around 45 fps, and when this bug occurs they drop to around 25 fps. And once this bug occurs in one track in a session, it seems to occur in the other tracks as well.

For the high graphics tracks like Cocoa Temple, I get lesser frame rates all the time (b/w 20 - 30 fps).

**Comment by hiker** [comment] 2015-02-12 04:26
To check if this related to an issue I am currently looking at: Do you get a flood of messages about music not playing (or similar audio related messages)? You can check ~/.config/supertuxkart/0.8.2/stdout.log
Does this happen with all tracks (esp. with math class, which is more or less the smallest track we have)? More likely with Gran Paradiso and Cocoa? Or other tracks as well?

**Comment by aadityabagga** [comment] 2015-02-12 04:32
Gotta go to college now, will try to verify when I come back. As far as I remember I could reproduce it in multiple tracks, not sure about math class as I dont play it too often.

**Comment by aadityabagga** [comment] 2015-02-12 15:31
Hi,

Did more testing here are the points:

* Was able to reproduce it on all tracks once it had started, including Oliver's math class and the extra plugin levels like the Island, paradise peaks, etc.

* Does not occur at the start of the race, but manifests itself within the first lap and continues till the end as far as I could test.

* It started on the level scotland, and as soon as it started I paused the game and looked at the terminal output which was:
~~~~
[warn   ] material: Track uses deprecated texture 'redwhite.png'
[error  ] SFXManager: SFXOpenAL OpenAL error while positioning: AL_INVALID_NAME
~~~~

* After I had gotten the error above, in subsequent levels I did not get this warning/error whenever the bug (choppiness) started.

* My testing was as follows:
Math class -> Old mine -> Scotland (bug appeared for the first time) -> Desert sand (bug appeared again after playing about 30-40sec) -> Math class (bug did not appear) -> The island (bug appeared) -> Bovine backyard (bug appeared) -> Math class (bug appeared) -> paradise peaks (bug appeared).

* Terminal output: http://pastebin.com/jLrmyna3

**Comment by aadityabagga** [comment] 2015-02-12 15:59
Played some tracks after restarting the game, did not face the bug. I thought of looking at the terminal output and I saw what I had seen the previous time even though the bug had not occured yet:
~~~~
[error  ] SFXManager: SFXOpenAL OpenAL error while positioning: AL_INVALID_NAME
~~~~

Then I thought of playing the scotland track again to see if I could reproduce it, it did not happen till I was in lap 3, and then it happened again!

The output in terminal was same too:
~~~~
[error  ] SFXManager: SFXOpenAL OpenAL error while positioning: AL_INVALID_NAME
~~~~

Complete output: http://paste2.org/_fMNFUE02

**Comment by hiker** [comment] 2015-02-12 21:06
Yes, scotland is one of the tracks that have a 'last lap' music defined (a different/faster music to be played during the last lap), and I recently fixed a bug there (plus other audio improvements). So chances are that it will work now - is there any chance for you to compile our current version? Otherwise you would have to wait for our release candidate (which shouldn't be too far away).
I'll close this ticket now, but please comment on it if you should still get this problem (or want to try to compile yourself and need help).

**Closed by hiker** 2015-02-12 21:06 UTC

**Comment by aadityabagga** [comment] 2015-02-13 15:13
I managed to compile it (with ```DCMAKE_BUILD_TYPE=RelWithDebInfo```). In the few tracks I played, I did not encounter the bug, so it may have been fixed!

Some (random) things I noticed

* Lighthouse track crashes as soon as it starts with the message:
~~~~
[error  ] main: Exception caught : [ParticleKind] Cannot locate file rain.png.
[error  ] main: Aborting SuperTuxKart.
~~~~

* In some tracks like green valley and scotland, I can hear some sounds, like mooing of cows and sheep before the race actually starts. Also at the end I think sounds of the race end and after race sometimes get mixed up.

* Music did play faster in the last lap in the Scotland track.

* Desert sands track crashed in the middle of the race with the message:
~~~~
[error  ] main: Exception caught : [ParticleKind] Cannot locate file smoke_yellow.png.
[error  ] main: Aborting SuperTuxKart.
~~~~

* Lighting effect for skid and nitro looks more interesting now.

The errors about missing textures may be due to some mistake I did when downloading/compiling.

**Comment by auriamg** [comment] 2015-02-14 22:56
I am unable to reproduce the lighthouse track, is this on a specific graphical level?

**Comment by aadityabagga** [comment] 2015-02-15 04:30
Yeah, it was on graphical level 3 on Manjaro Linux, specs in the OP.

When I play it on Slackware Linux, with graphical level 2 (as it does not have the latest drivers/mesa yet), it does not crash at start, but usually in the middle of the race with the message:
~~~~
[error  ] main: Exception caught : [ParticleKind] Cannot locate file smoke_yellow.png.
[error  ] main: Aborting SuperTuxKart.
~~~~
I think its a PEBKAC error somewhere my side.

**Comment by LFCacahuetes29715** [comment] 2015-07-29 16:29
I have the problem of "Music is not playing when it should". Can you please help me fix this error?

**Comment by hiker** [comment] 2015-07-30 05:42
Hi,

putting comments to an open ticket does not really help, we might not even notice ;)
But from the youtube comments I take it you are running 0.8.1, please update to 0.9. We won't do any more work on the 0.8 series.

Cheers,
   Joerg
