### ISSUE TITLE
Font tool build failure

### ISSUE THREAD

**Issue by cap44** [supertuxkart/stk-code#2171] opened 2015-05-02 15:49 UTC
Building the font tool fails because of a "/usr/bin/ld: ../../lib/irrlicht/libstkirrlicht.a(CIrrDeviceLinux.cpp.o): undefined reference to symbol 'XConvertSelection'
/usr/lib64/libX11.so.6: error adding symbols: DSO missing from command line" error

build log: http://pastebin.com/q5fmueGk 

openSUSE 13.2 64bit

**Comment by deveee** [comment] 2015-05-02 17:08
Caused by cmake 3.2, fixed in STK in this commit: 0f56a4f6d344d6db8357e614cca0bd04fe93cf2b. Font tool needs something similar.

**Closed** 2015-05-03 06:53 UTC
