### ISSUE TITLE
Kart getting stuck unturned in phase "zen garden"

### ISSUE THREAD

**Issue by ianclever** [supertuxkart/stk-code#2139] opened 2015-04-27 04:03 UTC
This bug occurs when the kart up on a stone in the puddle of water inside the cave, from this point it no longer responds to acceleration commands or direction, and worse, accelerates alone, you can only get out by pressing backspace. see:

https://drive.google.com/file/d/0B-kzH29nQAeOREFsU1FucGNjRjQ/view?usp=sharing

tested in arch linux (current version) and SuperTuxKart (0.9)

**Comment by auriamg** [comment] 2015-04-27 22:28
I am not sure if there is anything we can do about that, we do detect if the kart has fallen or is upside down but in this case it just stuck on a weird shape. That's why we have a rescue button :)

**Comment by qwertychouskie** [comment] 2017-09-19 22:56
No longer an issue, the kart will always make its way off the rock relatively quickly now.  Can be closed.

**Comment by Alayan-stk-2** [comment] 2018-05-20 00:08
I can't reproduce it either.

Video showing unsuccessful attempts to reproduce it : https://www.youtube.com/watch?v=jHGakwaAmGY

**Comment by auriamg** [comment] 2018-05-20 00:09
Doesn't seem to be a problem anymore, closing as can't-reproduce

**Closed by auriamg** 2018-05-20 00:09 UTC
Labels: C: 3D Modelling
