### ISSUE TITLE
Too easy to not make lap count on Hacienda

### ISSUE THREAD

**Issue by STK-FabianF** [supertuxkart/stk-code#4364] opened 2020-08-29 18:13 UTC
## Description
On Hacienda, it sometimes happens that a lap isn't counted by driving too much at the side on the start, as shown in this video:
https://youtu.be/oaDjwqbBw0M

**Comment by Alayan-stk-2** [comment] 2020-08-29 19:28
Duplicate of #4144

**Closed by Alayan-stk-2** 2020-08-29 19:28 UTC
Labels: R: duplicate
