### ISSUE TITLE
Ramp on cornfield crossing causes a warp to a diffrent than expected spot.

### ISSUE THREAD

**Issue by thekoksus** [supertuxkart/stk-code#3349] opened 2018-07-25 09:23 UTC
## Description

On Cornfield crossing, hitting the ramp in a very specific way causes the players kart to be teleported further in the track. The player is then returned to the ramp.

## Steps to reproduce

Start race on map cornfield crossing.
Drive up to the ramp.
Attempt to hit the very edge of the ramp as shown [here](https://i.imgur.com/MvJvbb5.png)
You will be teleported to a diffrent spot on the map. **This is the bug**

## Configuration

STK release version:
0.9.3 (Donator pack installed)

STK Source (ppa, distribution package, official bin,...):
Official bin

System: 
Xubuntu 16.04 (4.4.0-130-generic)

Graphics card: 
nVidia GTX 1050Ti (Propriatory binary driver installed)

CPU: 
Intel Xeon E5-1620 0 (8) @ 3.800GHz 

Gamepads/keyboards models if related to the issue:
Does not apply

## Additional information

[Replay file](https://cdn.discordapp.com/attachments/376132466152308738/471442337600634892/cornfield_crossing_2018725_1_163_571.replay)

**Comment by auriamg** [comment] 2018-07-26 00:03
I remember fixing a very similar issue not too long ago. I did some testing and could not reproduce the issue, so it should be fixed in next version

**Closed by auriamg** 2018-07-26 00:03 UTC
