### ISSUE TITLE
The nitro bar is not very informative

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#3173] opened 2018-04-01 11:30 UTC
A kart can hold at max 20 nitros, and the nitro bar reflects this.

However, while it fills up, it's difficult to gauge really how much nitro a kart has.

- The nitro bar is not divided in segments like the speed bar. 5 segments of 4 would be simple and useful.
- The thickness of the bar vary. This is misleading, as one may think that the quantity of nitro is proportional to the area and not to the angle covered. A bar with a constant thickness would be less ambiguous.
- It fills itself very unevenly (probably related to a misplaced center point). It fills itself normally at the start, then seems to fill itself quickly from 9 to 13 nitros, and then very slowly up to 20. This is very misleading. See the video : https://www.youtube.com/watch?v=T36faaq8cGc

**Comment by auriamg** [comment] 2018-04-01 14:30
Duplicate of #2822

Outside of nitro-collection challenges, showing the exact number is not something we'ere interested in, STK is a part game after all not a simulator

**Comment by Alayan-stk-2** [comment] 2018-04-01 15:09
That's not a duplicate.

For one, I don't ask for a numerical counter. For two, the way the nitro gauge fills, as shown in the video, is broken. This issue is about fixing it, not adding a counter as a workaround.

**Comment by auriamg** [comment] 2018-04-01 23:54
Okay fair enough, I've reopened it since those small changes you propose sound unintrusive and useful enough, though that goes fairly low priority

**Comment by Alayan-stk-2** [comment] 2018-04-02 19:56
After having done the code for a speedometer capable to display an increased maximum speed, I understand how this is done. It does not use an angle, but trace a polygon whose form vary according to a point moving on a square edge. That's why the way it fills itself is very uneven.

**Closed** 2018-04-11 01:14 UTC
Labels: P4: minor
