### ISSUE TITLE
Animated waving flag in the main menu

### ISSUE THREAD

**Issue by elioqoshi** [supertuxkart/stk-code#2470] opened 2016-04-18 14:56 UTC
Would you agree on animating the flag in the main menu to be waving? That would add some life to the main menu.
Similar to Crash Team Racing (beginning)
https://www.youtube.com/watch?v=3O8FK5d67cM

**Comment by auriamg** [comment] 2016-04-18 23:50
Maybe, but I'm a bit unconvinced. This may get annoying (IIRC crash team racing had a lot less menus than we had). Also, this is not possible with the current GUI engine, and this feature is probably not important enough to warrant modifying the GUI engine for that

**Comment by elioqoshi** [comment] 2016-04-19 07:42
So you say that even an animated GIF wouldn't be possible?

**Comment by auriamg** [comment] 2016-04-19 23:11
If we did it, an animated gif would definitely not be the way :) that's not the way 3D engines work

**Comment by elioqoshi** [comment] 2016-04-19 23:33
But then I'm not sure of the limitation you were referring to?

**Comment by auriamg** [comment] 2016-04-19 23:48
We'd need to make it a 3D animation. It's doable but just not a priority, atm the background is a static image

**Comment by samuncle** [comment] 2016-08-09 07:06
How is the background drawn?  If it's with a shader then it might be possible to modify it "relatively easily "

**Comment by leilei-** [comment] 2016-08-09 19:07
the way i'd do it is make a texture atlas and just change the tex coordinates over time.

**Comment by auriamg** [comment] 2016-08-10 20:24
I'm closing this because in the end this is not a bug and not a feature request that we really plan to work on at this time. It may code later, but considering we are mostly busy implementing networked multiplayer, having a waving background seems extremely unimportant in comparison

**Closed by auriamg** 2016-08-10 20:24 UTC

**Comment by samuncle** [comment] 2016-08-11 05:55
Maybe it would be better to let it open?
So anyone interested can give it a try
