### ISSUE TITLE
Kart stops accelerating when closing a dialogue box

### ISSUE THREAD

**Issue by Rnuomer** [supertuxkart/stk-code#1989] opened 2015-02-19 14:29 UTC
When STK is configured to take a gamepad button as both "Accelerate" and "Select", and the game throws a dialogue window in your face (e.g. from pausing, tutorial message or pressing "fire" when near a track in story mode), the game will forget you still have Accelerate held down until you start pressing it again

**Comment by Rnuomer** [comment] 2015-02-19 17:59
Also I should note I'm using 8.1, just from the Ubuntu repo

**Comment by hiker** [comment] 2015-02-22 21:06
Afaik there's a similar issue when opening hte in-game menu. And I vaguely remember seeing a patch for that (probably before github).

**Comment by Alayan-stk-2** [comment] 2018-04-14 16:25
Duplicate of #1021

**Closed** 2018-08-29 18:27 UTC
Labels: R: duplicate
