### ISSUE TITLE
Intel 5200 HD issue on Cocoa Temple

### ISSUE THREAD

**Issue by onetrev** [supertuxkart/stk-code#2154] opened 2015-05-01 05:41 UTC
First up before the rants about Intel graphics, ya they used to suck, but this fifth gen Intel Graphics is pretty decent! No seriously, it's true. See details below...

The actual issue I'm seeing, Cocoa Temple seems to be causing issues at certain points, even at 1366x768 and graphics level 1. I can drive along averaging 80 FPS, then in the section with the spinning gear in the middle of the track or when crossing a wooden bridge it drops to as low as 20 FPS and really stutters. 

*System Specs:*
Dell XPS 13 (2015)
Intel i5-5200u
Intel HD5500 (using latest OEM drivers, unfortunately must use those I believe)
Windows 8.1

And per [this review](http://www.ultrabookreview.com/6151-dell-xps-13-2015-9343-review/) this graphics card can play Grid 2 at the same resolution 44FPS so I'm thinking something is up! And also otherwise I've played the initial few tracks on STK 0.9 at graphics Level 3, with no issues, and easily 50FPS. 

Please let me know if I can provide any more info! Thank you!!

**Comment by HoboHacker** [comment] 2015-05-04 03:25
The game really should be more optimized for these certain places in tracks, I have experienced this same thing.

**Comment by auriamg** [comment] 2015-05-06 23:04
Hi, it's unclear what is happening since we cannot reproduce this issue on other GPUs.

If you wish to help you could follow these steps :
* Enable artist debug mode : http://supertuxkart.sourceforge.net/Artist_Debug_Mode
* In-game, in the problematic area, right-click and select the option to show the profiler
* In the same context menu, click the option to start collecting a profiler report
* Wait for about 10-15 seconds, then right-click again and stop the profiler report.
* Take the "profiler.csv" and "profiler_gpu.csv" files in your config folder and attach them to this ticket

You could also perhaps take another profiling session in a nearby area where the slowdown does not happen, so that we can compare both

Thanks!

**Comment by onetrev** [comment] 2015-05-07 04:09
Sure thing, very happy to help any way I can. Hopefully I took a long enough profile report on these. Version one is the buggy one. Version 2 is one that is fine. 

KEY NOTE though... in my case it only gets really bad after the first lap. Seriously. I tried it out I believe 5 times, same thing every time. It's slightly worse in these trouble areas than the rest of the track on the first lap, but on the second lap is when things totally break down. The wooden bridge and the gears area are fine, 50 FPS on lowest second on first lap, on the second lap 20 FPS and actually play even stops for a fraction of a second once or twice.

Both of these attached profiles are from around the same area of the track actually, but version one is on the 2nd lap, version 2 is on the first lap when it went smoothly.

Hmm, not sure how you are supposed to attached the .csv file here in GitHub. I have included a link to them in Google Drive. Link here:
https://drive.google.com/folderview?id=0BwCwPPC2GQg9fmZmbXdjYW5XT0M1M0wtam9MMkdnWUFaeDdadkVGbVNoOHVJQmx0aXNDclE&usp=sharing

Thanks!

**Comment by auriamg** [comment] 2015-05-08 00:20
Okay so here are preliminary observations :

* Large spikes in World::Update (AI)
* A few large spikes in World::Update (camera) - probably noise and not data, though
* but for the most part, the profiling looks like it's running close to 60 FPS, I see no timings in there that are consistent with 20 FPS :S What I see in profiling.csv are timings consistent with a 60-FPS run

A few things you could try : 
* Try without AI karts
* Try with sound disabled
* Do you have vsync enabled in options? both in game options and in your driver options as it may be forced in the driver (unfortunately on linux controller vsync can be a little hard). Maybe the game is sliiightly slower than 60 FPS and thus it always misses a sync and thus goes down to 30 FPS. If you noticed a 50 FPS though it's probably already disabled

does any of these changes make a difference?

But overall I'm pretty puzzled, profiling.csv contains timings consistent with a 60 FPS run

**Comment by onetrev** [comment] 2015-05-09 04:22
I tried without AI karts. Definitely was better. Still had a few glitches where game play stuttered for a split second or two and framerates dropped a little, but both were not nearly as bad.

I tried without sound and music + no AI karts. At this point definitely was much better, I did not have any of the glitches where game play stutters. So maybe something doing there? Not sure. Framerates still dropped in those two area of Cocoa temple but it was playable for sure.

Hope this helps a little because Broadwell is now powering the majority of new laptops (and some desktops) so we'll be seeing a lot of these Intel 5500 HD graphics cards and the related Intel Audio.

Let me know if I can do anything else to help resolve this, otherwise, I'll just keep on as is, and play some tracks without sound. :(

**Comment by auriamg** [comment] 2015-05-09 23:12
Okay thanks, just another test maybe, what if you play with kart but no sound? Just so that we know which is the biggest culprit, karts or sounds

**Comment by onetrev** [comment] 2015-05-10 15:09
Whoops, sorry should have test that combination as well. Playing with AI karts but no sound, is actually fairly good, no major framerate slow downs for sure. Definitely seems like sound is the key contributor to the issue.

**Comment by hiker** [comment] 2015-05-10 23:18
Does the slowdown happen if there is some ambient noise in the track?

Could you also check if %AppData%/supertuxkart/0.8.2/stdout.log contains any warnings about "Throttling sfx - queue" ?

**Comment by onetrev** [comment] 2015-05-11 06:13
Sorry not sure what you mean regarding ambient noise in the track, I don't notice any one particular sound that sets it off.

I did review the logs though and found this near the bottom:

```
[warn   ] SFXManager: Throttling sfx - queue size 101
[warn   ] SFXManager: Throttling sfx - queue size 101
[warn   ] SFXManager: Throttling sfx - queue size 101
[warn   ] SFXManager: Throttling sfx - queue size 101
[warn   ] SFXManager: Throttling sfx - queue size 101
[warn   ] MusicOgg: Music not playing when it should be. Source state: 4116
[warn   ] MusicOgg: Music not playing when it should be. Source state: 4116
```

**Comment by hiker** [comment] 2015-05-11 06:21
OK, so the warnings indicate that the sound thread can not keep up with the amount of sfx created per frame - the frame rate is too high for what your sound card can handle.

Cocoa uses 3 sound effects: exotic bird, waterfall, river. You would be able to hear them as you get close to the emitters of those sounds. I am wondering if you can hear  one or two of those sounds (e.g. just starting) when the slow down happens? Could you perhaps send a screenshot of the location when the slow down starts, and when it finishes? Then I could try to have a look at how many sfx are playing at those places, e.g. if any of the ambient sound start there. Maybe we need to limit the number of sfx that are played at the same time? Though it is strange that the game play should become unresponsive - I'd expect that you lose some sfx (e.g. river might not be played, ...), but not that much of an impact to the fps rate :(

**Comment by onetrev** [comment] 2015-05-11 15:13
Weird! From that initial review I posted with the same system as mine playing Grid 2 at an avg of 44FPS you'd think all would be okay, as this is occuring for me with the lowest graphics settings in STK. That being said, without sound I can play all tracks at Level 3 graphics, and even Cocoa Temple has framerates in the 40's and 50's without sound.

Anyhow, the slowdown starts on this bridge in attached screenshot and finishes as soon as I'm off the bridge, and the related "wood" sound is done. It also starts and stops in the area with the big turning gear in the middle of the track, but I don't hear any particular sound in that area.

It's also significantly worse on my second lap. First lap is definitely much smoother in these area.

![cocoa_temple-2015 05 11_08 05 08](https://cloud.githubusercontent.com/assets/597601/7568071/807105e8-f7b5-11e4-8189-ff2f017c6ac7.png)

**Comment by Coeur-Noir** [comment] 2015-07-18 12:06
I have noticed the same slowdowns at the same place of that track.

STK 0.9 on Ubuntu-Unity 14.04 / Intel® Haswell Desktop / Intel® Core™ i7-4770K CPU @ 3.50GHz × 8 / ram 15,4Go

**Comment by auriamg** [comment] 2015-08-21 23:25
Is one of you able to try latest git version? There have been quite a few changes to audio management since 0.9 was released, maybe it's now better

**Comment by onetrev** [comment] 2015-08-27 22:11
Hey, sorry I tried to give a go a compile this on my Windows machine, but running into issues and a bit pressed for time for the next little bit. If no one else has tested this in a week or two I'll give it a go again!

**Comment by Coeur-Noir** [comment] 2015-08-28 09:42
I'd give it a try…

Should I uninstall actual version of STK from my pc ?

**Comment by Coeur-Noir** [comment] 2015-08-28 11:04
It's indeed better with stk from today's 2015-08-28 git !

Still a minor slow down at the same place (river) which does not prevent from playing. And this is with more "advanced" graphical options activated !

So a real progress, thx !

Still some glitches on displaying karts : 
![some_karts](https://cloud.githubusercontent.com/assets/1895947/9544945/36b52d78-4d85-11e5-823f-bd0de3c958b6.jpg)
Gimp is sun burnt, Punny and Framanouille have transparency problems, don't they ?

**Comment by auriamg** [comment] 2015-08-28 23:54
Coeur-Noir, your last post is unrelated and are separte issues. Regarding addon karts, they are not maintained by us, this appears to be issues in the models themselves and out of our control. Regarding wilber, it's known that lighting on the kart selection screen is not perfect and may eventually be improved

**Comment by Coeur-Noir** [comment] 2015-08-29 10:20
My whole latest post was not out of topic - only the last sentence, with picture - so edited it to be more topic focused !

…so with graphic level @4 I have about 18 to 20 fps most of the length of cocoa temple but only 9 to 11 near the tunnel / river before the big jump and at the beginning / end line of the track.

**Comment by onetrev** [comment] 2015-10-18 23:05
Hi @auriamg, now that 0.9.1 was released I was able to try it out. Unfortunately on my system, on Cocoa Island, there is definitely no improvement, it might even be worse. And now that I'm running Windows 10, I have the latest Intel video drivers and all audio drivers have been updated.

On Cocoa Island I still get extremely low frame rates at those two key location. My avg FPS goes from about 25 on Graphics Level 3, down to average 10-15 FPS as my race goes along.

In addition I can report sound effect and music glitches throughout on this track, especially once I've gone through one of the two key trouble spots (first main bridge and the big spinning wheel). The music and sound effects start echoing for sure.

With effects and music disabled I can average 30 FPS, lowest value of 20FPS, and all around the STK UI seems more responsive. Sorry I know without being able to replicate this there is nothing much you can do, just wanted to report this, especially because it seems odd this would be happening for a good new high end laptop that is very popular. :)

**Comment by onetrev** [comment] 2015-10-23 19:27
Actually almost feel the subject of this issue should be changed.

I can put the Graphics Level down to 1 and still it plays about the same frame rate, and most importantly it still bogs down significantly at the two trouble spots. On the wooden bridge, frame rate goes to < 10FPS and actually game play stutters, start/stop movement of cart, with probably pauses as long as half a second. 

Anyway, it's definitely something up with the sound, it's not a graphics issue at all. Hope that helps!

**Comment by auriamg** [comment] 2015-10-24 16:06
Could try looking at task manager (or equivalent for other systems) while experiencing the slowdowns? I am wondering if maybe the CPU might be at 100%, and disabling sounds just frees up the CPU a little bit. After all I think we all have quad-code i7 CPUs or so, maybe people with less poweful CPUs (or with fewer cores) may max it out at 100%? That's the only explanation I currently have as to why the sound would make such a difference, so if you could please check that it may help us

**Comment by onetrev** [comment] 2015-10-25 02:35
Will do for sure! Unfortunately, STK is crashing for me upon race start now, so I can't test this out. Bummer! Posting issue in other forum as Crash Report specifies.

**Comment by onetrev** [comment] 2015-10-25 03:35
Right o, after a few crashes, got a few races to load so I could test this.... My Haswell i5 5200U is pretty decent but ya definitely no desktop i7 processor! :)

However, during race testing, Cocoa Temple and others sometimes started at 100% when the race started, but quickly settled down to 40-80% CPU, never going beyond 90%. Even on the bridge on Cocoa Temple where the game crawls to almost a stop (I timed it out, took me 9 seconds to cross the short bridge!), the CPU was never higher than 80%.

Not sure that helps, but that's the data I collected.

**Comment by hiker** [comment] 2015-10-25 12:28
Can you try collecting the profile data (as explained by auria above) again? Best to collect it once just after racing for a few seconds (ideally with just 1 kart if you can produce this issue this way), and then again at the location where the slow down happens, and post the profiles?

Do you have the same problem in snowtuxpeak? It has basically the same sfx on the bridge.

**Comment by onetrev** [comment] 2015-10-25 16:22
Profile data captured. Both at the start of the race and after a lap completed on the wooden bridge.

https://drive.google.com/folderview?id=0B2n2pJDJGCwAcG5ldms4VHZjV1k&usp=sharing

I haven't completed enough challenges yet since my clean instead of STK 0.9.1 so I don't have access to SnowTuxPeak yet.

But worth keeping in mind basically once I hit the bridge and thereafter the sound and music for the game is definitely glitchy. The sound effects and music echos and is super slow sounding. It's like the tempo of the music and effects are 1/2 the speed they should be plus it echos. And that continues throughout the rest of the race once it starts. 

And once these sound/music glitches start the all around gameplay / frame rate slows down and starts to stutter a bit. It is much much worse as detailed above on the bridge and where the big spinning gear is but seems like something bigger than just those two areas because that echo-ing and music slow down shouldn't continue throughout the track right? This does not happen on any of the other 4 tracks I've raced on this version.

**Comment by auriamg** [comment] 2015-10-26 01:31
okay just noting down the long discussion we had on IRC

what happens is that due to how the bridge is made of planks, the game is continuously deleting and creating sound sources to the frequent change of material under the kart, and creating sources is synchronous (contrarily to the rest of audio processing which happens in a thread) and any operation touching OpenAL can potentially be slow

**Comment by onetrev** [comment] 2015-10-26 05:44
Makes sense for sure. Thanks for the update! Only concerns before I close this issue then, just want to make sure there isn't something being missed.

1) Why then is the sound/music malfunctioning (echoing and/or very slow tempo) throughout the rest of the race once the main trouble spots are passed?

2) Why such a major slow down when the CPU isn't maxing out even in these areas?

**Comment by hiker** [comment] 2015-10-26 05:48
Please don't close it for now - we are evaluating a patch, and will need your feedback (at this stage we can only see very small peaks, and just hope that they are the reason for the slow down in your case). Would you potentially be able to build your own version of STK to test it?

1) We think that openal is swamped with requests, which might cause some issues or expose some bugs (either in STK or OpenAL).
2) Because this is a single threaded bottle neck, all done in the main thread, so all other CPUs will not be affected (the actual playing of the sounds happens in a separate thread, but not the creation). It could be that the main thread even sleeps in a lock, not even using CPU time.

**Comment by onetrev** [comment] 2015-10-26 06:07
Ah okay, gotcha. For sure will keep open. And thanks again for working on this!

Regarding testing, I might be able to build my own version of STK when the time comes. Just depends on my workload -- it just might take me a bit. Also when trying to build before I had some issues access the SVN repo, password requirement or something if I recall, but can sort that out when need be.

**Comment by hiker** [comment] 2015-10-27 12:29
I've submitted a simple patch that should improve the situation (though not perhaps completely fix it).

Could you try to compile your own version? If you have problems with that, please let me know and I'll compile a binary for you.

**Comment by deveee** [comment] 2015-10-27 12:32
I was modifying the code which handles bridge sound in the past. There was
an issue that the sound was still playing when a kart was flying or
stopped. Maybe it checks sound state or pauses/resumes the sound too
frequently?

Also if this is a bug in openal, you can check the current version. Remove
openal32.dll from supertuxkart directory and install current version from
their website:
https://www.openal.org/downloads/oalinst.zip

I personally didn't notice such slowdowns, even on very old hardware.
Though I almost always was playing on linux.

**Comment by onetrev** [comment] 2015-10-27 23:23
Hi @hiker ... really sorry to ask this. But any chance you can compile this for me? I'd have to install everything again to try and compile this as the only thing I run normally locally is a git client.

**Comment by hiker** [comment] 2015-10-28 03:09
Here the IRC log with details. A better fix (detecting if an already playing SFX is played again, and if so, just modify the location of the already playing effect instead of destroying the old one and creating a new one). Also perhaps create the effects in the audio thread instead of in the main thread.

00:26 < Auria1> it's the part between "const Material* material=m_terrain_info->getMaterial();" and "}   // if there is material", trying to further reduce it
00:26 < Auria1> oh when I said it's not materials actually I was looking at material *GFX* not SFX
00:35 < Auria1> hiker: the slowdon is associated to http://pastebin.com/wKBEiVtC
00:35 < Auria1> don't know more precisely atm
00:36 < hiker> Can you check if perhaps RescueAnimation is triggered?
00:36 < Auria1> still cornering it down
00:37 < hiker> But there's nothing RescueAnimation that I can see that would cancel the animation :(
00:38 < hiker> But it is related to the holes in the bridge then
00:38 < hiker> It
00:38 < hiker> It's the !material branch
00:38 < Auria1> hmm actually there appears to be more than one source of slowdowns
00:39 < Auria1> this is also a problem : http://pastebin.com/FteHuPe9
00:39 < Auria1> could it be repeatedly creating and deleting source sources?
00:39 < hiker> Yes, good idea
00:39 < hiker> Very good idea
00:39 < hiker> We keep track of 2 sfx iirc
00:39 < hiker> But with the bridge the sfx would be cancelled
00:39 < Auria1> this also comes up :
00:39 < Auria1>         if(m_previous_terrain_sound)
00:39 < Auria1>         {
00:39 < Auria1>             m_previous_terrain_sound->deleteSFX();
00:39 < Auria1>         }
00:39 < hiker> when driving between the wooden parts
00:40 < hiker> Yep, that's what I am talking of
00:40 < Auria1> perhaps simply logging created and deleted sources would help
00:40 < Auria1> profiling is just a littl3e annoying since the slowdowns are not quite on the same place every time I run it
00:41 < Auria1> we also have some issues with the profiler, sometimes it doesn't get the same amount of push and pops sigh :(
00:41 < hiker> :(
00:42 < Auria1> that can mess up the output
00:42 < Auria1> profiler should ideally be scoped I guess so that's it's always cleaned but that's a big change
00:42 < hiker> In case that three sfx needed to be played (i.e. a previous is
00:42 < hiker>     // playing, a current is playing, and a new terrain with sfx is
00:42 < hiker>     // entered), the oldest (previous) sfx is stopped and deleted.
00:43 < hiker> I wonder if we could test if the new sfx is the same as the previous sfx
00:43 < hiker> Atm we test material, and because of the holes in the bridge, we always get different material than the current sfx
00:43 < Auria1> or just keep "X" most recent sounds (say 3 last)
00:44 < hiker> Well, atm we keep the previous
00:44 < hiker> What about a simple test:
00:44 < hiker> in Kart::handleMaterialSFX
00:44 < hiker>     if(getLastMaterial()!=material)
00:44 < hiker> add:
00:44 < hiker> .. && !m_previous_sfx
00:44 < Auria1> if(getLastMaterial()!=material) doesn't check if the new material actually has a sounds though
00:44 < Auria1> just restricting to materials that actually have sounds would help
00:44 < hiker> So, instead of dropping the previous one in this case, we just don't create a new one
00:45 < Auria1> "m_previous_sfx" does not exist
00:45 < hiker> De-facto is shouldn't matter,but this could avoid the re-creation of the sfx
00:45 < Auria1> m_previous_terrain_sound ?
00:45 < hiker> So, we have m_terrain_sound and m_previous
00:45 < hiker> So each time you enter a new board on the bridge
00:45 < hiker> a new sfx is added
00:46 -!- oblo [~oblo@host128-178-dynamic.6-87-r.retail.telecomitalia.it] has quit [Quit: Sto andando via]
00:46 < hiker> and the previous one (from two boards back) is deleted
00:46 < hiker> With this test we would just not create more sfx if two are already playing
00:46 < hiker> that should verify if it is the constantly creation of sfx
00:46 < Auria1> your test doesn't compile
00:47 < hiker> Ahj, sorry
00:47 < Auria1> well m_previous_sfx doesn't exist. probably it's easy to change but I know very little of that code
00:47 < hiker> m_previous_Terrain_sound
00:47 < hiker> lower case T
00:47 < Auria1> I'd also like to find what screws up the profiler though, as this messed up the output :(
00:49 < Auria1> no idea how to find that though
00:51 < Auria1> ah no I know what messed it up, the issue is that it doesnt take the same path on every frame so the report doesn't know what to use as header
00:51 < Auria1> probably the profiler report should deal with that better
00:52 < Auria1> even with your change I still get peaks in handleMaterialSFX
00:53 < hiker> :(
00:53 < Auria1> but anyway we really need to fix the profiler report, I can't ever be sure my readings are accurate
00:54 < samuncle--> Hiker how can I wrote something for free game dev blog?
00:54 < Auria1> I'm seeing spikes around " body->setGravity(gravity);" but can't be sure
00:54 < hiker> The other thing to try would be to modify the modelling, so that there is no gap between the boards (adding a transparent part of the wood textures there)
00:54 < hiker> samuncle--: I'd guess to contact the admins
00:54 < samuncle--> Ok
00:54 < samuncle--> I thought you wanted to write one
00:54 < hiker> That sounds strange, set gravity just changes a variable .. iirc, let me check
00:55 < samuncle--> But I can ask them
00:55 < hiker> Auria1: more or less - it sets two values, m_gravity and m_gravity_acceleration
00:56 < Auria1> hiker: don't search too much, I think it may be a case of the profiling report being messed up
00:56 < Auria1> will definitely need to fix that, not sure how though
00:56 < Auria1> how do we handle different exection paths in a csv??
00:57 < Auria1> trying to something hackish, will just output the column names on every line
00:58 -!- Jammy|zedding [~dunno@cpc73517-shef13-2-0-cust413.17-1.cable.virginm.net] has quit [Quit: t5efgfdag]
01:01 < hiker> No idea, I was never much involved in our profiling implementation
01:01 < hiker> I can recommend a nice open source tool :P
01:02 -!- samuncle- [~lnum131@095-097-034-099.static.chello.nl] has joined #stk
01:02 -!- samuncle-- [~lnum131@095-097-034-099.static.chello.nl] has quit [Read error: Connection reset by peer]
01:02 < Auria1> okay since hacking the report I seem to get a lot less peaks indeed
01:03 < hiker> with the modified sfx handling?
01:03 < Auria1> yes, I can perhaps try without to compare
01:03 < hiker> Yep
01:03 < Auria1> I got on small peaks, but much less than before
01:03 < Auria1> okay trying again without
01:07 < Auria1> hiker: confirmed, without your fix then the materialSFX method frequently takes 15ms to execute
01:07 < Auria1> seems quite a bit better with the fix
01:09 < hiker> Does the sfx still sound ok?
01:09 < Auria1> haven't done extensive tests
01:09 < hiker> I would expect with recreating it all the time we get a better
01:09 < hiker> 'bump' effect
01:09 < Auria1> in my short tests it sounded okay
01:09 < hiker> I mean ... the "bong   bong   bong   bong ..." whenever we hit a new board
01:10 < hiker> We would need to look into that section in more detail, but I think it should be a pretty safe fix

**Comment by hiker** [comment] 2015-11-09 13:09
Hi Onetrev,
finally I had some time to create a new executable:
https://www.dropbox.com/s/gw3zp4xt5hlvh6v/supertuxkart-0.9.1-audio-test.exe?dl=0
Just copy the file next to the existing supertuxkart.exe, and try starting it.

**Comment by Benau** [comment] 2015-11-09 16:31
@hiker i want to point out that your exe require freetype6.dll (and data/ttf/ font files too) to work!
```
objdump -x supertuxkart-0.9.1-audio-test.exe  |grep DLL
 vma:            Hint    Time      Forward  DLL       First
	DLL Name: KERNEL32.dll
	DLL Name: USER32.dll
	DLL Name: ADVAPI32.dll
	DLL Name: pthreadVC2.dll
	DLL Name: libcurl.dll
	DLL Name: OpenAL32.dll
	DLL Name: OPENGL32.dll
	DLL Name: freetype6.dll
	DLL Name: HID.DLL
	DLL Name: SETUPAPI.dll
	DLL Name: IPHLPAPI.DLL
	DLL Name: MSVCP140.dll
	DLL Name: VCOMP140.DLL
	DLL Name: WS2_32.dll
	DLL Name: WINMM.dll
	DLL Name: VCRUNTIME140.dll
	DLL Name: api-ms-win-crt-runtime-l1-1-0.dll
	DLL Name: api-ms-win-crt-stdio-l1-1-0.dll
	DLL Name: api-ms-win-crt-filesystem-l1-1-0.dll
	DLL Name: api-ms-win-crt-math-l1-1-0.dll
	DLL Name: api-ms-win-crt-heap-l1-1-0.dll
	DLL Name: api-ms-win-crt-utility-l1-1-0.dll
	DLL Name: api-ms-win-crt-environment-l1-1-0.dll
	DLL Name: api-ms-win-crt-time-l1-1-0.dll
	DLL Name: api-ms-win-crt-convert-l1-1-0.dll
	DLL Name: api-ms-win-crt-string-l1-1-0.dll
	DLL Name: api-ms-win-crt-locale-l1-1-0.dll
	DLL Name: GDI32.dll
```
(assume @onetrev is using 0.9.1 stk)
You can try to get freetype6.dll from here:
https://github.com/supertuxkart/dependencies/tree/master/windows/dependencies/dll

font file (mkdir ttf in your data):
https://github.com/supertuxkart/stk-code/tree/master/data/ttf

**Comment by onetrev** [comment] 2015-11-09 20:25
Got the font directory setup... But having trouble installing the dll file. Frustrating, because I think I'm doing it right. File moved to C:\Windows\SysWOW64\  .... Running Command Prompt in Admin mode... I'm in C:\Windows\SysWOW64\ directory, and using this command:
`regsvr32 C:\windows\syswow64\freetype6.dll` and I keep getting "Specified Module Could Not Be Found"

**Comment by hiker** [comment] 2015-11-09 22:27
Oops, sorry - my mistake, I copied the wrong executable (current git, not the 0.9.1-patched one).

I've uploaded a new binary:
https://www.dropbox.com/s/1hkf3icqzpf4yhl/supertuxkart-0.9.1-audio-test2.exe?dl=0

Note that it is called test2 ;)

**Comment by onetrev** [comment] 2015-11-09 23:36
Got it! Tried it! When my system didn't crash when the track loaded (already reported that issue on the forum) I was able to do some tests. The framerate is definitely a little better on the bridge. 

But the bigger issue is still there. The whole sound effects and music for this race breaks down. Forget about the bridge and gear section. As noted above, there is clipping, off tempo sound effects and music. It's like someone slowed down the playback on an old record! :)  Maybe we should just give up hope on it and move on?

**Comment by hiker** [comment] 2015-11-10 00:57
Auria already implemented the much better fix. Can you try the following:
https://www.dropbox.com/s/7s86yxavf8z6ibg/supertuxkart-0.9.1-audio-test3.exe?dl=0

Thanks!
  Joerg

**Comment by onetrev** [comment] 2015-11-10 02:55
Tried test3.... even better framerates over the bridge! Good news there! BAD news is most definitely we still face broken sound and music basically once I go over the bridge. The echoing and severe music speed slow down happens exactly the same.

**Comment by hiker** [comment] 2015-11-10 03:12
What happens if you drive the track in reverse (i.e. without crossing the bridge). Is the sound music and sound still broken then?

**Comment by onetrev** [comment] 2015-11-10 03:26
Well technically Cocoa Temple doesn't have a "reverse" option... But I just tried it by driving the wrong way at the start then back forward again and around the start area, before the bridge. And indeed the sound and music glitch started happening again with no bridge involved.

**Comment by hiker** [comment] 2015-11-10 03:32
So that's very likely a completely unrelated issue. I am closing this ticket now, can you open a new ticket for this issue? Can you include what happens when you disable sfx and/or music - does this have any impact?

**Closed by hiker** 2015-11-10 03:32 UTC
Labels: R: fixed

**Comment by onetrev** [comment] 2015-11-10 03:43
Agreed. Sorry got some false positives initially. This is definitely a different issue. I will post details for sure in bit / tomorrow.
