### ISSUE TITLE
License says "Copyright Â© 2007" with a Â charachter

### ISSUE THREAD

**Issue by scootergrisen** [supertuxkart/stk-code#2544] opened 2016-07-02 12:55 UTC
Windows installer for STK 0.9.2 have a Â character in the GPL license that is showed during installation just before "© 2007 Free Software Foundation, Inc."

It look like "Copyright Â© 2007 Free Software Foundation, Inc."

**Comment by scootergrisen** [comment] 2016-07-02 12:55
![stk1](https://cloud.githubusercontent.com/assets/1836590/16540437/022281b8-4065-11e6-9c77-c97aa2bc894b.png)

**Comment by scootergrisen** [comment] 2016-07-02 12:57
Also there is a long __________ line that wraps.
Maybe it would be better to show the license in it own box or something so that line is not needed.
![stk2](https://cloud.githubusercontent.com/assets/1836590/16540440/0ee98248-4065-11e6-9eee-f2371422c87d.png)

**Comment by auriamg** [comment] 2016-07-03 00:24
@hiker maybe an encoding issue in the installer?

As for the wrapping "____", yes it happens but it's exessively minor and I don't think anyone cares about that...

**Comment by qwertychouskie** [comment] 2016-07-11 00:45
`COPYING` seems to be UTF-8, but that needs [a Unicode version of NSIS](http://www.scratchpaper.com/).

**Comment by qwertychouskie** [comment] 2016-07-24 00:29
Also see https://en.wikipedia.org/wiki/Nullsoft_Scriptable_Install_System, towards the bottom.  Maybe we just need to use v3.0-rc2?

**Comment by qwertychouskie** [comment] 2016-10-05 22:25
From http://nsis.sourceforge.net/Download:
> NSIS 3.0
> Released July 24, 2016 
One day after I suggested 3.0-rc2 :)
Now that it is officially stable, it probably should be upgraded in STK.

**Comment by qwertychouskie** [comment] 2016-12-07 21:00
Obsoleted by #2661 (since the issue is really about Unicode support in the installer), can be closed.

**Comment by hiker** [comment] 2017-10-23 23:38
Fixed in 6476af46cdf1c0279e6b11a208059eec827ff45b.

**Closed by hiker** 2017-10-23 23:38 UTC
Labels: P4: minor
