### ISSUE TITLE
Skidding responsiveness issues

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#3625] opened 2018-11-26 05:48 UTC
This issue is related to the fix of #3168. Simply reverting that fix and getting back the old issue would be a poor outcome, so I want a proper solution which really eliminates this serie of issue.

In the majority of situations, skidding will work fine, but when switching from one direction to another, issues still arise.

- If the check to not skid in the wrong direction is triggered, STK will wait until the system sends another key input to finally trigger skidding. Instead of skidding at the earliest possible time, it will have a significant delay which may mess badly with trajectories. To test the delay, just press a key in any text editor/box. The delay you will see between the first apparition of the pressed symbol and its repetition (ddddd...) corresponds to the skidding delay
- It is also possible to not get an expected skid at all. The easiest way to reproduce it is to quickly switch between left/right. The pattern to make the issue appear (left and right can be exchanged) :  left/right/skid while the kart still overall steers left/left/right/left/right. The skid key may remain pressed as long as wanted, no skidding will be achieved afterwards, even when doing "normal" controls, until it stops being pressed and is pressed again.

**Comment by deveee** [comment] 2018-11-26 08:08
You can't start left skidding when you have right direction etc. But you can remember that skidding is already started and wait with real skidding until direction is correct.

**Comment by Alayan-stk-2** [comment] 2018-11-26 08:46
Yes, I'm thinking about something along those lines to fix this issue.

**Comment by deveee** [comment] 2018-12-14 22:13
I was trying to reproduce the skidding with wrong direction with reverted Benau's fix and it works for me... Every time it happened for me it was because I pressed skidding key before I changed direction (which is kinda expected and it happened very rarely too), something like:
```
left 0
left 0
left 32768
left 32768
left 32768
skidding left
right 32768
right 32768
left 0
left 0
right 32768
right 32768
right 32768
right 32768
right 32768
right 32768
right 32768
right 32768
right 32768
right 32768
right 32768
right 32768
right 32768
right 32768
right 32768
right 32768
right 32768
right 32768
right 32768
right 32768
right 32768
right 32768
right 32768
skidding none
skidding none
```
And I initially thought that it uses smoothed current kart steering, but as far as I see it uses most recent left/right action to determine skidding direction. So it should work. There is only small delay when you want to use skidding immediately after previous skidding.

But I'm pretty sure it was often happening for me in the past...

**Comment by Alayan-stk-2** [comment] 2018-12-14 22:42
@deveee What change did you apply to get that log ? I will try on my side to revert the patch and see if I can reproduce the "skidding in wrong direction" issue.

Also, if I remember correctly, steering doesn't work the same way depending on input type - this isn't relevant here I guess ?

**Comment by deveee** [comment] 2018-12-15 11:10
```
diff --git a/src/karts/controller/local_player_controller.cpp b/src/karts/controller/local_player_controller.cpp
index 8c7e35fe1..d2cc59e7c 100644
--- a/src/karts/controller/local_player_controller.cpp
+++ b/src/karts/controller/local_player_controller.cpp
@@ -178,22 +178,10 @@ bool LocalPlayerController::action(PlayerAction action, int value,
         }
     }
 
-    // Check if skid key is pressed and if turn button is in disagreement
-    // with the current steering dominant, ignore the skid key press, see #3168
-    if (action == PA_DRIFT && value != 0)
-    {
-        if ((!PlayerController::action(PA_STEER_LEFT, 0, /*dry_run*/true) &&
-            m_controls->getSteer() < 0.0f) ||
-            (!PlayerController::action(PA_STEER_RIGHT, 0, /*dry_run*/true) &&
-            m_controls->getSteer() > 0.0f))
-            return false;
-    }
-
     // If this event does not change the control state (e.g.
     // it's a (auto) repeat event), do nothing. This especially
     // optimises traffic to the server and other clients.
-    if (!PlayerController::action(action, value, /*dry_run*/true))
-        return false;
+    if (!PlayerController::action(action, value, /*dry_run*/true)) return false;
 
     // Register event with history
     if(!history->replayHistory())
diff --git a/src/karts/controller/player_controller.cpp b/src/karts/controller/player_controller.cpp
index 2875456a5..13c9761e0 100644
--- a/src/karts/controller/player_controller.cpp
+++ b/src/karts/controller/player_controller.cpp
@@ -148,6 +148,7 @@ bool PlayerController::action(PlayerAction action, int value, bool dry_run)
     switch (action)
     {
     case PA_STEER_LEFT:
+        printf("left %i\n", value);
         SET_OR_TEST(m_steer_val_l, value);
         if (value)
         {
@@ -159,6 +160,7 @@ bool PlayerController::action(PlayerAction action, int value, bool dry_run)
             SET_OR_TEST(m_steer_val, m_steer_val_r);
         break;
     case PA_STEER_RIGHT:
+        printf("right %i\n", value);
         SET_OR_TEST(m_steer_val_r, -value);
         if (value)
         {
@@ -222,15 +224,32 @@ bool PlayerController::action(PlayerAction action, int value, bool dry_run)
         break;
     case PA_DRIFT:
         if (value == 0)
+        {
+            printf("skidding none\n");
             SET_OR_TEST_GETTER(SkidControl, KartControl::SC_NONE);
+        }
         else
         {
             if (m_steer_val == 0)
+            {
+                printf("skidding no direction\n");
                 SET_OR_TEST_GETTER(SkidControl, KartControl::SC_NO_DIRECTION);
+            }
             else
+            {
                 SET_OR_TEST_GETTER(SkidControl, m_steer_val<0
                                                 ? KartControl::SC_RIGHT
                                                 : KartControl::SC_LEFT  );
+                                                
+                if (m_steer_val<0)
+                {
+                    printf("skidding right\n");
+                }
+                else
+                {
+                    printf("skidding left\n");
+                }
+            }
         }
         break;
     case PA_PAUSE_RACE:
```
Or you can print keycodes in CIrrDeviceLinux to make sure that nothing is messed in input manager.

**Comment by deveee** [comment] 2018-12-15 21:33
I think that https://github.com/supertuxkart/stk-code/commit/59f29ca975974a9add5090984dd4354c48b226ef can be reverted.

I see that skidding has some inconsistencies, like when you release left/right button during skidding it goes back to SC_NO_DIRECTION, because autorepeat for skidding key is still enabled. But it seems practically impossible that you will get two skidding key events in single update and it will choose wrong direction from second event. Anyway I can probably add ```if (m_controls->getSkidControl() == KartControl::SC_NONE)``` there. Or you can change SC_LEFT/SC_RIGHT in the same way when skidding is already started, but it doesn't matter in practice. Or actually it may happen if you have too low speed and it is waiting before start skidding...

I was playing a bit on two different computers/operating systems/keyboards and skidding was always in correct direction.

Actually it may be caused by wireless keyboard. There could be delay or no event at all if poor connection.

**Comment by deveee** [comment] 2018-12-15 22:08
The patch that causes responsiveness issues is reverted and also at least one possible case for skidding in wrong direction is fixed in https://github.com/supertuxkart/stk-code/commit/24926bcb1d13122b23407478d24785c501ba2411

**Closed by deveee** 2018-12-15 22:08 UTC
Labels: C: Race Events, P2: major, T: defect

**Comment by Alayan-stk-2** [comment] 2018-12-17 10:05
I did tests with the revert and your patch fixing one possible case. My goal was to see if the "skidding in wrong direction" bug can be reproduced.

Usually, when I feel like I just reproduced it, the log is something like : 

```
right 32768
right 32768
skidding right
left 32768
left 32768
```
I added prints of the world time. When I try to reproduce the issue, I often get the skid time one frame before the direction change is registered, but when it's same frame it also triggers the bug : 
```
right 32768, world_time 1.150000
right 32768, world_time 1.150000
skidding right, world_time 1.650000
left 32768, world_time 1.650000
left 32768, world_time 1.650000
```

**Comment by deveee** [comment] 2018-12-17 10:43
Ok, so the expected result is that it will use skidding in right direction
(because right key was pressed before), but it used skidding in left
direction instead? Or you feel that you pressed left key before skidding,
but STK received them in single frame in wrong order? I will look if it's
possible that events order is messed (IIRC there was ie. a hack for
autorepeat on linux).

**Comment by Alayan-stk-2** [comment] 2018-12-17 11:08
> Ok, so the expected result is that it will use skidding in right direction (because right key was pressed before), but it used skidding in left direction instead?

That's a description of the "wrong skidding direction" bug (#3168) yes, with left/right which can be changed.

> Or you feel that you pressed left key before skidding, but STK received them in single frame in wrong order? I will look if it's possible that events order is messed (IIRC there was ie. a hack for autorepeat on linux).

Well, my feel from how I was annoyed by this issue in 0.9.3 was that I pressed the direction change before the skid key, but with "feel" it's hard to tell for sure.

Maybe it would be better to have a consistent behavior if both events are received on the same frame no matter the real order they went in.

I'll do more tests.

**Comment by Alayan-stk-2** [comment] 2018-12-17 11:30
After more tests on 0.9.3 and git : 
- I don't feel a significant behavior different between 0.9.3 and git. This means it is likely that part of what I thought was incorrect behavior was in fact correct with STK receiving the skid input before the turn input (be it because I really pressed the skid before the turn, or because of some error).
- If I press skid+directionA after the end of a skid then keep pressing skid but switch to directionB, when the graphical animation ends and skidding is again possible, it skids in directionA. Really a corner case, but weird.

**Comment by Alayan-stk-2** [comment] 2018-12-18 05:47
The logs didn't indicate anything particularly suspicious, so let's consider the issue resolved for now. If there is really still an issue, we'll find about it again soon enough.
