### ISSUE TITLE
Ghost villa: Holes and holes

### ISSUE THREAD

**Issue by lightonflux** [supertuxkart/stk-code#2234] opened 2015-07-06 21:50 UTC
The track with the ghost villa has many places where on can fall through the map. Which is especially surprising as it is one of the egg hunt maps. 

Drive to the door of the villa and then left in front of the house. Drive over the edge you see in this screen and you fall:

![bildschirmfoto von 2015-07-06 22 30 34](https://cloud.githubusercontent.com/assets/1377943/8534022/114049bc-2439-11e5-9908-abb210acb0ec.png)

Same thing on the right side: 
![bildschirmfoto von 2015-07-06 22 30 09](https://cloud.githubusercontent.com/assets/1377943/8534030/2b6a5db4-2439-11e5-90bd-79a4587634ed.png)

And you don't have to stay close to the wall, just drive right to the villa on the grass you will have another chance to kill yourself:

![bildschirmfoto von 2015-07-06 22 29 39](https://cloud.githubusercontent.com/assets/1377943/8534043/4d4bef74-2439-11e5-8bf3-161e43ab1e85.png)

Or just turn 90° to the left at the start line and die:

![bildschirmfoto von 2015-07-06 22 28 36](https://cloud.githubusercontent.com/assets/1377943/8534059/619c50b8-2439-11e5-91e9-9aae255a6600.png)

Same if you turn 180° and drive on the grey path:

![bildschirmfoto von 2015-07-06 22 24 16](https://cloud.githubusercontent.com/assets/1377943/8534073/73ee967c-2439-11e5-9d58-fbb74ae30603.png)

I think there are much more, but those are the biggest offenders right now.

**Comment by auriamg** [comment] 2015-07-07 23:04
Closing as a duplicate of #2235 - these  issues are real but the track is being redone so most of them should disappear

**Closed by auriamg** 2015-07-07 23:04 UTC
