### ISSUE TITLE
Some kind of controll issue

### ISSUE THREAD

**Issue by UbuntuJackson** [supertuxkart/stk-code#3723] opened 2019-01-23 22:58 UTC
So when I tried the new version I felt something with the controls are wrong. I first thought it was the new physics and thought that oh well, I'll get used. But it didn't go like that, it got worse. Sometimes I loose controll over the kart and drive into a lot of stuff and the controlls feels like delayed in some way and really unsteady and wobbely. I can't really turn like I want the kart to do. "Get good" you might answer, but let me tell ya, I have never had this problem in 0.9.3 or any other version for that matter. This is something that clearly appears in 0.10 for me only. I have also tried with keyboard and it's the same problem with that. I would be very, vey, very grateful if somebody could solve this, thank you in advance.
## Configuration

STK release version: 0.10 beta

STK Source (PPA, distribution package, official binary, etc.): 

System: Windows 10

Graphics card: GPU AMD Radeon(TM) RX Vega 11 Graphics

CPU: AMD Ryzen 5 2400G with Radeon Vega Graphics

Gamepads/keyboards models if related to the issue: Xbox One Controller

## Additional information

stdout.log:
```

```

input.xml:
```xml

```

Error message:
```

```

**Comment by Schyrsivochter** [comment] 2019-02-01 20:52
I’ve been having similar issues, too: controls lagging a bit and the press or release of a button sometimes not registering, though you seem to have it worse.
My OS is Ubuntu 18.10, Intel Core i5-7200U with HD Graphics 620, PS3 controller (DualShock 3) connected via Bluetooth.

**Comment by qwertychouskie** [comment] 2019-02-01 20:58
Do you guys only notice the problem in online races?

**Comment by Schyrsivochter** [comment] 2019-02-02 12:17
No, I’ve only played offline/singleplayer so far.

**Comment by qwertychouskie** [comment] 2019-02-02 18:35
Hmm... @Alayan-stk-2 can you add this to the 0.10 milestone and add T: Regression?

**Comment by Alayan-stk-2** [comment] 2019-02-02 18:59
I've discussed it several time with Ubuntu Jackson, he's recorded a full video where he played online with me showing his kart racing and his inputs on his gamepad, and I'm not convinced there is anything at all.

On keyboard, I'm quite sure there is zero regression, and I don't see how you would have gamepad inputs suddenly not being registered properly/getting random input lag.

The only reason I haven't closed this yet is that I don't have a hard proof either that there really is nothing to fix, so I let it open just in case. I will add the regression and defect labels if and when we get a clear proof of something being broken.

As UJ initially complained about steering, I strongly suspect that this is related to this change : https://github.com/supertuxkart/stk-code/commit/f3ef25d52594271f953d9db1db69a26a280309ff

Previously, you had this behavior : 
- Keyboard turning was smoothed : you couldn't get from turning full left (right) to full right (left) instantly, rather the steering of the kart changed progressively (iirc about 0.25s to go full left to full right).
- Analog joystick turning was NOT smoothed. This allowed to change the steering of the kart much more quickly than with keyboard (which is an advantage) but also made the kart steering very sensitive (which can be hard to control well). 

Now, analog joystick turning is also subject to smoothing (i.e., limit how fast you can change the steering). This is an important fix to allow full parity between keyboard and gamepad - what you can do with your kart doesn't depend anymore on your preferred input tool. STK is perfectly playable with the smoothing, as proven by me and Andet. It also helps for control on Android where the sensitivity was an issue.

A potential check would be for @UbuntuJackson or @Schyrsivochter to compile a STK git version from soon before the commit I linked to above. Playing in the version before that commit, do they still feel that something is wrong, or does it feel more like 0.9.3 ? This would allow to definitely answer if this is related to this or not.

If this is not related, then testing other versions (using a bisecting strategy) should allow to find the culprit if any.

**Comment by Schyrsivochter** [comment] 2019-02-04 18:10
At first I was like ‘what the fuck, this is unacceptable’ but then I played some more and … it really isn’t. I’ll just have to get used to it, I guess.

**Comment by UbuntuJackson** [comment] 2019-05-20 06:49
> 
> 
> At first I was like ‘what the fuck, this is unacceptable’ but then I played some more and … it really isn’t. I’ll just have to get used to it, I guess.

I probably don't have the same issue as you cause I have not got used. In my case, no this is not acceptable. The controlls where good in 0.9.3, it should be possible to make good working steering in 1.0 too.

**Closed** 2019-05-20 09:01 UTC

**Comment by qwertychouskie** [comment] 2019-05-22 19:15
Turns out the issue was @UbuntuJackson was using JoyToKey because he was hitting https://github.com/supertuxkart/stk-code/issues/3061, the problem seems absent when not using JoyToKey.

https://github.com/supertuxkart/stk-code/issues/3061 should really be fixed before the next release.
