### ISSUE TITLE
The phase "magma source" appeared as released ahead of time

### ISSUE THREAD

**Issue by ianclever** [supertuxkart/stk-code#2149] opened 2015-04-28 04:05 UTC
The bug occurs in story mode, even with a pending championship "magma source" phase was listed as released, although the door was not opened. I have no idea if it was on purpose or is it really a bug. see:
![bug_liberar_corrida](https://cloud.githubusercontent.com/assets/12104659/7362642/a38eaa62-ed42-11e4-8675-7d6208eb3eba.png)

tested in arch linux (current version) and SuperTuxKart (0.9)

And if I may suggest that you assess the level of difficulty of the way "beginner", as the kart speed is incompatible with the proposed time, so that it is easier to pass the "intermediate" mode than in "beginner" especially in stages: "Loch Ness" and 'seabed'.

**Comment by Flakebi** [comment] 2015-04-28 16:00
You probably mean the same issue that is tracked in #2004. You need to finish all challenges before the gate opens, unfortunately this isn't shown in the minimap at the moment (there it gets unlocked if you have more than a certain amount of points).

**Comment by ianclever** [comment] 2015-04-28 17:03
Yes, it's the same bug.

**Comment by hiker** [comment] 2015-04-28 23:43
Duplicate of #2004 .

**Closed by hiker** 2015-04-28 23:43 UTC
Labels: R: duplicate
