### ISSUE TITLE
Shift key warning not applicable under certain use cases

### ISSUE THREAD

**Issue by psypherium** [supertuxkart/stk-code#2898] opened 2017-08-12 18:27 UTC
There is a warning to not map the shift key. I ignored it and mapped Left Shift to boost. All my other mappings still work. For example, under Dvorak, my fire key is mapped to the period key, or the greater than symbol ( . then > ) when shift is held. This, and all other keys are mappable with no conflicts. Perhaps this issue only occurs in certain distros, or older distros. My working config is under Arch Linux (Antergos). This leaves open the possibility for a second default keyboard profile using the "wasd" keys + shift nitro + space drift + e shoot, which is much easier on the hands for most keyboard gamers.

**Comment by deveee** [comment] 2017-08-12 19:43
Duplicate of #2312.

It was always working for me, but there is too many cases - different operating systems, keyboards, languages, configurations etc... I assume that there was a reason to add this warning. From the other side, the "Alt" key seems unsafe too and there is no warning at all.

**Closed by deveee** 2017-08-12 19:43 UTC

**Comment by auriamg** [comment] 2017-08-13 22:01
I wonder if this warning is still relevant since the input code has changed a lot over the years, maybe it's no longer relevant - but then, in the past, before this warning was there, we did have a lot of bug reports related to that so not sure it's worth risking bugs

**Comment by psypherium** [comment] 2017-08-14 05:09
Maybe it could be changed to "Might stop working" instead of "Will stop working"? Also maybe add a warning that the alt key might also be unsafe? Great work with the game, I'm looking forward to the next release. I hope you have a good day.
