### ISSUE TITLE
Scotland track unexpected shortcut

### ISSUE THREAD

**Issue by Alayan-stk** [supertuxkart/stk-code#1676] opened 2014-11-07 22:43 UTC
Steps to reproduce : Start a race. Don't follow the road but go immediatly right, on grass. Go near the castle angle, keep going even if it resists somehow on the left, and fall in water. You'll then be rescued on the bridge. If you did well, it won't take more time than for the first of the AI kart to go there (in a 20 karts race I was 1st or 2nd after the bridge with it). Lap will be counted as valid once finished.

(Note : Bug detected on 0.8.1, but I doubt it has been corrected since)

**Comment by qwertychouskie** [comment] 2016-09-08 22:15
I couldn't figure out how to reproduce this, even if the shortcut still exists, it is very non-obvious.  Can this be closed?

**Comment by Alayan-stk-2** [comment] 2018-03-20 11:37
The "fall in the water" trick doesn't seem to work anymore.

However, following the path and climbing back to the road just before the bridge can still work. In my first test I managed to be 12th and 10th of 20 on the bridge, but with a bit more training, I managed 6th and then 2nd.

Adding a simple checkline in the second curve of the race should fix things without having to worry about the rest and letting track explorers be happy.

**Comment by Mrxx99** [comment] 2018-03-20 13:56
Shortly after I read this issue I found a video on Youtube, showing how to heavily cheat on Nessie's Pond AKA the Scotland track: https://www.youtube.com/watch?v=5Ckbd1VL0-o
What a coincidence :D

**Comment by Mrxx99** [comment] 2018-03-20 14:21
More tracks which can be abused:
Green Hill Valley: https://www.youtube.com/watch?v=32XM3AuQSTs
Blackhill Mansion: https://www.youtube.com/watch?v=zse0WAdl8dw

I think all these tracks are missing some checklines.

**Comment by Flakebi** [comment] 2018-03-20 14:28
Concerning the Scotland track (Nessie’s Pond):
I’m actually faster if I take the street and not the way over the grass (and there is less risk of falling in the water on the regular way).
So I’d say an additional checkline is not necessarily needed because you don’t gain an advantage over the street.
If you are skilled enough to be faster off-track, I’m impressed and you deserve it ;).

**Comment by Alayan-stk-2** [comment] 2018-03-22 05:42
@Flakebi It takes some practice to get the feel of how to do the "by the grass" way properly (the safe way use the door), but it's definitely faster. See the replays. First is the best time I did through the street (1:44:14). Second is the best I did through the grass (1:39:49). These are 3 laps race, so I wouldn't have been able to pull this out if it wasn't possible to use the shortcut with some consistency. In a race, it's probably too risky to use 3 times, but on the first lap, as there is a serious probability of eating a cake along the street, it can definitely be better with a bit of caution.

(Rename the files in .replay and put them in the appropriate folder to check it out)

[scotland_2018322_2_99_49.txt](https://github.com/supertuxkart/stk-code/files/1836226/scotland_2018322_2_99_49.txt)
[scotland_2018322_2_104_145.txt](https://github.com/supertuxkart/stk-code/files/1836227/scotland_2018322_2_104_145.txt)

Though, clearly, the video found by Mrxx99 indicates a much great issue.

The suggested additional checkline would solve it too.

**Comment by Alayan-stk-2** [comment] 2018-03-31 20:17
Fixed with #3163 and an additional checkline.

The shortcut through grass and door remains available but it offers only 1 second or so and is hard to pull off (in contrast with the "go into the water and be rescued" way described in the first post, or the checkline abuse going backwards through the river).

**Closed** 2018-03-31 22:51 UTC

**Comment by qwertychouskie** [comment] 2018-04-02 00:44
@Alayan-stk-2 I can't seem to do the grass shortcut, the replay shows it as counting laps, but doing it myself it never counts them.
