### ISSUE TITLE
Addons crash

### ISSUE THREAD

**Issue by auriamg** [supertuxkart/stk-code#3085] opened 2018-01-02 22:36 UTC
reported on the forum https://forum.freegamedev.net/viewtopic.php?f=17&t=7751&p=75460#p75460 

```
crash_reporting.cpp:CrashReporting::getCallStack:314
crash_reporting.cpp:CrashReporting::winCrashHandler:103
get_thread_local_invalid_parameter_handler
invalid_parameter_noinfo
_intrinsic_setjmpex
strftime
strftime
time.cpp:StkTime::toString:55
addon.cpp:Addon::getDateAsString:165
addons_screen.cpp:AddonsScreen::loadList:400
abstract_state_manager.cpp:GUIEngine::AbstractStateManager::pushScreen:136
main_menu_screen.cpp:MainMenuScreen::eventCallback:549
event_handler.cpp:GUIEngine::EventHandler::sendEventToUser:600
event_handler.cpp:GUIEngine::EventHandler::onWidgetActivated:651
event_handler.cpp:GUIEngine::EventHandler::onGUIEvent:693
event_handler.cpp:GUIEngine::EventHandler::OnEvent:157
cguibutton.cpp:irr::gui::CGUIButton::OnEvent:221
cguienvironment.cpp:irr::gui::CGUIEnvironment::postEventFromUser:544
cirrdevicestub.cpp:irr::CIrrDeviceStub::postEventFromUser:229
cirrdevicewin32.cpp:WndProc:1062
CallWindowProcW
CallWindowProcW
glDebugEntry
CallWindowProcW
CallWindowProcW
DllUnregisterServer
DllUnregisterServer
DllUnregisterServer
DllUnregisterServer
CallWindowProcW
DispatchMessageW
cirrdevicewin32.cpp:irr::CIrrDeviceWin32::handleSystemMessages:2234
```

**Comment by hiker** [comment] 2018-01-02 23:42
Might be related to a translation? If we somehow give bad format data to strftime?
```
    const struct tm *t = gmtime(&tt);
    core::stringw w_date_format = translations->w_gettext(N_("%d/%m/%Y"));
    core::stringc c_date_format(w_date_format.c_str());
    char s[64];
    strftime(s, 64, c_date_format.c_str(), t);
```
Or could be an issue with string length (according to the strftime man page: 'If the length of the result string (including the terminating null byte) would exceed max bytes, then strftime() returns 0,  and  the  contents  of  the array are undefined.'). So result is undefined,  which is then used to create a std::string on return. Though the crash is in strftime, so before that.
Can anyone reproduce this issue? It all works for me :(

**Comment by deveee** [comment] 2018-01-03 20:05
As posted on the forum, the reason is that the string is translated in this way:

msgid "%d/%m/%Y"
msgstr "%д.%м.%Г"

And it's already fixed on transifex.

Maybe we need a string verification and a fallback to "%d/%m/%Y"?

**Comment by auriamg** [comment] 2018-01-03 23:23
If there was an error code returned that would be easy, unfortunately it just segfaults :/ not sure how we can detect an invalid pattern in this case

**Comment by hiker** [comment] 2018-01-04 00:08
A crash is indeed strange. But we can add a unit test for this: cycle through all languages and call the strftime() function (of course we need to remember to run the unit tests when we release after updating translations).

The related question: should we do a new release to fix this? I have said that before ... being able to dynamically download new translations to stk would be great :)  I'll open a ticket for that.

**Comment by deveee** [comment] 2018-01-04 07:45
In this particular case we can check if a string contains only %d, %m or %Y. Other % seem invalid in this case. Or you want to allow such translation?
```
msgid "%d/%m/%Y"
msgstr "%d %b '%y"
```

Btw. also Tatar language has:
```
msgid "%d/%m/%Y"
msgstr "%к/%а/%Е"
```

**Closed** 2018-10-11 02:53 UTC
