### ISSUE TITLE
Can't drift left 

### ISSUE THREAD

**Issue by adnidor** [supertuxkart/stk-code#2359] opened 2015-10-24 22:30 UTC
I can't drive left while pressing the drift key. Pressing the drift key while driving left has no effect.

I tried multiple keyboard configurations and multiple OSes, the problem still persists

**Comment by auriamg** [comment] 2015-10-24 23:39
Have you checked http://supertuxkart.sourceforge.net/FAQ#Some_keyboard_keys_do_not_work_when_pressed_simultaneously ? This is probably a case of limitations on your keyboard. Do you maybe have a gamepad?

**Comment by VOTProductions** [comment] 2015-10-26 13:42
Unable to reproduce on Arch Linux. Holding down V and then holding down left works, as well as holding down left, and then holding down V (skidding).

Tested on a CM Storm Quickfire TK.

**Comment by deveee** [comment] 2015-11-18 09:27
As auria said this is most probably keyboard limitation. I had this problem with some keyboards too, especially on laptops. But with other keyboards or other key bindings it works fine.

I'm marking it as works-for-me.

**Closed by deveee** 2015-11-18 09:27 UTC
