### ISSUE TITLE
Multiplayer Kart Selection Menu - 2 simultaneous inputs > 1 move

### ISSUE THREAD

**Issue by rogue-spectre** [supertuxkart/stk-code#2744] opened 2017-01-18 07:51 UTC
Hi,

  In the Multiplayer kart selection Menu. If the two players make a simultaneous input, only one is taken into account.

**Comment by crazyimp** [comment] 2017-11-25 00:14
Hi, we encountered this too. Some more details:

Simultaneous input in the character selection screen (for multiplayer) block each other.
This makes the selection process somewhat laggy and unresponsive. It's even possible to block the others players input completely by keeping a button or joystick pressed in one direction.

Steps to reproduce:
1. "Master" player with gamepad, second player with keyboard.
2. Master player selects character and accepts.
3. Master player presses "right" (tested with this, guess other will work too) and keeps it pressed.
Effects:
Second player cant select a character, inputs are completely ignored.

Tested with version: c59af9136c0f2317002d700186b69580eb144110
Inputs: normal USB keyboard, xbox controller s (first gen).
OS: gentoo

**Comment by Alayan-stk-2** [comment] 2018-11-24 02:34
Related to #2743

**Comment by Alayan-stk-2** [comment] 2024-08-15 17:26
Since #2743 is not a problem anymore, closing this. The splitscreen kart selection screen handles simultaneous input fine as far as I can tell.

**Closed by Alayan-stk-2** 2024-08-15 17:26 UTC
Labels: T: defect, P3: normal, C: Input, R: can't reproduce anymore

**Comment by Alayan-stk-2** [comment] 2024-08-15 18:57
LLS confirme que cela fonctionne correctement.
