### ISSUE TITLE
Beagle and Beastie have no kart

### ISSUE THREAD

**Issue by math07** [supertuxkart/stk-code#1860] opened 2014-12-30 16:51 UTC
On the board, Arthur and I discussed about having the same issue for a while : Beagle and Beastie have no kart in the kart selection screen and while playing.

1) Do you have this problem too or is it graphic card specific ?
2) There is no problem in 0.8.1, did the 3d models of those karts from svn-assets changed in 0.8.2 ? If they didn't, it might be code related.

![z2](https://cloud.githubusercontent.com/assets/9955284/5580521/c3ad5ea0-9019-11e4-8855-613d8d316d34.png)
![z](https://cloud.githubusercontent.com/assets/9955284/5580525/dfa24bde-9019-11e4-987e-ebacc2c7227c.png)

**Comment by math07** [comment] 2015-01-08 03:20
Okay guys here is some update.
I had a few(not a lot) addons installed before the server changes. Today I uninstalled all of them and the bug was gone in my git version and in the previously installed 0.8.2 beta.  As you can see on the second screenshot, I had evil tux, a tux alternative and the kind of cat karts installed and 1-2 maps. Right now the new addon server is empty(no kart) at all so I can't try to reproduce the bug.

**Comment by hiker** [comment] 2015-01-08 04:16
Confirmed, installing alternative tux from the addons (with stk 0.8.1, since it's not in our new repo) reproduces the bug for me - on both windows with hd3000, and linux with GT220.

**Comment by auriamg** [comment] 2015-01-09 23:59
The issue is that they both have kart.png textures, this would therefore probably be the same issue as #1891

**Comment by Eddie595** [comment] 2015-01-10 17:23
Hello. I am having the same issue with the two karts not displaying the kart model. I also have extra karts, so from what was said, am I to assume that removing these extra-karts should fix this bug? Is that the only workaround at the moment?

**Comment by math07** [comment] 2015-01-10 17:32
Yes at the moment, there is no clean fix but I'm pretty sure one will be found before official release of 0.8.2. If you can't wait until then, remove alternative tux first because this one is known to cause problem and if it doesn't work remove other extra-karts.

**Comment by auriamg** [comment] 2015-01-12 01:17
Commit 81bd79a73662190b6cacf509e0440eb276eb3d2e may have an impact on this, can someone please test again? Beastie looks fine for me

**Comment by auriamg** [comment] 2015-01-12 02:38
Confirmed fixed with c791fd46c13f1147b6cbbb91641aad348c63ca55

**Closed by auriamg** 2015-01-12 02:38 UTC
Labels: C:Graphics, P2: major
