### ISSUE TITLE
Captions with accents broken in 0.9.2 with new TTF font

### ISSUE THREAD

**Issue by mkkot** [supertuxkart/stk-code#2574] opened 2016-07-14 08:44 UTC
Hello,

with new TTF font Polish language diacritics are broken. Probably missing font characters cause that system is taking other font characters to replace them. Please see the screens.

![przechwycenie obrazu ekranu_2016-07-14_10-40-15](https://cloud.githubusercontent.com/assets/10531790/16833480/d3e319bc-49af-11e6-89d2-c0bd2791e52a.png)
![przechwycenie obrazu ekranu_2016-07-14_10-40-32](https://cloud.githubusercontent.com/assets/10531790/16833481/d3e7f6c6-49af-11e6-9908-01cb75630239.png)

**Comment by Benau** [comment] 2016-07-14 09:20
Possibly duplicate of #2540

Can you try to apply https://gist.github.com/Benau/93c9b9cc356c5a9bb1c1 and re-compile?

**Comment by mkkot** [comment] 2016-07-14 09:53
It depends of how badly you want to test it. For me it's not a big flaw, however compilation of this game would take probably few hours.

**Comment by Benau** [comment] 2016-07-14 09:59
Are you using static build from us / from distro repo?

**Comment by mkkot** [comment] 2016-07-14 10:48
I'm using Archlinux provided binary. BTW I guess that you have this path already applied, would it be possible for you simply to switch language to Polish and check if you have the same problem? Or maybe there is some x86_64 binary I could simply replace. I can compile this game but if there is a less effort way, I would go for that.

**Comment by deveee** [comment] 2016-07-14 11:44
If it's on Arch, then I assume that it's not a problem with too old glibc.
They usually have packages in current versions in repos.

Btw our static build is not statically linked with glibc and also doesn't
contain these libraries. It needs glibc, libgcc, xorg as the dependencies
and it uses these libraries from system.

Could you clarify if this is a problem in our official 0.9.2 build, or is
this a problem with this commit:
https://github.com/supertuxkart/stk-code/commit/19acdad9b4784a84e1ae87cd2e2953ebe6df97bc
which replaces the non-free font that we were using? I don't know if they
applied it on Arch or not...

Our official 0.9.2 build works fine for me with Polish language on Ubuntu
16.04.

**Comment by mkkot** [comment] 2016-07-14 12:58
My glibc is 2.23-5. AFAIK there is no patch applied. Arch is known from not applying not needed patches ;)
Here is pkgbuild:
https://git.archlinux.org/svntogit/community.git/tree/trunk?h=packages/supertuxkart

If there were patches, they would be displayed here. And I can see in /usr/share/supertuxkart/data/ttf/:

mk@linux ttf]$ ls
FreeSansBold.ttf            SigmarOne.otf                Ubuntu-R.ttf
FreeSans.ttf                'SIL Open Font License.txt'  wqy-microhei.ttf
LICENSE                     Ubuntu-B.ttf
NotoNaskhArabicUI-Bold.ttf  ubuntu-font-licence-1.0.txt

So I guess this is Ubuntu font. However, I can see no problem with this font when displaying its characters:

![przechwycenie obrazu ekranu_2016-07-14_14-57-36](https://cloud.githubusercontent.com/assets/10531790/16840163/673fc52a-49d3-11e6-818d-90daa019c5cd.png)

Please tell me what else I can check.

**Comment by Benau** [comment] 2016-07-15 01:54
Meanwhile i think of adding lazy loading chars support for title fonts too, which avoid fallback fonts completely

**Closed** 2016-07-20 02:03 UTC
