### ISSUE TITLE
Lowest window mode size 1280x720 is to tall on screen with 1366x768

### ISSUE THREAD

**Issue by scootergrisen** [supertuxkart/stk-code#2591] opened 2016-08-02 14:56 UTC
The window mode option in STK with certain fixed window sizes does not make a whole lot of sense if the lowest window size is 1280x720 and the screen size is 1366x768.
So i cant even see the whole window on the screen.

Would it not be possible to have any window size that the user wished to the window would be changed with the mouse like so many other programs?

If not possible then maybe add small sizes like 640x480 and 800x600 and custom size so the user can type a number.

Also instead of having a button for each resolution, why not just a drop down menu with the all, that way they the buttons don't take up so much room and you could have a lot more sizes.

**Comment by Arthur-D** [comment] 2016-08-02 21:53
I'm not sure what the issue is: you say STK is 1280x720 and your screen is 1366x768?
 1366
-1280
=   86
and
 768
-720
= 48
so that should leave enough room for the whole window plus window decorations and a taskbar.

**Comment by Arthur-D** [comment] 2016-08-02 22:09
Actually on second thought I guess the taskbar or the window decorations would have to go since both of those are often 36 pixels or larger. Maybe set auto-hide on your taskbar?
Anyway we stopped supporting 800x600 officially some years ago because it became difficult to have enough room for everything.

**Comment by MTres19** [comment] 2016-08-03 12:49
1280 × 720 isn't the lowest available resolution. Click the arrows on either side of the list of resolutions to see more. It goes as low as 1024 × 768.

**Comment by deveee** [comment] 2016-08-03 16:32
General rule is width >= 1024 && height >= 768. The 1280x720 is an
exception because 16:9 monitors are quite popular and this is an
altetnative to 1024x768 (lowest officially supported resolution).

You can force to use lower resolution by setting artist debug mode and
manually set for example 640x480 in config.xml, but it may look badly.

W dniu środa, 3 sierpnia 2016 MTres19 <notifications@github.com> napisał(a):
> 1280 × 720 isn't the lowest available resolution. Click the arrows on
either side of the list of resolutions in the options menu to see more. It
goes as low as 1024 × 768.

**Comment by deveee** [comment] 2016-08-03 17:51
Anyway the 1280x720 resolution has a sense on 1366x768 display, because some window managers check how much place is available and create smaller windows, that are fully visible. I'm closing it as invalid.

**Closed by deveee** 2016-08-03 17:51 UTC

**Comment by scootergrisen** [comment] 2016-08-04 12:35
Yeah the task bar and window list and stuff like that take up room so i can't see the whole window even when selecting the lowest possible resolution for the window that STK offers.

> 1280 × 720 isn't the lowest available resolution. Click the arrows on either side of the list of resolutions in the options menu to see more. It goes as low as 1024 × 768.
768 is higher then 720.

Why close as invalid?
Its annoying that i can't test something in STK windowed mode easily and switch window to write something without going in and out of fullscreen.
The "Back" button is in the top left corner and the things like "Options" button are at the bottom so each time i go into options i have to move window up so i can press the options button, then i need to move window down so i can press the back button.

**Comment by deveee** [comment] 2016-08-04 14:37
I closed it as invalid because we have no plans to officially support
resolutions lower than 1024x768.

We can't just disable these resolutions on 1366x768 screen because these
work fine with other window managers/operating systems. Try to run STK with
1366x768 resolution under Gnome. It should just create maximized window and
the whole content should be visible.

I also wrote you what to do if you want to test something with lower
resolution. You need to enable artist debug mode and choose any resolution
you want in config.xml file or from command line.

**Comment by scootergrisen** [comment] 2016-08-04 15:08
The problem what is that is GNOME don't allow me to maximize the window...
I don't have the latest version of STK right now to test but i don't remember ever being able to maximize the "normal" way.

Well... now i see i CAN right click on the window list in GNOME (not there by default), but for some reason maximize is disabled if i right click the window title and also i can't drag the STK window beyond the top of the screen to maximize it like other windows.

Are there some code in STK that inhibits maximizing the window?
If so maybe this restricting could be removed.

I will try the artist debug mode but i would still like this to work normally without the user having to do advanced stuff.

**Comment by deveee** [comment] 2016-08-04 16:22
I meant it's not possible to maximize the window in typical way, but using highest available resolution (in your case 1366x768), you should get maximized window, at least under Gnome.

Make the window fully resizeable is not trivial, but there is already opened a ticket for this feature request.
