### ISSUE TITLE
Crash after exiting a race

### ISSUE THREAD

**Issue by solistice** [supertuxkart/stk-code#1323] opened 2014-05-13 14:27 UTC
Following stacktrace is given when exiting a race (either with the Exit Race or closing the application altogether): http://pastebin.com/GeteBbgV

Easily reproducible by exiting the game in any given way. I have no knowledge wether this only occurs on Mac OS, but it happens every time

**Comment by solistice** [comment] 2015-01-08 11:05
Tried to reproduce and never occurred anymore! Think this is fixed, but since this was not always 100% reproducable, I'm going to leave it open for now

**Comment by hiker** [comment] 2015-02-17 06:01
Appears to be a duplicate of #1938 .

**Closed by hiker** 2015-02-17 06:01 UTC
Labels: R: duplicate
