### ISSUE TITLE
Out-of-place texture in top and bottom of skybox on some maps.

### ISSUE THREAD

**Issue by BlueCatYellowCat** [supertuxkart/stk-code#3735] opened 2019-02-02 12:03 UTC
## Description
On outdoor maps, there is a large strange texture in what I assume is the skybox. This is visible when the player's character is hit up into the air, or drives off the edge of a map to see the floor of the skybox.
[Here is a video](https://my.mixtape.moe/albqmq.webm). Notice when the player is hit, a large dark surface comes onto the screen.
I have seen it on a couple of maps, I recall them being dark or rainy maps. I am guessing this may be a GPU-related issue but I am not sure at all.

## Steps to reproduce
1) Select an affected map ('[Around The Lighthouse](https://my.mixtape.moe/albqmq.webm)' and '[Blackhill Mansion](https://my.mixtape.moe/cjdqfy.jpg)' will work, most visible on darker outdoor maps)
2) Find a way to have the camera look up at the sky. One way is to drive up a sloped surface. Another way is to get hit with a weapon so that the character goes into the air.

## Configuration

STK release version: 0.9.3

STK Source (PPA, distribution package, official binary, etc.):
Official binary

System: 
Windows 7 x64

Graphics card: 
Nvidia GTX 1050

CPU: 
Intel Skylake

Gamepads/keyboards models if related to the issue: 
None

## Additional information
Tested while on highest quality settings.

**Comment by Alayan-stk-2** [comment] 2019-02-02 14:40
Duplicate of #2128

**Closed by Alayan-stk-2** 2019-02-02 14:40 UTC
