### ISSUE TITLE
Shifting Sands: Narrow tunnel has sharp naughty edges

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#2124] opened 2015-04-26 19:38 UTC
In Shifting Sands, the short/narrow part through the pyramid has pretty sharp edges near the point where both in-pyramid paths join. This slows down your kart a lot, as if it were crashing to something.

Very frustrating.

STK version: 0.9

**Comment by hiker** [comment] 2015-04-28 23:39
Duplicate of #2084.

**Closed by hiker** 2015-04-28 23:39 UTC
Labels: R: duplicate
