### ISSUE TITLE
Hitting home button and re-opening from launcher causes black screen on android (GLES2)

### ISSUE THREAD

**Issue by cddepppp256** [supertuxkart/stk-code#3644] opened 2018-12-09 15:19 UTC
STK shows a black screen with "loading", followed by just a black screen after doing steps to reproduce.

teps to reproduce: Open STK, wait for it to load, then click the home button. Re-open from your launcher/homescreen.

STK release version: git

STK Source: git, self compiled debug apk

System: Android

stdout.log
```
[info   ] [FileManager]: Data files will be fetched from: '/storage/emulated/0/Android/data/org.supertuxkart.stk_dbg/files/supertuxkart-dbg/data/'
[info   ] [FileManager]: Data files will be fetched from: '/storage/emulated/0/Android/data/org.supertuxkart.stk_dbg/files/supertuxkart-dbg/data/'
[info   ] [FileManager]: User directory is '/storage/emulated/0/Android/data/org.supertuxkart.stk_dbg/files/supertuxkart-dbg/home/supertuxkart/0.10-git/'.
[info   ] [FileManager]: Addons files will be stored in '/storage/emulated/0/Android/data/org.supertuxkart.stk_dbg/files/supertuxkart-dbg/home/.local/share/supertuxkart/addons/'.
[info   ] [FileManager]: Screenshots will be stored in '/storage/emulated/0/Android/data/org.supertuxkart.stk_dbg/files/supertuxkart-dbg/home/.local/share/supertuxkart/screenshots/'.
[info   ] [FileManager]: User-defined grand prix will be stored in '/storage/emulated/0/Android/data/org.supertuxkart.stk_dbg/files/supertuxkart-dbg/home/.local/share/supertuxkart/grandprix/'.
[info   ] [FileManager]: Asset 0 will be loaded from '/storage/emulated/0/Android/data/org.supertuxkart.stk_dbg/files/supertuxkart-dbg/data/challenges/'.
[info   ] [FileManager]: Asset 1 will be loaded from '/storage/emulated/0/Android/data/org.supertuxkart.stk_dbg/files/supertuxkart-dbg/data/gfx/'.
[info   ] [FileManager]: Asset 2 will be loaded from '/storage/emulated/0/Android/data/org.supertuxkart.stk_dbg/files/supertuxkart-dbg/data/grandprix/'.
[info   ] [FileManager]: Asset 3 will be loaded from '/storage/emulated/0/Android/data/org.supertuxkart.stk_dbg/files/supertuxkart-dbg/data/gui/icons/'.
[info   ] [FileManager]: Asset 4 will be loaded from '/storage/emulated/0/Android/data/org.supertuxkart.stk_dbg/files/supertuxkart-dbg/data/gui/screens/'.
[info   ] [FileManager]: Asset 5 will be loaded from '/storage/emulated/0/Android/data/org.supertuxkart.stk_dbg/files/supertuxkart-dbg/data/gui/dialogs/'.
[info   ] [FileManager]: Asset 6 will be loaded from '/storage/emulated/0/Android/data/org.supertuxkart.stk_dbg/files/supertuxkart-dbg/data/library/'.
[info   ] [FileManager]: Asset 7 will be loaded from '/storage/emulated/0/Android/data/org.supertuxkart.stk_dbg/files/supertuxkart-dbg/data/models/'.
[info   ] [FileManager]: Asset 8 will be loaded from '/storage/emulated/0/Android/data/org.supertuxkart.stk_dbg/files/supertuxkart-dbg/data/music/'.
[info   ] [FileManager]: Asset 9 will be loaded from '/storage/emulated/0/Android/data/org.supertuxkart.stk_dbg/files/supertuxkart-dbg/data/replay/'.
[info   ] [FileManager]: Asset 10 will be loaded from '/storage/emulated/0/Android/data/org.supertuxkart.stk_dbg/files/supertuxkart-dbg/data/tracks/'.
[info   ] [FileManager]: Asset 11 will be loaded from '/storage/emulated/0/Android/data/org.supertuxkart.stk_dbg/files/supertuxkart-dbg/data/sfx/'.
[info   ] [FileManager]: Asset 12 will be loaded from '/storage/emulated/0/Android/data/org.supertuxkart.stk_dbg/files/supertuxkart-dbg/data/shaders/'.
[info   ] [FileManager]: Asset 13 will be loaded from '/storage/emulated/0/Android/data/org.supertuxkart.stk_dbg/files/supertuxkart-dbg/data/skins/'.
[info   ] [FileManager]: Asset 14 will be loaded from '/storage/emulated/0/Android/data/org.supertuxkart.stk_dbg/files/supertuxkart-dbg/data/textures/'.
[info   ] [FileManager]: Asset 15 will be loaded from '/storage/emulated/0/Android/data/org.supertuxkart.stk_dbg/files/supertuxkart-dbg/data/ttf/'.
[info   ] [FileManager]: Asset 16 will be loaded from '/storage/emulated/0/Android/data/org.supertuxkart.stk_dbg/files/supertuxkart-dbg/data/po/'.
[verbose  ] translation: Env var LANGUAGE = 'en_US'.
[verbose  ] translation: Language 'English (United States)'.
[info   ] tinygettext: Adding language fallback en

[info   ] IrrDriver: OpenGL version: 2.1
[info   ] IrrDriver: OpenGL vendor: ARM
[info   ] IrrDriver: OpenGL renderer: Mali-450 MP
[info   ] IrrDriver: OpenGL version string: OpenGL ES 2.0
[warn   ] irr_driver: Using the fixed pipeline (old GPU, or shaders disabled in options)
[info   ] GrandPrixManager: Loading Grand Prix files from /storage/emulated/0/Android/data/org.supertuxkart.stk_dbg/files/supertuxkart-dbg/data/grandprix/
[info   ] GrandPrixManager: Loading Grand Prix files from /storage/emulated/0/Android/data/org.supertuxkart.stk_dbg/files/supertuxkart-dbg/home/.local/share/supertuxkart/grandprix/
[warn   ] OpenGL: OpenGL version is too old!
```
Screenshot:
![screenshot_2018-12-09-09-06-41](https://user-images.githubusercontent.com/44927373/49699157-6ea6f580-fb93-11e8-9ea9-cca8fec23ace.png)

Edit: I belive that you have to make sure android has zipped the process in memory (I know most versions of android do this -- right?), but I am not sure.

**Comment by deveee** [comment] 2018-12-09 17:36
Does it happen with STK 0.9.3 too?

It's possible that opengl context is lost, but it never happened for me and it's not simple to recreate it. And still it seems that whole screen should be black in this case...

To get more verbose log you can connect your phone with USB cable and use:
```adb logcat | grep "SuperTuxKart\|DEBUG\|Irrlicht```
but you need define DEBUG and _DEBUG in Android.mk (or remove #ifdef in COGLES2Driver::testGLError and ContextManagerEGL::swapBuffers)

**Comment by deveee** [comment] 2018-12-09 21:39
Actually does it happen only when you press launcher icon and not if you just go back to the minimized window? If so, maybe it just needs singleTask?
```
diff --git a/android/AndroidManifest.xml b/android/AndroidManifest.xml
index 8b1a11d31..e75fdcc60 100644
--- a/android/AndroidManifest.xml
+++ b/android/AndroidManifest.xml
@@ -17,6 +17,7 @@
 
         <activity android:name="android.app.NativeActivity"
                   android:label="@string/app_name"
+                  android:launchMode="singleTask"
                   android:configChanges="fontScale|keyboard|keyboardHidden|layoutDirection|locale|mcc|mnc|navigation|orientation|screenLayout|screenSize|uiMode"
                   android:screenOrientation="sensorLandscape">
 
```

**Comment by cddepppp256** [comment] 2018-12-10 02:37
I am not 100% certain, and I can't recreate the bug right now. (Not denying that it exists or anything...)
Maybe it's png/jpeg library? The text shows for a while then it goes to a completely black screen... so maybe the png/jpeg library is blacking out these images? (I mean.. It explains why the text shows and why it goes after a while...)

**Comment by cddepppp256** [comment] 2018-12-10 02:39
Does it happen with STK 0.9.3 too? Not that I know.

Actually does it happen only when you press launcher icon and not if you just go back to the minimized window? Not sure there, but I do assume it would do the same thing either way.

**Comment by cddepppp256** [comment] 2018-12-10 02:55
I tried to reproduce on the a new apk with that fix and had no luck getting it to reproduce!
Log (I tried several things, even opening other apps.. that use irrlichit :P):
[https://pastebin.com/ZkB40Md9](https://pastebin.com/ZkB40Md9)

**Comment by deveee** [comment] 2018-12-10 07:59
I see 2 possible cases there:
1. You press home button, then go back to the activity and screen is black. It is possible that opengl context is lost, but it never happened for me, so maybe it was working in this way on some very old phones.
2. You press home button, then you press launcher icon and it tries to launch another STK instance rather than go back to the already running activity (never happened for me too, but it may be possible on some lauchers). And indeed in will cause issues, because stk library is already loaded and we don't properly initialize all global variables, so that it will be in some undefined state.

The https://github.com/supertuxkart/stk-code/commit/7ab4edf8d4310a8284860ea5dae49e4e537f65f0 prevents to launch second STK activity and it should fix the second case (if it was reproducible before and you can't reproduce it now, then it's most likely fixed).

And still the main reason of the second case is https://github.com/supertuxkart/stk-code/issues/3000

**Closed by deveee** 2018-12-10 07:59 UTC
