### ISSUE TITLE
No word wrap in Acheivement dialog

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#3532] opened 2018-10-30 18:05 UTC
See pic:
![pic](http://i.imgur.com/tLOMv2C.png)

Also the OK button is very small and very close to the bottom of the dialog.

@Alayan-stk-2

**Comment by deveee** [comment] 2018-10-30 18:39
+1 for word wrap. And I think that the bug report should be more general. IMO there is no need to duplicate goal description. It's 2x more text to translate and it looks bad especially in complex 3in1 achievements.

... maybe only for complex achievements use description + goal/progress table (instead of double goal/progress tables)? And for simple achievements only description + progress?

**Comment by Alayan-stk-2** [comment] 2018-10-30 18:46
The dialog uses a standard label for the description, the bug is not specific to this dialog

The GUI code for that label : 
`        <label id="description" width="90%" height="12%" align="center"
text_align="center" word_wrap="true" text=""/>`

> ... maybe only for complex achievements use description + goal/progress table (instead of double goal/progress tables)? And for simple achievements only description + progress?

You won't save on translation by not having the goal description for single-goal achievements.

It could be argued that the achievement itself doesn't need to have a too specific description if the goal states things clearly enough.

As for the "double" thing, if you're referring to the fact that you get 2 goal & 2 progress column when there are multiple conditions (like with gold driver), I agree it's rather poor. There are better ways to show nesting level using only 1 goal & 1 progress column, I just haven't come around to do so.

Tbh, as long as I can't add any new achievements because of the online sync "feature" blocking any progress, I probably won't bother with it.

**Comment by qwertychouskie** [comment] 2018-10-30 19:20
I haven't looked specifically into it, but I think adding achievements should work fine as long as they have unique IDs.  Besides, there is already one new achievement.

**Comment by deveee** [comment] 2018-10-30 20:08
Tbh. I don't care about adding new achievements. I care about making existing achievements working correctly.

If word wrap is a known limitation then maybe don't use long text as a description? In 0.9.3 it was looking ok, so for me it's a regression.

And actually it looks that word wrap was working in 0.9.3:
![zrzut ekranu z 2018-10-30 21-02-10](https://user-images.githubusercontent.com/5108558/47747081-c9415d80-dc87-11e8-8232-882ce3671e4b.png)

**Comment by deveee** [comment] 2018-11-03 22:57
The word wrap for description is fixed in https://github.com/supertuxkart/stk-code/commit/6ae89331c0e463d0f703e5ed227f58caae4f255f

But there are still 2 goal columns, so I will keep it opened until this is fixed too.

And @Alayan-stk-2 for the "double" thing I didn't mean double columns. I meant that for example "Collect at least 5 bananas in one race" is equal to "Bananas collected (1 race)". So that the goal column shouldn't be needed at all when the description is written well. But maybe I just have different point of view.

**Comment by Alayan-stk-2** [comment] 2018-11-03 23:41
Ok, it was the setText call which was wrong. makes sense. Good fix.

We probably won't agree on the goal progress table. You seem to want to remove that table, while I think it is quite important to keep it as it's the only way to display multi-goal progress correctly, and it makes no sense to remove it only for 1 goal achievements as the progress column is still needed, and you won't save anything on translation anyway. Having less specific details in the description and offloading them to the goals could be better, I'm not very happy with how the existing descriptions focus on the technicalities.

**Comment by deveee** [comment] 2018-11-11 01:00
It's slightly better now. I assume that achievements depth is always < 3. If you really want that complex achievements, then please fix the GUI first. And in theory overlapped text may still happen for very long descriptions or for low resolutions, but it works in typical cases.

**Closed by deveee** 2018-11-11 01:00 UTC
Labels: C:GUI, P3: normal, T: defect
