### ISSUE TITLE
Add "Volcan Island" track

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#2481] opened 2016-05-03 00:00 UTC
It would be nice to have the "Volcan Island" track as an official track, as it is very high quality, and many people probably do not go into the addons section and try different tracks looking for good ones.

**Comment by auriamg** [comment] 2016-05-03 00:05
This great is really well done, the biggest issue with this track however is that it very narrow - that's great for time trial, but to play against friends or AIs that's pretty frustrating as this causes a lot of kart-kart collisions... We'll need to think about it. @hiker , @samuncle  what do you think?

**Comment by hiker** [comment] 2016-05-03 06:14
Agree with both.  I am contacting the author now after I had a quick chat with samuncle.

**Comment by Ponzino** [comment] 2016-05-03 19:38
Hi. I'm Fabio, the author of the track. Thanks for your interest. I will try to scale it. I hope that the result is good. I'll tell you soon.

**Comment by auriamg** [comment] 2016-05-03 23:29
Hi Ponzino, your track looks very good and I would really like to congratulate you for your great work! Indeed if it could only be just a bit wider. I am slightly worried that scaling everything up may make the track too long (at the moment it takes a sweet 1 minute to play). Let's hope something can be done that's not too hard

Also, I doesn't necessarily need to be wide everywhere, if some segments remained narrow while others were larger that would also be good I think

**Comment by Ponzino** [comment] 2016-05-04 05:22
ok. I have some questions. where it need to expand? where it can be narrow? how much time do I have? Unfortunately, in this period I am very busy, but I want to do it. tonight i will try to scale (+30%). I think that this is first to do and to verify.

**Comment by hiker** [comment] 2016-05-04 06:16
I'll let samuncle fill in more details, but as a start the guidelines recommend a lap time of 1:00 to 1:30 minutes. From my point of view re width: there should be enough space to kind of easily overtake a kart in most of the track (of course more narrow sections as a added challenge are ok). Think of one kart driving in the middle of the road and you want to overtake it.

The other thing (and that's from my point of view, samuncle certainly has more and better recommendations): try to avoid a long row of positive items in a row parallel to the track direction: this way the first kart can collect all items, while there is nothing left for the second kart, which results in a strong advantage for the first kart. Lining them up 'left to right' (orthogonal to track direction) is typically a much better option, since the first kart can only collect one item, leaving items for the other karts.

**Comment by Ponzino** [comment] 2016-05-04 19:15
I have uploaded a new revision of the track. I have only increased the scale at 1,5 (+50%). For me the result is good. In SuperTux mode the lap ends in less than 1:30 minutes. Before than next week i will resolve all other problems (gift item, nitro, some lights, some resize) and i will release another revision. Please test and try it. Thanks for all suggestions!!!! :-)

**Comment by samuncle** [comment] 2016-05-04 19:17
Hi :)

Can you come on irc #supertuxkart on freenode

I would like to discuss with you

I was really impressed by your track

Sam
Supertuxkart lead artist

**Comment by Ponzino** [comment] 2016-05-04 19:52
ok, but tomorrow. now I'm going to sleep. It's okay for the 21:00? Good night at all...

**Comment by samuncle** [comment] 2016-05-04 19:53
It's perfectly fine :)

Kind regards

**Comment by auriamg** [comment] 2016-05-04 23:18
I just tried the new version and it's a lot better, nice work :)
Now this does put the track on the longer side at around 1 minute 30 for 1 lap, that's on the higher limit but still okay

**Comment by auriamg** [comment] 2016-05-06 01:08
Oh i've also noticed you haven't uploaded the sources (blend file) to the addons, that would be very important! It would be a shame to not have the blend

**Comment by Ponzino** [comment] 2016-05-06 05:10
when my work is over, I will add the source file. Yesterday I spoke with samuncle, and I have decided to make other changes to my track. More details and objects by library.

**Comment by Ponzino** [comment] 2016-05-08 10:15
the new revision is postponed than a week. why not make a tutorial on how to use libraries? This can simplify learning. 
i have chose a new OST: https://www.joshwoodward.com/song/AftertheFlames

**Comment by qwertychouskie** [comment] 2016-05-10 23:53
There is an issue with the song: line 7, word 3.  This game should be fully kid friendly.

**Comment by auriamg** [comment] 2016-05-11 01:20
We also generally don't have lyrics on our soundtracks. But that is fairly minor, we can always pick the soundtrack when the track is finished

**Comment by Ponzino** [comment] 2016-05-11 04:17
I use instrumental version

**Comment by Ponzino** [comment] 2016-05-13 17:07
i have released another revision. please try it. it isn't the final version. the next revision (final) will be available in a few days. in the next i will add some object by library.

**Comment by Ponzino** [comment] 2016-05-13 17:11
"Some invalid files were found in the uploaded add-on. These files have been removed from the archive: after_the_flames.music, JoshWoodward-AttS-03-AfterTheFlames-NoVox.ogg"

the ost has not been uploaded. Why this problem?

**Comment by auriamg** [comment] 2016-05-13 23:53
Hmm it seems like our addons website is a bit too aggressive :( will open a ticket with the addons website maintainer

**Comment by leyyin** [comment] 2016-05-14 11:28
@Ponzino sorry for the issue, can you please try now?

**Comment by Ponzino** [comment] 2016-05-14 12:14
@leyyin @auriamg it work! Thanks

**Comment by Ponzino** [comment] 2016-05-14 12:18
is there any tutorial on how to use the library?

**Comment by auriamg** [comment] 2016-05-14 22:13
You are right, our documentation was really lacking when it came to library objects.

I have added a new section to the docs, please let us know if you still have questions : http://supertuxkart.sourceforge.net/Track_Maker%27s_Guide#Using_library_objects

**Comment by Ponzino** [comment] 2016-05-15 11:14
excellent! thanks. :-)

**Comment by Ponzino** [comment] 2016-05-18 16:11
!!!WORK FINISHED!!!!

I have uploaded the definitive version of my track. There is also the .blend file.
Special thanks at all for support and help :-):-)
Please try it and send feedback.


ps: i have used the library "stklib_seaweed_a" and it make this error in the console:

[warn   ] Material: Cannot determine texture full path : <stktex_kelpMain_a.png>
[error  ] material: Cannot find texture 'stktex_kelpMain_a.png'.
[warn   ] Material: Cannot determine texture full path : <stktex_kelpRoot_a.png>
[error  ] material: Cannot find texture 'stktex_kelpRoot_a.png'.
[warn   ] Material: Cannot determine texture full path : <stktex_kelpBlendUp_a.png>
[error  ] material: Cannot find texture 'stktex_kelpBlendUp_a.png'.
[warn   ] Material: Cannot determine texture full path : <stktex_kelpBlendDown_a.png>
[error  ] material: Cannot find texture 'stktex_kelpBlendDown_a.png'.
[warn   ] Material: Cannot determine texture full path : <stktex_kelpLight_a.png>
[error  ] material: Cannot find texture 'stktex_kelpLight_a.png'.

**Comment by auriamg** [comment] 2016-05-18 23:59
Thanks a lot for the nice work, and congratulations! Your track has just been integrated into STK and will be part of next release. Very nice work :)

I am leaving this ticket open because I still need to investigate the warnings

**Comment by auriamg** [comment] 2016-05-19 00:25
I have fixed the warnings on the console, this object needed to be updated and re-exported.

**Comment by samuncle** [comment] 2016-05-23 16:58
I tested the track and while it certainly looks nice, there are massive performance issue. I got "only" 60 FPS while I have a constant 85 FPS with cocoa temple (and visually cocoa temple is one of the most complex track ever made)

(The GPU is a NVIDIA GTX 970)

We should investigate why it's happening, I also recommend to the author to change the old palm trees with newer one in the library.

**Comment by auriamg** [comment] 2016-05-23 21:09
@samuncle  I can't reproduce those results, on my GTX 680 (a less powerful GPU), I have 80 to 105 FPS on volcano, and 60-70 FPS on cocoa temple

**Comment by nado** [comment] 2016-05-23 21:26
Didnt see any performance issue while playing in multi up to 3 players (while cocoa temple makes the game lagging a bit).

**Comment by Ponzino** [comment] 2016-05-24 08:48
@samuncle These are my 2 test (average values):

on hd 5870 (very old gpu)
VI 30 Fps
CT 15 Fps
at 1680x1050

on r9 270
VI 85 Fps
CT 60 Fps
at 1920x1200

I do not understand your results.... :-(

I think it's good to replace the palm trees with the newer ones in the library, but I decided to keep the old because I wouldn't want to change the style of my track. If it isn't a problem i would like to keep the old models. Of course, the decisions are yours, this is just my opinion :-)

**Comment by qwertychouskie** [comment] 2016-05-25 23:06
I think it would be nice to have a zipper at the end of the jump, as all of the next-gen tracks (e.g. Cocoa Temple) do it this way.

**Comment by qwertychouskie** [comment] 2016-05-25 23:11
If you do add a zipper, the landing area should also be made bigger.

**Comment by auriamg** [comment] 2016-05-27 00:23
Now that the track has been integrated, this ticket can be closed. If there are more issues, please open separate tickets

Also important note : the track has now been added to our media repo ( http://supertuxkart.sourceforge.net/Media_Repo ), so if you want to further work on this track, please start from the version in our media repo (we did a few minor tweaks when integrating the track into the game)

**Closed by auriamg** 2016-05-27 00:23 UTC
