### ISSUE TITLE
Game not starting

### ISSUE THREAD

**Issue by ZeroCoolHacker** [supertuxkart/stk-code#3783] opened 2019-03-02 12:19 UTC
## Description
I have compiled the source and when i run the binary it aborts with an error. Last few lines of logs are attached.

## Steps to reproduce
- Compile from source
- Run the binary in bin folder

STK release version: 
latest dev
Downloaded it from github

System: 
intel core i5-2450M

Graphics card: 
[Radeon HD 6400M/7400M Series]
CPU: 
intel core i5-2450M
Gamepads/keyboards models if related to the issue: 

## Additional information
Here is the output i get
[outputlog.txt](https://github.com/supertuxkart/stk-code/files/2922057/outputlog.txt)

**Comment by deveee** [comment] 2019-03-02 20:52
This bug is kinda funny, because it works in this way since first release based on irrlicht and noone had such error.

In theory we don't need ```XInitThreads()```, because we execute xlib calls in single thread. But maybe graphics driver needs it.

SDL2 added XInitThreads in 2012:
https://hg.libsdl.org/SDL/annotate/1f4e69a8e5e6/src/video/x11/SDL_x11video.c
And they say:
> The nVidia driver requires XInitThreads to be called for it to work in multithreaded mode. Sam also
> says that the overhead for this is small enough that it should just be done by default at this point.
> If this causes issues, we can add a hint later to enable / disable this call. 

Also we don't use xcb, so it looks that xlib uses xcb internally (?).

Anyway can you try this patch?
```
diff --git a/lib/irrlicht/source/Irrlicht/CIrrDeviceLinux.cpp b/lib/irrlicht/source/Irrlicht/CIrrDeviceLinux.cpp
index d848b4b37..237debb81 100644
--- a/lib/irrlicht/source/Irrlicht/CIrrDeviceLinux.cpp
+++ b/lib/irrlicht/source/Irrlicht/CIrrDeviceLinux.cpp
@@ -134,6 +134,8 @@ CIrrDeviceLinux::CIrrDeviceLinux(const SIrrlichtCreationParameters& param)
 
 	// create keymap
 	createKeyMap();
+	
+	XInitThreads();
 
 	// create window
 	if (CreationParams.DriverType != video::EDT_NULL)
```

**Comment by curVV** [comment] 2019-03-06 07:30
Myself and a friend both have the exact same problem. We're both using intel gpu.
Adding XInitThreads(); on this line did not work. Same error as above.

**Comment by deveee** [comment] 2019-03-06 07:44
Thanks for testing.

Does the game even start or that error is a first line in console?

**Comment by curVV** [comment] 2019-03-06 07:53
Here's the output:
```
[verbose  ] main: Error messages and other text output will be logged to /home/curvian/.config/supertuxkart/0.10-git/stdout.log.                                                            
[info   ] [FileManager]: Data files will be fetched from: '../../data/'                       
[info   ] [FileManager]: Data files will be fetched from: '../../data/../../stk-assets/'
[info   ] [FileManager]: User directory is '/home/curvian/.config/supertuxkart/0.10-git/'.
[info   ] [FileManager]: Addons files will be stored in '/home/curvian/.local/share/supertuxkart/addons/'.
[info   ] [FileManager]: Screenshots will be stored in '/home/curvian/.local/share/supertuxkart/screenshots/'.
[info   ] [FileManager]: User-defined grand prix will be stored in '/home/curvian/.local/share/supertuxkart/grandprix/'.
[info   ] [FileManager]: Asset 0 will be loaded from '../../data/challenges/'.
[info   ] [FileManager]: Asset 1 will be loaded from '../../data/gfx/'.
[info   ] [FileManager]: Asset 2 will be loaded from '../../data/grandprix/'.
[info   ] [FileManager]: Asset 3 will be loaded from '../../data/gui/icons/'.
[info   ] [FileManager]: Asset 4 will be loaded from '../../data/gui/screens/'.
[info   ] [FileManager]: Asset 5 will be loaded from '../../data/gui/dialogs/'.
[info   ] [FileManager]: Asset 6 will be loaded from '../../data/../../stk-assets/library/'.
[info   ] [FileManager]: Asset 7 will be loaded from '../../data/../../stk-assets/models/'.
[info   ] [FileManager]: Asset 8 will be loaded from '../../data/../../stk-assets/music/'.
[info   ] [FileManager]: Asset 9 will be loaded from '../../data/replay/'.
[info   ] [FileManager]: Asset 10 will be loaded from '../../data/../../stk-assets/tracks/'.
[info   ] [FileManager]: Asset 11 will be loaded from '../../data/../../stk-assets/sfx/'.
[info   ] [FileManager]: Asset 12 will be loaded from '../../data/shaders/'.
[info   ] [FileManager]: Asset 13 will be loaded from '../../data/skins/'.
[info   ] [FileManager]: Asset 14 will be loaded from '../../data/../../stk-assets/textures/'.
[info   ] [FileManager]: Asset 15 will be loaded from '../../data/ttf/'.
[info   ] [FileManager]: Asset 16 will be loaded from '../../data/po/'.
Linux 4.20.12-artix1-1-ARTIX #1 SMP PREEMPT Sun Feb 24 17:56:30 UTC 2019 x86_64
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
supertuxkart: xcb_io.c:263: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
Aborted
```

**Comment by deveee** [comment] 2019-03-06 08:04
So it doesn't like something in CIrrDeviceLinux.cpp. And does STK 0.9.3 work for you?

**Comment by curVV** [comment] 2019-03-06 08:40
0.93 works fine.
The git version works for just about everyone except these two which are both archlinux and intel gpu.

**Comment by deveee** [comment] 2019-03-06 08:49
You can try to revert https://github.com/supertuxkart/stk-code/commit/d0d036c372fe5085e6173cb011456cbe9765add4#diff-0e872e87adcd7fcadef3ddb19da9d92c or just remove the ```XPeekIfEvent(display, &event, &isWindowMapped, (XPointer)&window);``` line. And if not, then no idea atm. Everything else seems unrelated...

**Comment by curVV** [comment] 2019-03-06 09:09
That works, thanks.

**Comment by ZeroCoolHacker** [comment] 2019-03-06 12:31
Thanks @deveee That works!

**Comment by deveee** [comment] 2019-03-06 20:06
Fixed in https://github.com/supertuxkart/stk-code/commit/3c7673ccfc731710b6e15526891d9d897ed2df29

**Closed by deveee** 2019-03-06 20:06 UTC

**Comment by qwertychouskie** [comment] 2019-03-06 20:20
Can you also add the XInitThreads?  From the SDL commit description I wonder if it missing is what causes performance to sometimes be way less than it should be with the Nvidia driver.  The description seems to indicate not calling it prevents the driver from working multi-threaded.  And it shouldn't hurt anything.

**Comment by cddepppp256** [comment] 2019-03-08 23:06
I might be a bit late here, but I can confirm that I had this issue most of the time when starting the game. Note that it's not always, as if I started it 5 or 6 times it would work sometime.
