### ISSUE TITLE
Flames from nitro bottles are still rendered after using swapper

### ISSUE THREAD

**Issue by stkAnon** [supertuxkart/stk-code#1550] opened 2014-09-20 21:36 UTC
![](http://img42.com/lP8vM+)

**Comment by auriamg** [comment] 2015-11-25 00:02
Can you still reprouce this? I am unable to reproduce, it may have been fixed

**Comment by stkAnon** [comment] 2015-12-15 03:57
It seems to be fixed in 0.9.1.

IIRC someone also mentioned fixing it on IRC some months ago.

**Comment by auriamg** [comment] 2015-12-18 01:19
CLosing as fixed, please reopen if it still happens

**Closed by auriamg** 2015-12-18 01:19 UTC
Labels: C:Graphics, P4: minor, R:Waiting for feedback
