### ISSUE TITLE
Clipping 

### ISSUE THREAD

**Issue by testdummy118** [supertuxkart/stk-code#2023] opened 2015-03-06 07:25 UTC
![non_overlaying_texture](https://cloud.githubusercontent.com/assets/11346115/6521553/37e73988-c38e-11e4-8eda-ea8e20446ab5.JPG)
![overlaying_plant](https://cloud.githubusercontent.com/assets/11346115/6521555/37e9ca9a-c38e-11e4-9813-d759adfedda8.PNG)
![shell_example](https://cloud.githubusercontent.com/assets/11346115/6521554/37e841b6-c38e-11e4-9b3d-a2283767714d.JPG)

As you can see in the images, the plant is overlaying in the tubes of the map. The rock however beside it is not.

Character: Elephpant
Map: Subsea
Mode: Story
Version: 0.8.1 / 0.8.2 (not sure)
Resolution: 1280x1024
Graphics: 5
Windowed

I'm not sure if this is something that has been fixed since I found it, but I was just hoping it'd help!

I love the game :) Keep up the good work!

**Comment by auriamg** [comment] 2015-03-07 23:16
Hi, thanks for your interest. This is actually a duplicate of #1448. In addition to this, the subsea track is not really well designed, and a future version of the track would improve on this a lot, hopefully

**Closed by auriamg** 2015-03-07 23:16 UTC
