### ISSUE TITLE
Improve "Installer Microsoft VC++ runtime libraries?" dialog

### ISSUE THREAD

**Issue by scootergrisen** [supertuxkart/stk-code#2545] opened 2016-07-02 13:01 UTC
When i installer STK 0.9.2 on Windows 7 i get dialog with this text:

```
Install Microsoft VC++ runtime libraries?
```

Maybe the dialog should explain to the user what its needed for and how the user would know if it is needed.
And maybe check if already installed and what what is installed and what version is being offered to be installed.
And what will happen if not choosing to install it... and maybe how to install it later if i select not to installer but want to installer later.

**Comment by scootergrisen** [comment] 2016-07-02 13:02
![stk3](https://cloud.githubusercontent.com/assets/1836590/16540460/efe17bf2-4065-11e6-8069-922e16575a70.png)

**Comment by auriamg** [comment] 2016-07-03 00:29
Marking as minor because we wouldn't ask if it wasn't required, and we've never had problems with users failing to install STK in practice. (though I agree that unfortunately some installers try to bundle third-party adwares and stuff like that, so yeah wouldn't hurt to clarify that it's required)

**Comment by scootergrisen** [comment] 2016-07-03 11:29
I think the first time i tried installing STK i did not want to install Microsoft VC++ runtime libraries.
Then i think STK did not work and i wanted to try installing Microsoft VC++ runtime libraries but because i choose No the first time i guess i have to install STK again to get that dialog to install Microsoft VC++ runtime libraries.

Maybe not a problem to install STK again, but maybe some how make it possible for the user to install Microsoft VC++ runtime libraries without having to install STK again.

**Comment by MTres19** [comment] 2016-07-04 00:37
Why not just silently install it without asking, like most installers? I think you're allowed to, since it's the redistributable version. The flags appear to be
`vcredist_x86.exe /install /passive /norestart`
according to [http://asawicki.info/news_1597_installing_visual_c_redistributable_package_from_command_line.html](http://asawicki.info/news_1597_installing_visual_c_redistributable_package_from_command_line.html)

**Comment by scootergrisen** [comment] 2016-08-02 15:49
If installing silenty i would very much like to be informed about it first so i would have the option to avoid automatic installations.
I don't like the idea of software installation other software without informing/asking the user.
But if Microsoft VC++ runtime libraries is needed to run STK then i guess if would be fine to inform the user at the beginning of the installer that Microsoft VC++ runtime libraries if need to run STK and that it will be installed automatic. Maybe a check box or something.

**Comment by qwertychouskie** [comment] 2016-08-02 18:38
Every other Windows installer I have ever seen just installs them automatically.  My opinion is that we should do the same to avoid confusing the user.

**Comment by qwertychouskie** [comment] 2016-10-30 23:11
Obsoleted by #2661 (since the issue is really about Unicode support in the installer), can be closed.

**Comment by Alayan-stk-2** [comment] 2019-04-28 23:20
An user reported on the blog that the game could not run, reporting this error : "Couldn't find MSVCP140.dll"

So it is clear that, in practice, there are users for who this create issues.

**Comment by qwertychouskie** [comment] 2019-04-29 19:24
1.0 wasn't built with MinGW?!?  I'm starting to get seriously upset that STK continues to KNOWINGLY violate the GPL.  As someone who has code being actively violated (https://github.com/supertuxkart/stk-code/search?q=author%3AQwertyChouskie&type=Commits), I'm really unhappy that 1.0 was released without fixing the known license violations, and even more very much really unhappy that https://github.com/supertuxkart/stk-code/issues/3344 was closed because "We are now considering using mingw for the release" even though they clearly didn't!

@Alayan-stk-2 Please re-open https://github.com/supertuxkart/stk-code/issues/3344 as it is still very much a problem.

**Comment by Hi-Angel** [comment] 2019-05-02 00:33
> 1.0 wasn't built with MinGW?!? I'm starting to get seriously upset that STK continues to KNOWINGLY violate the GPL. As someone who has code being actively violated (https://github.com/supertuxkart/stk-code/search?q=author%3AQwertyChouskie&type=Commits), I'm really unhappy that 1.0 was released without fixing the known license violations, and even more very much really unhappy that #3344 was closed because "We are now considering using mingw for the release" even though they clearly didn't!
>
> @Alayan-stk-2 Please re-open #3344 as it is still very much a problem.

FWIW, current Windows build looks overcomplicated to me overall *(but take it with a grain of salt — I don't have experience with building big projects on Windows)*. I thought to try to simplify it by using [Xonotic guide as a template](https://gitlab.com/xonotic/xonotic/wikis/Repository_Access#windows) *(which as a bonus would decouple it from MSVS)*, but as I don't want to spend time in vain, I decided to pull in something simple first. Well, I see other unanswered pulls as well as since [my pull for `ccache` autodetection](https://github.com/supertuxkart/stk-code/pull/3885) got opened, repo has had commits from various contributors. So nobody bothers, I don't know…

**Comment by Hi-Angel** [comment] 2019-05-05 22:39
@Alayan-stk-2 so, are contributions for porting Windows build instructions from MSVC to mingw welcome?

> There are 2 or 3 exceptions where the change of the PR is rather trivial in complexity but also in usefulness.

That sounds okay. You can't expect from newbies that simply want to improve the project they're using something amazing, since that would also be non-trivial *(because, clearly, things both amazing and trivial were already done by someone)*.

And there's also same as me category — people who are used to seeing that projects often has nobody to accept PRs *(even when they seem maintained)*, and hence would send something simple first just to see if there's anyone at all to accept code.

Both categories may contribute something nicer in the future, but won't because there's no one interested in their effort.

Either way, I don't understand that argument: a PR is either useful or not; so you decline it with a comment or you accept it. Sometimes the category of PR is unclear, but it's another story. If you see something trivial in both complexity and usefulness, why not just immediately accept it? It is useful, and it's a button press away on github.

**Comment by Benau** [comment] 2019-12-19 17:37
mingw is now used and no more redistribute is needed!![](https://lihkg.com/assets/faces/pigxm/drum.gif)

**Closed by Benau** 2019-12-19 17:37 UTC
Labels: P3: normal, T: defect
