### ISSUE TITLE
Graphics issue on multiseat setup

### ISSUE THREAD

**Issue by MangyCat** [supertuxkart/stk-code#5007] opened 2024-01-23 13:19 UTC
## Description

So i got a multiseat setup, seat0 is using Intel IGPU, seat1 is nvidia gpu, the issues only seem to be happening on the nvidia gpu while at the intel gpu's seat everything is fine nothing wrong, both gpus have Mesa loaded (Not using propietary driver).
This issue didnt use to happen before on the nvidia gpu when it was just one seat, everything worked fine.

The actual issue happening is the carts being invisible, like only their shadow being visible, like ghost carts. and I cannot even see the powerups other carts are using for example (fly swatters, bubble gum protection)

And the other thing is that the seat1 side is actually very sluggish even though it has a nouveau card and should logically be faster than the intel igpu even on the lowest settings!
## Steps to reproduce

1. Have a multiseat configuration (1 Intel gpu and one nvidia gpu running on nouveau)
2. Have lightdm desktop enviorment and login to enlightenment wayland (It doesnt matter if wayland or xorg, same thing happens on both)
3. Get on supertuxkart
4. Select your ghostly kart?
5. Race with other ghosts of carts 
6. Be disappointed
7. Exit game

## Configuration

STK release version: 1.4

STK Source (PPA, distribution package, official binary, etc.): Distribution package from pacman

System: Arch Linux

Graphics card: GT630 and Intel HD 2000 (Nvidia gf108 variant, running nouveau)

CPU: Intel I5 2400

Gamepads/keyboards models if related to the issue: 

## Additional information
I attempted to reset supertuxkart configuration by deleting the supertuxkart folder in .config and the supertuxkart folder in .local/share, it didnt work and resulted in the same bug. Also sometimes the issue disappears but its a hit or miss its like rolling a dice. Even when playing other games i encounter this pattern of the nvidia gpu being slow while the Intel gpu is fast for example minecraft.

stdout.log: (SEAT1's side (the one with issues))
```
[info   ] UserConfig: Could not read user config file '/home/etore/.config/supertuxkart/config-0.10/config.xml'.  A new file will be created.
[info   ] [FileManager]: Data files will be fetched from: '/usr/share/supertuxkart/data/'
[info   ] [FileManager]: User directory is '/home/etore/.config/supertuxkart/config-0.10/'.
[info   ] [FileManager]: Addons files will be stored in '/home/etore/.local/share/supertuxkart/addons/'.
[info   ] [FileManager]: Screenshots will be stored in '/home/etore/.local/share/supertuxkart/screenshots/'.
[info   ] [FileManager]: User-defined grand prix will be stored in '/home/etore/.local/share/supertuxkart/grandprix/'.
[info   ] [FileManager]: Asset 0 will be loaded from '/usr/share/supertuxkart/data/challenges/'.
[info   ] [FileManager]: Asset 1 will be loaded from '/usr/share/supertuxkart/data/gfx/'.
[info   ] [FileManager]: Asset 2 will be loaded from '/usr/share/supertuxkart/data/grandprix/'.
[info   ] [FileManager]: Asset 3 will be loaded from '/usr/share/supertuxkart/data/gui/icons/'.
[info   ] [FileManager]: Asset 4 will be loaded from '/usr/share/supertuxkart/data/gui/screens/'.
[info   ] [FileManager]: Asset 5 will be loaded from '/usr/share/supertuxkart/data/gui/dialogs/'.
[info   ] [FileManager]: Asset 6 will be loaded from '/usr/share/supertuxkart/data/replay/'.
[info   ] [FileManager]: Asset 7 will be loaded from '/usr/share/supertuxkart/data/shaders/'.
[info   ] [FileManager]: Asset 8 will be loaded from '/usr/share/supertuxkart/data/skins/'.
[info   ] [FileManager]: Asset 9 will be loaded from '/usr/share/supertuxkart/data/ttf/'.
[info   ] [FileManager]: Asset 10 will be loaded from '/usr/share/supertuxkart/data/po/'.
[info   ] [FileManager]: Asset 11 will be loaded from '/usr/share/supertuxkart/data/library/'.
[info   ] [FileManager]: Asset 12 will be loaded from '/usr/share/supertuxkart/data/models/'.
[info   ] [FileManager]: Asset 13 will be loaded from '/usr/share/supertuxkart/data/music/'.
[info   ] [FileManager]: Asset 14 will be loaded from '/usr/share/supertuxkart/data/sfx/'.
[info   ] [FileManager]: Asset 15 will be loaded from '/usr/share/supertuxkart/data/textures/'.
[info   ] [FileManager]: Asset 16 will be loaded from '/usr/share/supertuxkart/data/tracks/'.
[verbose  ] translation: Env var LANGUAGE = 'en_US.UTF-8'.
[verbose  ] translation: Language 'English (United States)'.
[info   ] ServerConfig: Could not read server config file '/home/etore/.config/supertuxkart/config-0.10/server_config.xml'. A new file will be created.
[info   ] [IrrDriver Logger]: ..:: Antarctica Rendering Engine 2.0 ::..
[info   ] [IrrDriver Logger]: SDL Version 2.26.2
[info   ] [IrrDriver Logger]: Using renderer: OpenGL 4.3
[info   ] [IrrDriver Logger]: NVC1: Mesa
[info   ] [IrrDriver Logger]: OpenGL driver version is 1.2 or better.
[info   ] [IrrDriver Logger]: GLSL version: 4.3
[info   ] IrrDriver: OpenGL version: 4.3
[info   ] IrrDriver: OpenGL vendor: Mesa
[info   ] IrrDriver: OpenGL renderer: NVC1
[info   ] IrrDriver: OpenGL version string: 4.3 (Core Profile) Mesa 23.3.3-arch1.1
[info   ] GLDriver: ARB Buffer Storage Present
[info   ] GLDriver: ARB Compute Shader Present
[info   ] GLDriver: ARB Arrays of Arrays Present
[info   ] GLDriver: ARB Texture Storage Present
[info   ] GLDriver: ARB Texture View Present
[info   ] GLDriver: ARB Image Load Store Present
[info   ] GLDriver: ARB Shader Atomic Counters Present
[info   ] GLDriver: ARB Shader Storage Buffer Object Present
[info   ] GLDriver: EXT Texture Compression S3TC Present
[info   ] GLDriver: ARB Uniform Buffer Object Present
[info   ] GLDriver: ARB Explicit Attrib Location Present
[info   ] GLDriver: EXT Texture Filter Anisotropic Present
[info   ] GLDriver: Geometry Shaders Present
[info   ] GLDriver: ARB Texture Buffer Object Present
[info   ] GLDriver: ARB Texture Swizzle Present
[info   ] GLDriver: ARB Pixel Buffer Object Present
[info   ] GLDriver: ARB Sampler Objects Present
[info   ] GLDriver: ARB Vertex Type 2_10_10_10_rev Present
[info   ] GLDriver: ARB Instanced Arrays Present
[info   ] SharedGPUObjects: Hardware Skinning enabled, method: TBO, max bones: 1024
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/screenquad.vert
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/motion_blur.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/lightning.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/primitive2dlist.vert
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/transparent.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/texturedquad.vert
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/uniformcolortexturedquad.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/texturedquad.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/coloredquad.vert
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/coloredquad.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/colortexturedquad.vert
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/colortexturedquad.frag
[info   ] irr_driver: GLSL supported.
[info   ] GUI: Loading skin data from file: /usr/share/supertuxkart/data/skins/peach/stkskin.xml
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_pass.vert
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_solid.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_shadow.vert
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/white.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_skinning.vert
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_skinning_shadow.vert
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_normal_map.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_alpha_test.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_shadow_alpha_test.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_decal.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_grass_pass.vert
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_grass.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_grass_shadow.vert
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_unlit.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_transparent.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_ghost.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_dynamic_night_bloom.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_tilling_mitigation.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_vertical_mapping.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_road_blending.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_displace.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/colorize.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_normal_visualizer.vert
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_normal_visualizer.geom
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_normal_visualizer.frag
[info   ] player_manager: A new players.xml file will be created.
[info   ] Highscore Manager: New highscore file '/home/etore/.config/supertuxkart/config-0.10/highscore.xml' created.

[info   ] GrandPrixManager: Loading Grand Prix files from /usr/share/supertuxkart/data/grandprix/
[info   ] GrandPrixManager: Loading Grand Prix files from /home/etore/.local/share/supertuxkart/grandprix/
[warn   ] SPMeshBuffer: kartDirt shader is missing, fallback to solid
[warn   ] SPMeshBuffer: kartDirt shader is missing, fallback to solid
[warn   ] SPMeshBuffer: kartDirt shader is missing, fallback to solid
[warn   ] SPMeshBuffer: kartDirt shader is missing, fallback to solid
[warn   ] SPMeshBuffer: kartDirt shader is missing, fallback to solid
[warn   ] LayoutManager: Statically sized widgets took all the place!!
[info   ] HTTPRequest: Downloading https://online.supertuxkart.net/dl/xml/online_news.xml
[info   ] addons: Downloading updated addons.xml.
[info   ] HTTPRequest: Downloading https://online.supertuxkart.net/dl/xml/online_assets.xml
[warn   ] LayoutManager: Statically sized widgets took all the place!!
[verbose  ] RaceManager: Nb of karts=1, ghost karts:0 ai:0 players:1

[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/simple_particle.vert
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/simple_particle.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/alphatest_particle.vert
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/alphatest_particle.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/degraded_ibl.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sunlight.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/pointlight.vert
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/pointlight.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/combine_diffuse_color.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/tonemap.frag
[info   ] [FileManager]: Creating directory(ies) '/home/etore/.cache/supertuxkart/cached-textures/hd/tracks/tutorial'
[info   ] FileManager: Creating directory '/home/etore/.cache/supertuxkart/cached-textures/hd/tracks/tutorial/'.
[info   ] Track: Overall scene complexity estimated at 73
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/importance_sampling_specular.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sky.vert
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sky.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/passthrough.frag
[info   ] Script: onStart(): start Driving Tutorial
[info   ] Script: tutorial_bananas(Kart 0): Triggered
[info   ] Script: tutorial_giftboxes(Kart 0): Triggered
[info   ] Script: tutorial_backgiftboxes(Kart 0): Triggered
[info   ] Script: tutorial_discard(Kart 0): Discarded a Message
[info   ] Script: tutorial_nitro_collect(Kart 0): Triggered
[info   ] Script: tutorial_discard(Kart 0): Discarded a Message
[info   ] Script: tutorial_nitro_use(Kart 0): Triggered
[info   ] Script: tutorial_discard(Kart 0): Discarded a Message
[info   ] Script: tutorial_rescue(Kart 0): Triggered
[info   ] Script: tutorial_discard(Kart 0): Discarded a Message
[info   ] Script: tutorial_skidding(Kart 0): Triggered
[info   ] Script: tutorial_skidding2(Kart 0): Triggered
[info   ] Script: tutorial_discard(Kart 0): Discarded a Message
[info   ] Singleton: Destroyed singleton.
[info   ] Singleton: Destroyed singleton.
[warn   ] LayoutManager: Statically sized widgets took all the place!!
[warn   ] LayoutManager: Statically sized widgets took all the place!!

```

input.xml:
```xml

```

Error message:
```
```
![shot-2024-01-23_14-10-24](https://github.com/supertuxkart/stk-code/assets/73955445/f74696d4-2025-4f7b-a8d8-8cf2aa42533e)

**Comment by Anatoliy6463** [comment] 2024-01-23 14:10
Oh, that's not good, it needs to be fixed in 1.5

**Comment by Benau** [comment] 2024-01-23 17:22
try add   <card vendor="Mesa"          os="linux"     disable="TextureBufferObject"/> to the graphics_restrictions.xml

**Comment by Darin755** [comment] 2024-03-08 20:18
I'm not a SuperTuxKart developer but perhaps you could try installing the proprietary Nvidia driver? It sounds like a low level issue and not a bug with the game.

**Comment by qwertychouskie** [comment] 2024-03-09 00:12
The Nouveau Gallium3D driver is known to have a number of significant correctness, stability, and performance issues, and is in the process of being deprecated.  Unfortunately, your card appears to be Fermi-based, which means it will likely not get NVK support.  If the new "NAK" shader compiler ever gets back-ported to the Nouveau Gallium3D driver, it should theoretically fix most issues, but the Mesa developers currently do not have any plans to do so.  Please consider testing with the proprietary Nvidia driver, as it will almost certainly give the best possible experience for your particular hardware.

**Comment by Alayan-stk-2** [comment] 2024-04-29 09:45
The needed fixes would have to happen on the driver's end, not on ours. Your best chance is, as suggested by previous posters, to not use the Nouveau drivers. They work too poorly for 3D gaming.

You can use the config setting suggested by Benau to try to fix the issue on your end, but we cannot apply it to the project at large without downgrading graphics for compliant card-driver combos, or investing excessive time in trying to figure out which combos work and which don't.

**Closed by Alayan-stk-2** 2024-04-29 09:45 UTC
Labels: C:Graphics, R:not our bug
