### ISSUE TITLE
If multiple AIs have the same kart, give custom colors to additional karts

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#5233] opened 2024-12-28 23:11 UTC
With groups such as addons or favorites, there may easily be less distinct karts than available karts in a group. This is also true when using the command line to specify a custom list of karts that's going to race (although that's used mostly in no-graphics mode).

The first instance of each kart should use the kart's default colors, but the 2nd instance of the kart should use a different color, the 3rd instance if there is one another, etc. (although it should rarely be more than a 2nd instance).

**Comment by CodingJellyfish** [comment] 2024-12-30 06:47
Duplicate of #3576

**Closed by CodingJellyfish** 2024-12-30 06:47 UTC
Labels: T: enhancement, P4: minor, C: Race Events

**Comment by Alayan-stk-2** [comment] 2024-12-30 18:04
Renamed the other issue to be clearer.
