### ISSUE TITLE
Ubuntu Touch support

### ISSUE THREAD

**Issue by symbuzzer** [supertuxkart/stk-code#5058] opened 2024-04-21 09:22 UTC
Hi sir, thanks for this great game. Can you port it to Ubuntu Touch please?

**Comment by CodingJellyfish** [comment] 2024-04-21 11:29
Hi sir, thanks for this great feedback. Can you port it to Ubuntu Touch please?

**Comment by symbuzzer** [comment] 2024-04-21 11:46
If I can, I didnt ask

**Comment by deveee** [comment] 2024-04-21 12:36
I think that you should be able to just use the package for arm?

**Comment by symbuzzer** [comment] 2024-04-21 12:46
> I think that you should be able to just use the package for arm?

Yes, arm64

**Comment by Alayan-stk-2** [comment] 2024-04-24 15:23
Duplicate of #4485

@deveee If the arm64 package works, should #4485 also be closed ?

**Closed by Alayan-stk-2** 2024-04-24 15:23 UTC

**Comment by deveee** [comment] 2024-04-24 17:56
I don't have device to test. We have official arm build and it should detect touch screen. I remember that someone was running STK on Librem phone and it was using wayland for window creation and events. AFAIK mir is a wayland compositor, assuming that Ubuntu Touch uses mir.

@symbuzzer Can you try to run the arm package?
https://github.com/supertuxkart/stk-code/releases/download/1.4/SuperTuxKart-1.4-linux-arm64.tar.xz

Or maybe it's possible to run Ubuntu Touch on emulator, I will look at this.

**Comment by symbuzzer** [comment] 2024-04-24 18:02
> I don't have device to test. We have official arm build and it should detect touch screen. I remember that someone was running STK on Librem phone and it was using wayland for window creation and events. AFAIK mir is a wayland compositor, assuming that Ubuntu Touch uses mir.
> 
> @symbuzzer Can you try to run the arm package? https://github.com/supertuxkart/stk-code/releases/download/1.4/SuperTuxKart-1.4-linux-arm64.tar.xz
> 
> Or maybe it's possible to run Ubuntu Touch on emulator, I will look at this.

I want to try sir. But I dont know how to install. Ubuntu Touch can install click files only

**Comment by deveee** [comment] 2024-04-24 18:07
Looks like I need Clickable to build package. I wouldn't support it officially though... Or maybe someone else wants.

Maybe I will build package for you if I have too much free time.

**Comment by symbuzzer** [comment] 2024-04-24 18:28
UBports community is growing very fast. New devices added regularly. I thing porting it is a good idea. Thanks for your effort
