### ISSUE TITLE
I can't configure controllers

### ISSUE THREAD

**Issue by Danfun64** [supertuxkart/stk-code#2557] opened 2016-07-04 19:27 UTC
This issue was already mentioned by @Daimanu06 in #2240, but I feel like I should point out that this is also a general issue, as I have experienced the same issue with both a Logitech f310 (xinput mode) and a Wii classic controller pro. 

I'm using Xubuntu 16.04 64-bit, and am currently using the official 0.9.2 binary....

edit: I get the same exact issue when using STK on Windows 10.

**Comment by auriamg** [comment] 2016-07-04 23:19
Is there a developer who can reproduce this issue and investigate?

**Comment by LoadingPleaseWait** [comment] 2016-07-05 03:46
I've attempted to reproduce the issue on Ubuntu 16.04 with an Xbox 360 controller but I haven't been able to find any bugs with reconfiguring my input devices. I tried with the 0.9.2 branch and the official release binary. Are you only having issues with those two controllers?

**Comment by Danfun64** [comment] 2016-07-05 04:54
IDK. Sorry. I don't have any other controllers to test atm.

**Comment by LoadingPleaseWait** [comment] 2016-07-06 19:34
I'll try to borrow a Wii controller from a friend. Are you able to play other games using those controllers?

**Comment by MTres19** [comment] 2016-07-06 20:06
I've never had this problem with an old Gravis Destroy Tiltpad—I believe Windows shows it as a generic "HID-Compliant Gamepad". But this seems to be about more advanced controllers, and I haven't tried to reconfigure it recently anyway.

**Comment by Danfun64** [comment] 2016-07-06 23:04
I tested other games with both controllers and in both cases they worked correctly.

**Comment by LoadingPleaseWait** [comment] 2016-08-05 23:17
My friend was unable to connect his wiimote to his computer so I would go with what others are saying.

**Comment by Danfun64** [comment] 2016-10-30 00:43
For the record, I can bind controls in 0.8.1-updates. Must have been a change that happened after 0.8.1 that broke things...

**Comment by Danfun64** [comment] 2016-10-30 03:09
Something I found out today. I have less problems configuring the controllers when only one is connected at a time. Maybe it has to do with them being two different types of controllers?

**Comment by qwertychouskie** [comment] 2017-09-16 20:40
@Danfun64 A lot of gamepad issues were recently fixed, can you test the Git version to see if your issue is fixed?

**Comment by auriamg** [comment] 2017-09-16 23:55
...or just wait for next version which should come soonish

**Comment by qwertychouskie** [comment] 2018-11-26 18:06
@Danfun64 Could you test this with 0.9.3 and see if it's still an issue?

**Comment by Danfun64** [comment] 2018-11-28 22:21
I haven't played STK in a while. I'll try to get things set up again within a week.

**Comment by Danfun64** [comment] 2018-12-31 05:06
Sorry for taking so long. I can only change the controls properly if I select using the gamepad. If I try to either use the enter key or click on the control I want to be changed, it immediately accepts whatever "input" had been received.

**Comment by Danfun64** [comment] 2018-12-31 05:39
I tested with 17b83ac321e620b0bb36fa8990da945fe5dde1a1

**Comment by Benau** [comment] 2020-04-28 18:21
For linux can you try compile latest git?
For windows can you try https://sourceforge.net/projects/supertuxkart/files/SuperTuxKart/git20200427/SuperTuxKart-git20200427-win.zip/download

**Comment by Alayan-stk-2** [comment] 2020-08-10 14:25
Please open a new ticket if the issue persists in STK 1.2 In the meantime, I'll close this as not applicable anymore as we now rely on SDL2 for gamepad handling.

**Closed by Alayan-stk-2** 2020-08-10 14:25 UTC
Labels: C: Input, P3: normal, T: defect
