### ISSUE TITLE
Kart "skips" in the air

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#3398] opened 2018-08-25 19:45 UTC
https://www.youtube.com/watch?v=fJZW_KeEI6k
Video shows it all.

This is the root cause of https://github.com/supertuxkart/stk-code/issues/3353 and https://github.com/supertuxkart/stk-code/issues/3397.

**Comment by hiker** [comment] 2018-08-28 00:59
I won't work on that for a few months likely, so no reason to assign it to me.

**Comment by Alayan-stk-2** [comment] 2018-09-18 12:04
In addition to the bridge path in Shifting Sands which is broken, this issue affects several key parts of the Black Forest track, which is expected to be included in the next release if all goes well ; and it may be happen in other tracks (I can do it in the overworld from the mountain).

**Comment by Arthur-D** [comment] 2018-09-18 15:15
Video of it happening in Green Valley, 5 times in 3 laps: https://youtu.be/ITDRqGHvpp0?t=49s

**Comment by Alayan-stk-2** [comment] 2018-09-18 18:17
I've changed a few things in my branch : 
- I use height data to know if it makes sense to cushion. Using only vertical speed and not height to decide to cushion or not is the root cause of the "skips in the air" issue.
- I use the height data from a few frames earlier to get a rough idea of the slope and adjust the impulse strength
- I forbid any cushioning if the kart has not left ground (this entirely suppress the "cushioning makes the kart leave the ground" issue observed on several track, like in the above Green Valley video).

There is one thing which is inferior to 0.9.3 : 
- While big jump are always cushioned correctly, small jumps may not be. As small jump means small vertical speed, the kart don't really lose speed or change angle, the only real downside is the crash sound. I suspect this issue is caused by an overly aggressive "don't cushion if on the ground" setting.

**Closed** 2018-09-18 19:16 UTC
Labels: C: Physics, P2: major, R: fixed, T: confirmed defect
