### ISSUE TITLE
Sound sometimes fails on Mac OS 11.1

### ISSUE THREAD

**Issue by iMacker2020** [supertuxkart/stk-code#4753] opened 2022-03-25 00:43 UTC
## Description

While playing the single player normal race the sound will sometimes end. I noticed this problem twice in the "Nessie Pond" game. 

## Steps to reproduce
Select single player.
Select Hexley.
Select Expert.
Select Normal Race.
Select Nessie's Pond.
Select Start Race.

## Configuration

STK release version: 1.3

STK Source (PPA, distribution package, official binary, etc.): Official binary version 1.3

System: M1 MacBook Air

Graphics card: M1 graphics.

CPU: M1

Gamepads/keyboards models if related to the issue: Logitech Gamepad F310.

## Additional information

stdout.log: No log was found.
```

```

input.xml:
```xml

```

Error message:
```

```

**Comment by Benau** [comment] 2022-03-25 00:45
Try [stk 1.3](https://github.com/supertuxkart/stk-code/releases/tag/1.3)?

**Comment by iMacker2020** [comment] 2022-03-25 00:47
I am using version 1.3.

**Comment by iMacker2020** [comment] 2022-03-25 00:54
I corrected the STK mistake in the Configuration info above. It is version 1.3.

**Comment by Benau** [comment] 2022-03-25 00:57
this issue is difficult to be fixed.....

**Comment by iMacker2020** [comment] 2022-03-27 01:55
It happened so many times to me today. I looked thru the Console to see if there was anything that could help. This is what I saw:

Mar 26 21:39:18 M1-MacBook-Air supertuxkart[3249]: getattrlist failed for /System/Library/Frameworks/OpenGL.framework/Resources//GLRendererFloat.bundle/GLRendererFloat: #2: No such file or directory

Mar 26 21:43:56 M1-MacBook-Air com.apple.xpc.launchd[1] (com.apple.mdworker.shared.08000000-0500-0000-0000-000000000000[3264]): Service exited due to SIGKILL | sent by mds[124]

Mar 26 21:45:37 M1-MacBook-Air com.apple.xpc.launchd[1]: Coalition Cache Hit: app<application.net.sourceforge.supertuxkart.44637771.44637776(501)> [2444]

Not sure if any of this helps.

**Comment by Benau** [comment] 2022-05-03 02:44
There are some threading improvements in latest git so https://github.com/supertuxkart/stk-code/releases/download/preview/SuperTuxKart-git20220503-mac.zip may work for you...

**Comment by LinuxDonald** [comment] 2023-02-17 16:47
I tested lastest night build on Macbook M1 Max and the problem ist gone. Had the same problem with last official release.

**Comment by Alayan-stk-2** [comment] 2024-05-12 15:38
> I tested lastest night build on Macbook M1 Max and the problem ist gone. Had the same problem with last official release.

Closing as fixed based on this comment

**Closed by Alayan-stk-2** 2024-05-12 15:38 UTC
Labels: T: defect, P4: minor, R: fixed, C:Audio
