### ISSUE TITLE
Missing ground in STK Enterprise

### ISSUE THREAD

**Issue by Mensious** [supertuxkart/stk-code#3610] opened 2018-11-22 19:11 UTC
## Description
My video: https://streamable.com/qjjhf

## Steps to reproduce
1. Start the STK Enterprise
2. Go and fall in the black hole

## Configuration
STK release version: Git (network), d73e0d9
Latests Assets
System: Gentoo

**Comment by Alayan-stk-2** [comment] 2018-11-22 21:06
The issue doesn't seem to be a missing texture, the issue is there is no ground at all in that spot to apply a texture on.

**Comment by Mensious** [comment] 2018-11-23 06:08
Ok sorry.

**Comment by Mensious** [comment] 2018-11-23 11:00
Sorry i can't change the Title

**Comment by Mensious** [comment] 2018-11-23 13:02
Ok i changed the Title

**Comment by theTomasPat** [comment] 2019-01-16 15:02
I would like to work on this issue if no one else has claimed it yet.

**Comment by theTomasPat** [comment] 2019-01-16 21:35
[spaceship_fix3610.zip](https://github.com/supertuxkart/stk-code/files/2766143/spaceship_fix3610.zip)

Here's a zip with only the blend file in it.

**Comment by auriamg** [comment] 2019-01-17 01:19
I have committed the fix, thanks

**Closed by auriamg** 2019-01-17 01:19 UTC
Labels: C: 3D Modelling, P5: very minor, T: defect
