### ISSUE TITLE
All particles disabled on low graphical settings

### ISSUE THREAD

**Issue by hiker** [supertuxkart/stk-code#3211] opened 2018-04-20 00:36 UTC
Certain particles need to work even when particle effects are disabled - at least the skidding effect, and likely nitro as well. That used to work in the past (afaik).

**Comment by deveee** [comment] 2018-04-20 07:08
Important particles are enabled even on graphics level "1". You have to manually disable it in advanced settings. At least it was intended to work in this way. 

I added a possibility to totally disable particles, because:
- particles were causing a crash on some (radeon?) devices
- I had quite big slowdown on my devices caused by GPU particles and transform feedback shader

But indeed now probably it doesn't matter, because we compute particles on CPU.

**Comment by Arthur-D** [comment] 2018-04-20 08:01
Also, while there may be no particles in some situations there's still the light, a bit harder to see maybe but it's noticeable.

**Comment by Alayan-stk-2** [comment] 2018-04-20 10:07
No, the light is definitely not enough. If it was there, I didn't notice it.

Having no visual feedback for skidding/nitro feels like being half-blind.

**Comment by deveee** [comment] 2018-04-27 11:10
Fixed in current git. Indeed something was changed since STK 0.9.3 and low graphics levels were disabling particles. Now STK GUI allows to set only "important only" and "all" and I think that disable all particles is not needed anymore.

**Closed by deveee** 2018-04-27 11:10 UTC
Labels: C: Other C++ code in STK, P2: major
