### ISSUE TITLE
Performance decrease in splitscreen multiplayer

### ISSUE THREAD

**Issue by superspacehero** [supertuxkart/stk-code#2383] opened 2015-11-24 03:42 UTC
My graphics card (an EVGA GTX GeForce 970) is capable of playing the SuperTuxKart at the highest graphical settings with no issues whatsoever. However, when playing with four players, the framerate drops considerably lower.

I'm aware that the reason for this is because of it having to render not one, but four screens all at once, and playing with the settings lowered to 3 worked just fine, and is perfectly fine with me, but I'm sure there some people who play who might not know so easily what to do.

The only thing I can think of that may fix this is having an option for a different quality when playing splitscreen multiplayer. However, this would most likely require loading the assets of the game again each time one raced.

I'm not pressuring this to be a high priority, but just something to consider.

**Comment by Benau** [comment] 2015-11-24 04:20
duplicate of #2304

**Comment by superspacehero** [comment] 2015-11-24 13:11
Sorry about that.

**Comment by deveee** [comment] 2016-08-18 08:51
I'm closing as duplicate

**Closed by deveee** 2016-08-18 08:51 UTC
