### ISSUE TITLE
network hangs

### ISSUE THREAD

**Issue by Benau** [supertuxkart/stk-code#3504] opened 2018-10-12 02:55 UTC
And here's the details about mansion map hang:
to reproduce, start a lan server with yourself connecting to it first, than open another no-graphics stk instance with
--connect-now=127.0.0.1:server port --network-ai=7 --no-graphics

than start 20 laps race with backhill mansion track, after a while on somewhere in the track fps drops significantly, and gdb cltrl-c shows:

#0  0x00000000011ee6d8 in btPolyhedralContactClipping::clipFaceAgainstHull (separatingNormal=..., hullA=..., transA=..., worldVertsB1=..., minDist=-0.0618214495, maxDist=0.0228552222, resultOut=...)                 
   at ../lib/bullet/src/BulletCollision/NarrowPhaseCollision/btPolyhedralContactClipping.cpp:319                                                                                                                      
#1  0x00000000011e37ec in btConvexConvexAlgorithm::processCollision (this=0x211f9b8, body0=0x2294a10, body1=0x22e39f0, dispatchInfo=..., resultOut=0x7fffffffd4a0)                                                     
   at ../lib/bullet/src/BulletCollision/CollisionDispatch/btConvexConvexAlgorithm.cpp:527                                                                                                                             
#2  0x00000000011e1990 in btConvexTriangleCallback::processTriangle (this=0x211f430, triangle=0x7fffffffcd88, partId=0, triangleIndex=65175)                                                                           
   at ../lib/bullet/src/BulletCollision/CollisionDispatch/btConvexConcaveCollisionAlgorithm.cpp:125                                                                                                                   
#3  0x00000000011b7518 in btBvhTriangleMeshShape::MyNodeOverlapCallback::processNode (this=0x7fffffffcd70, nodeSubPart=0, nodeTriangleIndex=65175)                                                                     
   at ../lib/bullet/src/BulletCollision/CollisionShapes/btBvhTriangleMeshShape.cpp:315                                                                                                                                
#4  0x00000000011d5f8a in btQuantizedBvh::walkStacklessTree (this=0x1ee5760, nodeCallback=0x7fffffffcd70, aabbMin=..., aabbMax=...) at ../lib/bullet/src/BulletCollision/BroadphaseCollision/btQuantizedBvh.cpp:376    
#5  0x00000000011d5ece in btQuantizedBvh::reportAabbOverlappingNodex (this=0x1ee5760, nodeCallback=0x7fffffffcd70, aabbMin=..., aabbMax=...)                                                                           
   at ../lib/bullet/src/BulletCollision/BroadphaseCollision/btQuantizedBvh.cpp:345                                                                                                                                    
#6  0x00000000011b759b in btBvhTriangleMeshShape::processAllTriangles (this=0x21fcb10, callback=0x211f430, aabbMin=..., aabbMax=...)                                                                                   
   at ../lib/bullet/src/BulletCollision/CollisionShapes/btBvhTriangleMeshShape.cpp:323                                                                                                                                
#7  0x00000000011e1d2a in btConvexConcaveCollisionAlgorithm::processCollision (this=0x211f418, body0=0x2294a10, body1=0x22e39f0, dispatchInfo=..., resultOut=0x7fffffffd4a0)                                           
   at ../lib/bullet/src/BulletCollision/CollisionDispatch/btConvexConcaveCollisionAlgorithm.cpp:188                                                                                                                   
#8  0x00000000011e0cbc in btCompoundLeafCallback::ProcessChildShape (this=0x7fffffffd300, childShape=0x2326a30, index=0) at ../lib/bullet/src/BulletCollision/CollisionDispatch/btCompoundCollisionAlgorithm.cpp:155   
#9  0x00000000011e105f in btCompoundLeafCallback::Process (this=0x7fffffffd300, leaf=0x219f6b0) at ../lib/bullet/src/BulletCollision/CollisionDispatch/btCompoundCollisionAlgorithm.cpp:182                            
#10 0x000000000119f2e1 in btDbvt::collideTV (this=0x2325630, root=0x219f6b0, vol=..., policy=...) at ../lib/bullet/src/BulletCollision/BroadphaseCollision/btDbvt.h:932                                                
#11 0x00000000011e027c in btCompoundCollisionAlgorithm::processCollision (this=0x211f3a0, body0=0x22e39f0, body1=0x2294a10, dispatchInfo=..., resultOut=0x7fffffffd4a0)                                                
   at ../lib/bullet/src/BulletCollision/CollisionDispatch/btCompoundCollisionAlgorithm.cpp:252                                                                                                                        
#12 0x00000000011a5ebf in btCollisionDispatcher::defaultNearCallback (collisionPair=..., dispatcher=..., dispatchInfo=...) at ../lib/bullet/src/BulletCollision/CollisionDispatch/btCollisionDispatcher.cpp:275        
#13 0x00000000011a6680 in btCollisionPairCallback::processOverlap (this=0x7fffffffd610, pair=...) at ../lib/bullet/src/BulletCollision/CollisionDispatch/btCollisionDispatcher.cpp:231                                 
#14 0x00000000011a4366 in btHashedOverlappingPairCache::processAllOverlappingPairs (this=0x21ec750, callback=0x7fffffffd610, dispatcher=0x20e1600)                                                                     
   at ../lib/bullet/src/BulletCollision/BroadphaseCollision/btOverlappingPairCache.cpp:387                                                                                                                            
#15 0x00000000011a5d65 in btCollisionDispatcher::dispatchAllCollisionPairs (this=0x20e1600, pairCache=0x21ec750, dispatchInfo=..., dispatcher=0x20e1600)                                                               
   at ../lib/bullet/src/BulletCollision/CollisionDispatch/btCollisionDispatcher.cpp:245                                                                                                                               
#16 0x00000000011a7630 in btCollisionWorld::performDiscreteCollisionDetection (this=0x21b1440) at ../lib/bullet/src/BulletCollision/CollisionDispatch/btCollisionWorld.cpp:229                                         
#17 0x00000000011828df in btDiscreteDynamicsWorld::internalSingleStepSimulation (this=0x21b1440, timeStep=0.00833333377) at ../lib/bullet/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.cpp:334                  
#18 0x000000000118272b in btDiscreteDynamicsWorld::stepSimulation (this=0x21b1440, timeStep=0.00833333377, maxSubSteps=1, fixedTimeStep=0.00833333377)                                                                 
   at ../lib/bullet/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.cpp:290                                                                                                                                       
#19 0x0000000000fc4acf in Physics::update (this=0x1fabb80, ticks=1) at ../src/physics/physics.cpp:168                                                                                                                  
#20 0x0000000000f06791 in World::update (this=0x7fffb8001460, ticks=1) at ../src/modes/world.cpp:1101                                                                                                                  
#21 0x0000000000ee51ce in LinearWorld::update (this=0x7fffb8001460, ticks=1) at ../src/modes/linear_world.cpp:180                                                                                                      
#22 0x0000000000f05c8b in World::updateWorld (this=0x7fffb8001460, ticks=1) at ../src/modes/world.cpp:916                                                                                                              
#23 0x0000000000f6de2e in RaceEventManager::update (this=0x2084210, ticks=1) at ../src/network/race_event_manager.cpp:35                                                                                               
#24 0x0000000000ed1a42 in MainLoop::updateRace (this=0x1eecfb0, ticks=1) at ../src/main_loop.cpp:206                                                                                                                   
#25 0x0000000000ed2320 in MainLoop::run (this=0x1eecfb0) at ../src/main_loop.cpp:471                                                                                                                                   
#26 0x0000000000ec6c06 in main (argc=4, argv=0x7fffffffe608) at ../src/main.cpp:2241                                                                                                                                  
or:

#0  0x00000000011e37f7 in btConvexConvexAlgorithm::processCollision (this=0x2f7c7d0, body0=0x3a09ce0, body1=0x39c02c0, dispatchInfo=..., resultOut=0x7fffffffd500)                                                     
   at ../lib/bullet/src/BulletCollision/CollisionDispatch/btConvexConvexAlgorithm.cpp:532                                                                                                                             
#1  0x00000000011e1990 in btConvexTriangleCallback::processTriangle (this=0x2f7ca40, triangle=0x7fffffffcde8, partId=0, triangleIndex=26467)                                                                           
   at ../lib/bullet/src/BulletCollision/CollisionDispatch/btConvexConcaveCollisionAlgorithm.cpp:125                                                                                                                   
#2  0x00000000011b7518 in btBvhTriangleMeshShape::MyNodeOverlapCallback::processNode (this=0x7fffffffcdd0, nodeSubPart=0, nodeTriangleIndex=26467)                                                                     
   at ../lib/bullet/src/BulletCollision/CollisionShapes/btBvhTriangleMeshShape.cpp:315                                                                                                                                
#3  0x00000000011d5f8a in btQuantizedBvh::walkStacklessTree (this=0x2f7b340, nodeCallback=0x7fffffffcdd0, aabbMin=..., aabbMax=...) at ../lib/bullet/src/BulletCollision/BroadphaseCollision/btQuantizedBvh.cpp:376    
#4  0x00000000011d5ece in btQuantizedBvh::reportAabbOverlappingNodex (this=0x2f7b340, nodeCallback=0x7fffffffcdd0, aabbMin=..., aabbMax=...)                                                                           
   at ../lib/bullet/src/BulletCollision/BroadphaseCollision/btQuantizedBvh.cpp:345                                                                                                                                    
#5  0x00000000011b759b in btBvhTriangleMeshShape::processAllTriangles (this=0x357e3f0, callback=0x2f7ca40, aabbMin=..., aabbMax=...)                                                                                   
   at ../lib/bullet/src/BulletCollision/CollisionShapes/btBvhTriangleMeshShape.cpp:323                                                                                                                                
#6  0x00000000011e1d2a in btConvexConcaveCollisionAlgorithm::processCollision (this=0x2f7ca28, body0=0x3a09ce0, body1=0x39c02c0, dispatchInfo=..., resultOut=0x7fffffffd500)                                           
   at ../lib/bullet/src/BulletCollision/CollisionDispatch/btConvexConcaveCollisionAlgorithm.cpp:188                                                                                                                   
#7  0x00000000011e0cbc in btCompoundLeafCallback::ProcessChildShape (this=0x7fffffffd360, childShape=0x39fcfe0, index=0) at ../lib/bullet/src/BulletCollision/CollisionDispatch/btCompoundCollisionAlgorithm.cpp:155   
#8  0x00000000011e105f in btCompoundLeafCallback::Process (this=0x7fffffffd360, leaf=0x3a08fa0) at ../lib/bullet/src/BulletCollision/CollisionDispatch/btCompoundCollisionAlgorithm.cpp:182                            
#9  0x000000000119f2e1 in btDbvt::collideTV (this=0x2ec7b80, root=0x3a08fa0, vol=..., policy=...) at ../lib/bullet/src/BulletCollision/BroadphaseCollision/btDbvt.h:932                                                
#10 0x00000000011e027c in btCompoundCollisionAlgorithm::processCollision (this=0x2f7c9b0, body0=0x39c02c0, body1=0x3a09ce0, dispatchInfo=..., resultOut=0x7fffffffd500)                                                
   at ../lib/bullet/src/BulletCollision/CollisionDispatch/btCompoundCollisionAlgorithm.cpp:252                                                                                                                        
#11 0x00000000011a5ebf in btCollisionDispatcher::defaultNearCallback (collisionPair=..., dispatcher=..., dispatchInfo=...) at ../lib/bullet/src/BulletCollision/CollisionDispatch/btCollisionDispatcher.cpp:275        
#12 0x00000000011a6680 in btCollisionPairCallback::processOverlap (this=0x7fffffffd670, pair=...) at ../lib/bullet/src/BulletCollision/CollisionDispatch/btCollisionDispatcher.cpp:231                                 
#13 0x00000000011a4366 in btHashedOverlappingPairCache::processAllOverlappingPairs (this=0x2f0fa20, callback=0x7fffffffd670, dispatcher=0x2ec7f50)                                                                     
   at ../lib/bullet/src/BulletCollision/BroadphaseCollision/btOverlappingPairCache.cpp:387                                                                                                                            
#14 0x00000000011a5d65 in btCollisionDispatcher::dispatchAllCollisionPairs (this=0x2ec7f50, pairCache=0x2f0fa20, dispatchInfo=..., dispatcher=0x2ec7f50)                                                               
   at ../lib/bullet/src/BulletCollision/CollisionDispatch/btCollisionDispatcher.cpp:245                                                                                                                               
#15 0x00000000011a7630 in btCollisionWorld::performDiscreteCollisionDetection (this=0x2e77420) at ../lib/bullet/src/BulletCollision/CollisionDispatch/btCollisionWorld.cpp:229                                         
#16 0x00000000011828df in btDiscreteDynamicsWorld::internalSingleStepSimulation (this=0x2e77420, timeStep=0.00833333377) at ../lib/bullet/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.cpp:334                  
#17 0x000000000118272b in btDiscreteDynamicsWorld::stepSimulation (this=0x2e77420, timeStep=0.00833333377, maxSubSteps=1, fixedTimeStep=0.00833333377)                                                                 
   at ../lib/bullet/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.cpp:290                                                                                                                                       
#18 0x0000000000fc4acf in Physics::update (this=0x2d84b20, ticks=1) at ../src/physics/physics.cpp:168                                                                                                                  
#19 0x0000000000f06791 in World::update (this=0x2dbdb40, ticks=1) at ../src/modes/world.cpp:1101                                                                                                                       
#20 0x0000000000ee51ce in LinearWorld::update (this=0x2dbdb40, ticks=1) at ../src/modes/linear_world.cpp:180                                                                                                           
#21 0x0000000000f05c8b in World::updateWorld (this=0x2dbdb40, ticks=1) at ../src/modes/world.cpp:916                                                                                                                   
#22 0x0000000000f6de2e in RaceEventManager::update (this=0x2d521b0, ticks=1) at ../src/network/race_event_manager.cpp:35                                                                                               
#23 0x0000000000ed1a42 in MainLoop::updateRace (this=0x234a770, ticks=1) at ../src/main_loop.cpp:206                                                                                                                   
#24 0x0000000000ed2320 in MainLoop::run (this=0x234a770) at ../src/main_loop.cpp:471                                                                                                                                   
#25 0x0000000000ec6c06 in main (argc=1, argv=0x7fffffffe668) at ../src/main.cpp:2241                                                                                                                                  
(you can host a time trial server so no items are involved, --mode=1)

**Comment by hiker** [comment] 2019-02-15 13:13
Is this still an issue? I had investigated this in the past without any real progress - I never had a bullet collision slowdown :(

**Comment by Benau** [comment] 2019-02-15 13:22
then delay it so we can release quicker, esp i don't see slowdown anymore recently

**Comment by hiker** [comment] 2019-02-16 15:17
OK, if we can't reproduce it, I'll just close it for now.

**Closed by hiker** 2019-02-16 15:17 UTC
Labels: C:Networking, P2: major, T: defect
