### ISSUE TITLE
Billboards not compatible with Alpha testing

### ISSUE THREAD

**Issue by samuncle** [supertuxkart/stk-code#2943] opened 2017-09-25 10:04 UTC
While trying to improve performance on a few maps I wanted to use billboards for trees, vegetations, etc especially for landscape.

However it appears billboards only support alpha blending and additive alpha. It would be important to have alpha testing as well (I suppose this also could be used to improve performance on android devices)

**Comment by auriamg** [comment] 2017-09-26 01:00
Duplicate of #2427

**Closed by auriamg** 2017-09-26 01:00 UTC
Labels: R: duplicate
