### ISSUE TITLE
STK crashes while loading kart selection menu after one race

### ISSUE THREAD

**Issue by masoug** [supertuxkart/stk-code#1262] opened 2014-03-26 01:08 UTC
Platform: Fedora Linux 20 STK 0.8.1

STK is crashing when I bring up the kart selection menu after one race. This doesn't happen after running story mode.

Stack Trace:
```
#0  0x0860a516 in FocusDispatcher::setRootID (this=0x0, reservedID=100) at /home/masoug/Programming/SuperTuxKart/stk-script/stk-code/src/states_screens/kart_selection.cpp:97
#1  0x0860d81e in KartSelectionScreen::init (this=0xcb7d0a8) at /home/masoug/Programming/SuperTuxKart/stk-script/stk-code/src/states_screens/kart_selection.cpp:951
#2  0x0846b636 in GUIEngine::AbstractStateManager::pushScreen (this=0x9062820, screen=0xcb7d0a8)
    at /home/masoug/Programming/SuperTuxKart/stk-script/stk-code/src/guiengine/abstract_state_manager.cpp:134
#3  0x08615f64 in MainMenuScreen::eventCallback (this=0xca70af0, widget=0xcb849e0, name="menu_toprow", playerID=0)
    at /home/masoug/Programming/SuperTuxKart/stk-script/stk-code/src/states_screens/main_menu_screen.cpp:304
#4  0x0847b766 in GUIEngine::EventHandler::sendEventToUser (this=0x963dd90, widget=0xcb849e0, name="menu_toprow", playerID=0)
    at /home/masoug/Programming/SuperTuxKart/stk-script/stk-code/src/guiengine/event_handler.cpp:623
#5  0x0847b952 in GUIEngine::EventHandler::onWidgetActivated (this=0x963dd90, w=0xcbc5280, playerID=0)
    at /home/masoug/Programming/SuperTuxKart/stk-script/stk-code/src/guiengine/event_handler.cpp:663
#6  0x0847bbc3 in GUIEngine::EventHandler::onGUIEvent (this=0x963dd90, event=...) at /home/masoug/Programming/SuperTuxKart/stk-script/stk-code/src/guiengine/event_handler.cpp:708
#7  0x0847a870 in GUIEngine::EventHandler::OnEvent (this=0x963dd90, event=...) at /home/masoug/Programming/SuperTuxKart/stk-script/stk-code/src/guiengine/event_handler.cpp:149
#8  0x08945393 in irr::gui::CGUIButton::OnEvent (this=0xd097840, event=...)
    at /home/masoug/Programming/SuperTuxKart/stk-script/stk-code/lib/irrlicht/source/Irrlicht/CGUIButton.cpp:225
#9  0x089454af in irr::gui::CGUIButton::OnEvent (this=0xd096c80, event=...)
    at /home/masoug/Programming/SuperTuxKart/stk-script/stk-code/lib/irrlicht/source/Irrlicht/CGUIButton.cpp:215
#10 0x088171ec in irr::gui::CGUIEnvironment::postEventFromUser (this=0x8fba048, event=...)
    at /home/masoug/Programming/SuperTuxKart/stk-script/stk-code/lib/irrlicht/source/Irrlicht/CGUIEnvironment.cpp:570
#11 0x087a4730 in irr::CIrrDeviceStub::postEventFromUser (this=0x8d5a0b8, event=...)
    at /home/masoug/Programming/SuperTuxKart/stk-script/stk-code/lib/irrlicht/source/Irrlicht/CIrrDeviceStub.cpp:220
#12 0x0879b6ce in irr::CIrrDeviceLinux::run (this=0x8d5a0b8) at /home/masoug/Programming/SuperTuxKart/stk-script/stk-code/lib/irrlicht/source/Irrlicht/CIrrDeviceLinux.cpp:1074
#13 0x08417dbf in IrrDriver::update (this=0x8d59dc0, dt=0.029000001) at /home/masoug/Programming/SuperTuxKart/stk-script/stk-code/src/graphics/irr_driver.cpp:1784
#14 0x0853add7 in MainLoop::run (this=0x9b31b78) at /home/masoug/Programming/SuperTuxKart/stk-script/stk-code/src/main_loop.cpp:153
#15 0x08538964 in main (argc=1, argv=0xbffff104) at /home/masoug/Programming/SuperTuxKart/stk-script/stk-code/src/main.cpp:1334
```

**Comment by deveee** [comment] 2015-01-09 13:25
Actually duplicate of #1347 (which has full backtrace)

**Closed by deveee** 2015-01-09 13:25 UTC
Labels: T: defect
