### ISSUE TITLE
Un-Fullscreen freezes the game

### ISSUE THREAD

**Issue by TheYellowArchitect** [supertuxkart/stk-code#4591] opened 2021-08-31 21:27 UTC
## Description
I use dwm.
Game boots up windowed. Once I press Super+F (makes any window fullscreen), game becomes truly fullscreen (no window borders), but when I press it to become windowed again, it freezes, and has to be killed manually (at least the rest of the pc works)

## Configuration

STK release version:  1.3-rc1

STK Source (PPA, distribution package, official binary, etc.): 
https://github.com/supertuxkart/stk-code/releases/tag/1.3-rc1

System: Artix (Arch Linux but replaced systemd with openrc)

Graphics card: Unironically no idea how to check it out with Linux, would have to open the box or boot with windows lol

CPU: AMD Ryzen 5 2600 Six-Core Processor

Gamepads/keyboards models if related to the issue: 

## Additional information
This is from the terminal t
```[ALSOFT] (WW) Cannot connect to server socket err = No such file or directory
[ALSOFT] (WW) Cannot connect to server request channel
[ALSOFT] (WW) jack server is not running or cannot be started
[ALSOFT] (WW) JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
[ALSOFT] (WW) JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
[ALSOFT] (WW) jack_client_open() failed, 0x11
[ALSOFT] (WW) Failed to initialize backend "jack"
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[info   ] GrandPrixManager: Loading Grand Prix files from /home/solomos/.local/bin/supertuxkart1.3/data/grandprix/
[info   ] GrandPrixManager: Loading Grand Prix files from /home/solomos/.local/share/supertuxkart/grandprix/
[warn   ] SPMeshBuffer: kartDirt shader is missing, fallback to solid
[warn   ] SPMeshBuffer: kartDirt shader is missing, fallback to solid
[warn   ] SPMeshBuffer: kartDirt shader is missing, fallback to solid
[warn   ] SPMeshBuffer: kartDirt shader is missing, fallback to solid
[warn   ] SPMeshBuffer: kartDirt shader is missing, fallback to solid
[info   ] addons: Using cached addons.xml.
[warn   ] LayoutManager: Statically sized widgets took all the place!!
[warn   ] LayoutManager: Statically sized widgets took all the place!!
[info   ] Singleton: Destroyed singleton.
[info   ] Singleton: Destroyed singleton.
[info   ] Singleton: Destroyed singleton.
[info   ] Singleton: Destroyed singleton.
[info   ] Singleton: Destroyed singleton.
[info   ] Singleton: Destroyed singleton.
[info   ] Singleton: Destroyed singleton.
[info   ] Singleton: Destroyed singleton.
[info   ] Singleton: Destroyed singleton.
[info   ] Singleton: Destroyed singleton.
```
This is from stdout.log
```
stdout.log:[info   ] [FileManager]: Data files will be fetched from: '/home/solomos/.local/bin/supertuxkart1.3/data/'
[info   ] [FileManager]: User directory is '/home/solomos/.config/supertuxkart/config-0.10/'.
[info   ] [FileManager]: Addons files will be stored in '/home/solomos/.local/share/supertuxkart/addons/'.
[info   ] [FileManager]: Screenshots will be stored in '/home/solomos/.local/share/supertuxkart/screenshots/'.
[info   ] [FileManager]: User-defined grand prix will be stored in '/home/solomos/.local/share/supertuxkart/grandprix/'.
[info   ] [FileManager]: Asset 0 will be loaded from '/home/solomos/.local/bin/supertuxkart1.3/data/challenges/'.
[info   ] [FileManager]: Asset 1 will be loaded from '/home/solomos/.local/bin/supertuxkart1.3/data/gfx/'.
[info   ] [FileManager]: Asset 2 will be loaded from '/home/solomos/.local/bin/supertuxkart1.3/data/grandprix/'.
[info   ] [FileManager]: Asset 3 will be loaded from '/home/solomos/.local/bin/supertuxkart1.3/data/gui/icons/'.
[info   ] [FileManager]: Asset 4 will be loaded from '/home/solomos/.local/bin/supertuxkart1.3/data/gui/screens/'.
[info   ] [FileManager]: Asset 5 will be loaded from '/home/solomos/.local/bin/supertuxkart1.3/data/gui/dialogs/'.
[info   ] [FileManager]: Asset 6 will be loaded from '/home/solomos/.local/bin/supertuxkart1.3/data/replay/'.
[info   ] [FileManager]: Asset 7 will be loaded from '/home/solomos/.local/bin/supertuxkart1.3/data/shaders/'.
[info   ] [FileManager]: Asset 8 will be loaded from '/home/solomos/.local/bin/supertuxkart1.3/data/skins/'.
[info   ] [FileManager]: Asset 9 will be loaded from '/home/solomos/.local/bin/supertuxkart1.3/data/ttf/'.
[info   ] [FileManager]: Asset 10 will be loaded from '/home/solomos/.local/bin/supertuxkart1.3/data/po/'.
[info   ] [FileManager]: Asset 11 will be loaded from '/home/solomos/.local/bin/supertuxkart1.3/data/library/'.
[info   ] [FileManager]: Asset 12 will be loaded from '/home/solomos/.local/bin/supertuxkart1.3/data/models/'.
[info   ] [FileManager]: Asset 13 will be loaded from '/home/solomos/.local/bin/supertuxkart1.3/data/music/'.
[info   ] [FileManager]: Asset 14 will be loaded from '/home/solomos/.local/bin/supertuxkart1.3/data/sfx/'.
[info   ] [FileManager]: Asset 15 will be loaded from '/home/solomos/.local/bin/supertuxkart1.3/data/textures/'.
[info   ] [FileManager]: Asset 16 will be loaded from '/home/solomos/.local/bin/supertuxkart1.3/data/tracks/'.
[verbose  ] translation: Env var LANGUAGE = 'en_US.UTF-8'.
[verbose  ] translation: Language 'English (United States)'.
[info   ] [IrrDriver Logger]: ..:: Antarctica Rendering Engine 2.0 ::..
[info   ] [IrrDriver Logger]: SDL Version 2.0.15
[info   ] [IrrDriver Logger]: Using renderer: OpenGL 4.3
[info   ] [IrrDriver Logger]: NV137: nouveau
[info   ] [IrrDriver Logger]: OpenGL driver version is 1.2 or better.
[info   ] [IrrDriver Logger]: GLSL version: 4.3
[info   ] IrrDriver: OpenGL version: 4.3
[info   ] IrrDriver: OpenGL vendor: nouveau
[info   ] IrrDriver: OpenGL renderer: NV137
[info   ] IrrDriver: OpenGL version string: 4.3 (Core Profile) Mesa 21.2.1
[info   ] GLDriver: ARB Buffer Storage Present
[info   ] GLDriver: ARB Compute Shader Present
[info   ] GLDriver: ARB Arrays of Arrays Present
[info   ] GLDriver: ARB Texture Storage Present
[info   ] GLDriver: ARB Texture View Present
[info   ] GLDriver: ARB Image Load Store Present
[info   ] GLDriver: ARB Shader Atomic Counters Present
[info   ] GLDriver: ARB Shader Storage Buffer Object Present
[info   ] GLDriver: EXT Texture Compression S3TC Present
[info   ] GLDriver: ARB Uniform Buffer Object Present
[info   ] GLDriver: ARB Explicit Attrib Location Present
[info   ] GLDriver: EXT Texture Filter Anisotropic Present
[info   ] GLDriver: Geometry Shaders Present
[info   ] GLDriver: ARB Texture Swizzle Present
[info   ] GLDriver: ARB Pixel Buffer Object Present
[info   ] GLDriver: ARB Sampler Objects Present
[info   ] GLDriver: ARB Vertex Type 2_10_10_10_rev Present
[info   ] GLDriver: ARB Instanced Arrays Present
[info   ] SharedGPUObjects: Hardware Skinning enabled, method: 1024 (max bones) * 16 RGBA float texture
[info   ] ShaderFilesManager: Compiling shader: /home/solomos/.local/bin/supertuxkart1.3/data/shaders/screenquad.vert
[info   ] ShaderFilesManager: Compiling shader: /home/solomos/.local/bin/supertuxkart1.3/data/shaders/motion_blur.frag
[info   ] ShaderFilesManager: Compiling shader: /home/solomos/.local/bin/supertuxkart1.3/data/shaders/lightning.frag
[info   ] ShaderFilesManager: Compiling shader: /home/solomos/.local/bin/supertuxkart1.3/data/shaders/primitive2dlist.vert
[info   ] ShaderFilesManager: Compiling shader: /home/solomos/.local/bin/supertuxkart1.3/data/shaders/transparent.frag
[info   ] ShaderFilesManager: Compiling shader: /home/solomos/.local/bin/supertuxkart1.3/data/shaders/texturedquad.vert
[info   ] ShaderFilesManager: Compiling shader: /home/solomos/.local/bin/supertuxkart1.3/data/shaders/uniformcolortexturedquad.frag
[info   ] ShaderFilesManager: Compiling shader: /home/solomos/.local/bin/supertuxkart1.3/data/shaders/texturedquad.frag
[info   ] ShaderFilesManager: Compiling shader: /home/solomos/.local/bin/supertuxkart1.3/data/shaders/coloredquad.vert
[info   ] ShaderFilesManager: Compiling shader: /home/solomos/.local/bin/supertuxkart1.3/data/shaders/coloredquad.frag
[info   ] ShaderFilesManager: Compiling shader: /home/solomos/.local/bin/supertuxkart1.3/data/shaders/colortexturedquad.vert
[info   ] ShaderFilesManager: Compiling shader: /home/solomos/.local/bin/supertuxkart1.3/data/shaders/colortexturedquad.frag
[info   ] irr_driver: GLSL supported.
[info   ] ShaderFilesManager: Compiling shader: /home/solomos/.local/bin/supertuxkart1.3/data/shaders/sp_pass.vert
[info   ] ShaderFilesManager: Compiling shader: /home/solomos/.local/bin/supertuxkart1.3/data/shaders/sp_solid.frag
[info   ] ShaderFilesManager: Compiling shader: /home/solomos/.local/bin/supertuxkart1.3/data/shaders/sp_shadow.vert
[info   ] ShaderFilesManager: Compiling shader: /home/solomos/.local/bin/supertuxkart1.3/data/shaders/white.frag
[info   ] ShaderFilesManager: Compiling shader: /home/solomos/.local/bin/supertuxkart1.3/data/shaders/sp_skinning.vert
[info   ] ShaderFilesManager: Compiling shader: /home/solomos/.local/bin/supertuxkart1.3/data/shaders/sp_skinning_shadow.vert
[info   ] ShaderFilesManager: Compiling shader: /home/solomos/.local/bin/supertuxkart1.3/data/shaders/sp_normal_map.frag
[info   ] ShaderFilesManager: Compiling shader: /home/solomos/.local/bin/supertuxkart1.3/data/shaders/sp_alpha_test.frag
[info   ] ShaderFilesManager: Compiling shader: /home/solomos/.local/bin/supertuxkart1.3/data/shaders/sp_shadow_alpha_test.frag
[info   ] ShaderFilesManager: Compiling shader: /home/solomos/.local/bin/supertuxkart1.3/data/shaders/sp_decal.frag
[info   ] ShaderFilesManager: Compiling shader: /home/solomos/.local/bin/supertuxkart1.3/data/shaders/sp_grass_pass.vert
[info   ] ShaderFilesManager: Compiling shader: /home/solomos/.local/bin/supertuxkart1.3/data/shaders/sp_grass.frag
[info   ] ShaderFilesManager: Compiling shader: /home/solomos/.local/bin/supertuxkart1.3/data/shaders/sp_grass_shadow.vert
[info   ] ShaderFilesManager: Compiling shader: /home/solomos/.local/bin/supertuxkart1.3/data/shaders/sp_unlit.frag
[info   ] ShaderFilesManager: Compiling shader: /home/solomos/.local/bin/supertuxkart1.3/data/shaders/sp_transparent.frag
[info   ] ShaderFilesManager: Compiling shader: /home/solomos/.local/bin/supertuxkart1.3/data/shaders/sp_ghost.frag
[info   ] ShaderFilesManager: Compiling shader: /home/solomos/.local/bin/supertuxkart1.3/data/shaders/sp_dynamic_night_bloom.frag
[info   ] ShaderFilesManager: Compiling shader: /home/solomos/.local/bin/supertuxkart1.3/data/shaders/sp_tilling_mitigation.frag
[info   ] ShaderFilesManager: Compiling shader: /home/solomos/.local/bin/supertuxkart1.3/data/shaders/sp_vertical_mapping.frag
[info   ] ShaderFilesManager: Compiling shader: /home/solomos/.local/bin/supertuxkart1.3/data/shaders/sp_road_blending.frag
[info   ] ShaderFilesManager: Compiling shader: /home/solomos/.local/bin/supertuxkart1.3/data/shaders/sp_displace.frag
[info   ] ShaderFilesManager: Compiling shader: /home/solomos/.local/bin/supertuxkart1.3/data/shaders/colorize.frag
[info   ] ShaderFilesManager: Compiling shader: /home/solomos/.local/bin/supertuxkart1.3/data/shaders/sp_normal_visualizer.vert
[info   ] ShaderFilesManager: Compiling shader: /home/solomos/.local/bin/supertuxkart1.3/data/shaders/sp_normal_visualizer.geom
[info   ] ShaderFilesManager: Compiling shader: /home/solomos/.local/bin/supertuxkart1.3/data/shaders/sp_normal_visualizer.frag
[info   ] HTTPRequest: Downloading https://online.supertuxkart.net/dl/xml/online_news.xml
[info   ] GrandPrixManager: Loading Grand Prix files from /home/solomos/.local/bin/supertuxkart1.3/data/grandprix/
[info   ] GrandPrixManager: Loading Grand Prix files from /home/solomos/.local/share/supertuxkart/grandprix/
[warn   ] SPMeshBuffer: kartDirt shader is missing, fallback to solid
[warn   ] SPMeshBuffer: kartDirt shader is missing, fallback to solid
[warn   ] SPMeshBuffer: kartDirt shader is missing, fallback to solid
[warn   ] SPMeshBuffer: kartDirt shader is missing, fallback to solid
[warn   ] SPMeshBuffer: kartDirt shader is missing, fallback to solid
[info   ] addons: Using cached addons.xml.
[warn   ] LayoutManager: Statically sized widgets took all the place!!
[warn   ] LayoutManager: Statically sized widgets took all the place!!
[info   ] Singleton: Destroyed singleton.
[info   ] Singleton: Destroyed singleton.
[info   ] Singleton: Destroyed singleton.
[info   ] Singleton: Destroyed singleton.
[info   ] Singleton: Destroyed singleton.
[info   ] Singleton: Destroyed singleton.
[info   ] Singleton: Destroyed singleton.
[info   ] Singleton: Destroyed singleton.
[info   ] Singleton: Destroyed singleton.
[info   ] Singleton: Destroyed singleton.
```

**Comment by Benau** [comment] 2021-09-01 03:14
I cannot reproduce and super-f doesn't work for me at all, this bug probably related to SDL2... you can try starting stk with ```SDL_DYNAMIC_API=/usr/lib/libSDL2-2.0.so ./run_game.sh```

**Comment by TheYellowArchitect** [comment] 2021-09-01 10:25
I went to the location of that folder, and typed `SDL_DYNAMIC_API=/usr/lib/libSDL2-2.0.so ./run_game.sh` and it still freezes on fullscreen toggling

Anyway, it is not a serious issue, since I can just fullscreen the terminal and run the game lol
Just wanted to report this bug

**Comment by qwertychouskie** [comment] 2021-09-02 00:01
Can you post the output of `glxinfo`?

I suspect this could be caused by dwm doing something weird.  Do you get the same issue with different WMs?

**Comment by TheYellowArchitect** [comment] 2021-09-02 14:38
Sure, just tell me where to find that file and I will post it :+1:

**Comment by qwertychouskie** [comment] 2021-09-03 01:34
It's not a file, it's a command.  Just run it in a terminal and paste the output here.

**Comment by Benau** [comment] 2021-09-03 15:01
actually SDL_DYNAMIC_API won't work if you use a older sdl2....
can you try inside your  SuperTuxKart-1.3-rc1-linux-64bit folder, ```cp /usr/lib/libSDL2-2.0.so.0 lib/libSDL2-2.0.so.0```
and then ./run_game.sh again

or whatever full path which has libSDL2-2.0.so.0
basically we are trying to use a (older) sdl2 and see if it fixes your problem ![](https://cdn.lihkg.com/assets/faces/mouse/yea.gif)

**Comment by TheYellowArchitect** [comment] 2021-09-03 16:05
> It's not a file, it's a command. Just run it in a terminal and paste the output here.

I don't have that command in my computer "zsh: command not found: glxinfo"

> Do you get the same issue with different WMs?

idk what WM is, but if you mean window managers, I have only tried my current configuration of dwm. [It is autistic](https://github.com/LukeSmithxyz/LARBS), but it is not unpopular

> can you try inside your SuperTuxKart-1.3-rc1-linux-64bit folder, cp /usr/lib/libSDL2-2.0.so.0 lib/libSDL2-2.0.so.0
and then ./run_game.sh again

Did it, still didn't work, got [video footage of the fullscreen to freeze (towards the end)](https://files.catbox.moe/s2otnj.mp4) in case it is useful in the future, but anyway, I hope the devs don't focus on this minor rare bug instead of important features e.g. better story mode

**Comment by Benau** [comment] 2021-09-03 17:09
Well it has nothing to do with stk(but SDL2 stk is using) so we are closing this issue ![](https://cdn.lihkg.com/assets/faces/pig/bye.gif)

**Closed by Benau** 2021-09-03 17:09 UTC
