### ISSUE TITLE
Make FPS unlimited on title screen

### ISSUE THREAD

**Issue by MarkkusCraft123** [supertuxkart/stk-code#2302] opened 2015-08-30 22:11 UTC
In my opinion, the STK menus look better when the fps is not capped.  If you want to see what I mean, you can do it by turning on the artist debug mode and on the menu screen you can select do not limit fps.

**Comment by deveee** [comment] 2015-08-31 18:21
In my opinion it doesn't matter at all. What's the difference that you see?

**Comment by auriamg** [comment] 2015-08-31 23:27
Also there is little use in having the game use 100% CPU+GPU at a ludicrius framerate (menus will easily go to 200-300 FPS without cap), when out of the game, or when paused. I see little use

**Comment by MarkkusCraft123** [comment] 2015-09-01 01:37
Lock at 60? I am a frame rate junky and the I can't stand the current fps.

**Comment by deveee** [comment] 2015-09-01 15:36
I think that human's eye can't see 60 fps and everything is in your mind :-P

The problem isn't that fps is too low, but that it doesn't have constant value. The counter shows you that averaged fps is 29.9, but in fact you have for example 30.0, 30.0, 30.0, 1.0, 30.0 etc... And the game is not smooth because of this.

And still 30 fps is certainly enough for gui with few buttons and simple animations. It's not a real game where you need higher responsivity.

I'm closing this as invalid.

**Closed by deveee** 2015-09-01 15:36 UTC

**Comment by deveee** [comment] 2015-09-01 20:43
I prepared for you an example:

```

**Comment by MarkkusCraft123** [comment] 2015-09-02 00:28
How about this:

<code>const double wanted_fps = 60.0;
const int peak_frequency = 100; // once per 100 frames
const int peak_duration = 0; // 0 ms</code>

**Comment by leyyin** [comment] 2015-09-04 04:18
@MarkkusCraft123 I am curios, what is your monitor refresh rate?

**Comment by MarkkusCraft123** [comment] 2015-09-11 01:22
60 Hz

**Comment by deveee** [comment] 2015-09-11 06:39
Just to clarify, if I use nvidia graphics card, then indeed it looks a bit
smoother. But it's because nvidia driver automatically locks it at
precisely 60 fps (adaptive vsync?). And this is advantage of vsync
technology, not of higher fps. With disabled vsync I see no difference.

**Comment by MarkkusCraft123** [comment] 2015-09-13 15:24
I use an Intel HD 3000 now
, I got an i3.

**Comment by qwertychouskie** [comment] 2016-09-06 00:17
On my system (Intel HD 3000, laptop's built-in screen at 60 Hz), when I use the Artist Debug Menu to un-limit the FPS, the menu looks way smoother.  The menu, when not limited, runs at 60 FPS.

> The problem isn't that fps is too low, but that it doesn't have constant value. The counter shows you that averaged fps is 29.9, but in fact you have for example 30.0, 30.0, 30.0, 1.0, 30.0 etc... And the game is not smooth because of this.

But, until the roughness is fixed, setting the limit to 60 FPS makes it look way better.  If the roughness is fixed in the future, 31 FPS might be fine, but in the mean time, could it be set to 60?  This is a value that shouldn't put all but the weakest GPUs at 100%, but makes the menu look way better, at least on my system.

**Comment by MarkkusCraft** [comment] 2016-09-21 23:18
Same GPU here. I put the topic on this issue as, "Make FPS unlimited on title screen", but I should have put it as, "Make FPS limited to VSync on title Screen". I just have a hard time looking at the FPS. The main menus are just fine, it's just the kart selection screen that really made me want to open this issue.

**Comment by Arthur-D** [comment] 2017-03-27 21:47
From my personal experience, I've found that the kart selection screen currently is a bit laggy with NVIDIA, and setting it to 60 might make sense there. But deveee is right that 30 FPS should be smooth enough at moderate animation speeds. It is when playing the game, so maybe it has to do with Render-To-Texture, and maybe with only some graphics drivers.
