### ISSUE TITLE
SegF at finish of nitro challenge on quicksands map

### ISSUE THREAD

**Issue by tomreyn** [supertuxkart/stk-code#1950] opened 2015-02-02 00:10 UTC
I was just taking the nitro challenge on the quicksands map using the emule kart on Ubuntu 14.04 amd64, then ran into this:

[GDB output](https://tomreyn.megaglest.org/stk_1e0a9022a30393a5af52cf2f5b5d222c6633aebd_quicksands_nitro_finish.txt)

Unfortunately there are [no debugging symbols](http://packages.ubuntu.com/search?keywords=libopenal1-dbg) available for libopenal1 on Ubuntu trusty (14.04).

**Comment by tomreyn** [comment] 2015-02-02 01:47
I just reproduced it without the nitro challenge but by just running this track alone, without AI. That's because it doesn't seem to happen when there are AI players.

gdb https://tomreyn.megaglest.org/stk_1e0a9022a30393a5af52cf2f5b5d222c6633aebd_quicksands_nonitro_finish.txt
stdout https://tomreyn.megaglest.org/stk_1e0a9022a30393a5af52cf2f5b5d222c6633aebd_quicksands_nonitro_finish.log

And it doesn't happen with gfx at level 2 (instead of 3),

**Comment by math07** [comment] 2015-02-02 13:13
I can't reproduce on Windows 8.1 and  HD 4600 latest driver. It looks like a graphic driver or platform specific issue. Nice find!

**Comment by tomreyn** [comment] 2015-02-02 21:09
Maybe someone else using Ubuntu 14.04 amd64 with [xorg-edgers](https://launchpad.net/~xorg-edgers/+archive/ubuntu/ppa?field.series_filter=trusty) (AMD/ATI) Radeon (open source) MESA drivers will be able to reproduce this.

**Comment by hiker** [comment] 2015-02-04 23:08
Most likely caused by two threads accessing vorbis (or other audio functions) at the same time. Should be fixed in c37e1eec0df53433cf1cffdd0b263bbcd8169179 to 1e994748cc3f7c86ead7c9d58084bb20f97389ea

Please reopen (with a new stack trace if possible) if this should still happen.

Thanks for the report!
  Joerg

**Closed by hiker** 2015-02-04 23:08 UTC

**Comment by tomreyn** [comment] 2015-02-05 00:33
```
<tomreyn> hiker: that's sooo fixed! :)
<tomreyn> gj
```
