### ISSUE TITLE
Paper cuts: several "panel" issues

### ISSUE THREAD

**Issue by ghost** [supertuxkart/stk-code#3137] opened 2018-03-14 13:49 UTC
I decided to test everything, the first maps and all game modes and I've found some panel issues on some maps and took screenshots of them and put a rectangle to show them.

By "**panel**" I mean the **flat texture panels** that create a wall, a mountain, a pyramid and other surfaces.

When I pass by them they usually **flicker/glitches**(part of the structure disappear for a split second and appear again) at some spots, it happens just in some maps, not all of them. Most off them if you stay still at the location that it happens, you can take a screenshot of the issue(this is what I did).

Specs:

Quality 2
Fullscreen
VSync enabled

STK release version:
Version: 0.9.3-1

STK Source (ppa, distribution package, official bin,...):
gnome-software

System:

```
Ubuntu 18.04 bionic (dev branch)
Kernel: x86_64 Linux 4.15.0-10-generic
Desktop: Gnome 3.27.92

CPU:       Dual core Intel Core i5-2410M (-MT-MCP-) 
           arch: Sandy Bridge rev.7 cache: 3072 KB
           flags: (lm nx sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx) bmips: 9179
           clock speeds: min/max: 800/2900 MHz 1: 801 MHz 2: 800 MHz
           3: 801 MHz 4: 805 MHz
Graphics:  Card: Intel 2nd Generation Core Integrated Graphics Controller
           bus-ID: 00:02.0 chip-ID: 8086:0116
           Display Server: x11 (X.Org 1.19.6 ) driver: i915
           Resolution: 1366x768@59.97hz
           OpenGL: renderer: Mesa DRI Intel Sandybridge Mobile
           version: 3.3 Mesa 18.0.0-rc4 (compat-v: 3.0) Direct Render: Yes

GPU: Intel HD Graphics 3000
```

I stoped racing to take these screenshots and edited them, even if it seems normal it has an issue, sometimes it's hard to capture the exact moment it happens so it looks normal:

![panels1](https://user-images.githubusercontent.com/34775187/37405852-8d65cc24-2774-11e8-9055-72886799f115.png)
![panels2](https://user-images.githubusercontent.com/34775187/37405853-8d92a960-2774-11e8-9ffa-a654d8a75c1f.png)
![panels3](https://user-images.githubusercontent.com/34775187/37405854-8dbdd1b2-2774-11e8-919e-69fed8f944f7.png)
![panels4](https://user-images.githubusercontent.com/34775187/37405855-8dddf604-2774-11e8-9515-5904ecbd661e.png)
![panels5](https://user-images.githubusercontent.com/34775187/37405856-8dffa1e6-2774-11e8-8e37-ceda6c7de535.png)
![panels6](https://user-images.githubusercontent.com/34775187/37405857-8e21d3f6-2774-11e8-8352-ccff49e136a0.png)
![panels7](https://user-images.githubusercontent.com/34775187/37405858-8e4aa0f6-2774-11e8-9104-0383e5ca3722.png)
![panels8](https://user-images.githubusercontent.com/34775187/37405859-8e6c1c68-2774-11e8-8723-72054a5058c0.png)
![panels9](https://user-images.githubusercontent.com/34775187/37405860-8e930cc4-2774-11e8-8cb3-0b8667e10c06.png)
![panels10](https://user-images.githubusercontent.com/34775187/37405861-8ec5bfe8-2774-11e8-9e8a-df60788bcd73.png)
![panels11](https://user-images.githubusercontent.com/34775187/37405863-8f0ff87e-2774-11e8-9cd2-ecf5fa839f6e.png)
![panels12](https://user-images.githubusercontent.com/34775187/37405864-8f2f4fd0-2774-11e8-8a77-cae79c30a33a.png)
![panels13](https://user-images.githubusercontent.com/34775187/37405865-8f4f75bc-2774-11e8-9cfb-6c085f706d3d.png)
![panels14](https://user-images.githubusercontent.com/34775187/37405866-8f6f4dc4-2774-11e8-8e91-48aca4ef062d.png)
![panels15](https://user-images.githubusercontent.com/34775187/37405867-8f8fd0e4-2774-11e8-99d1-5653391ba3ba.png)
![panels16](https://user-images.githubusercontent.com/34775187/37405868-8fae2f3a-2774-11e8-8786-ec45a7d85b97.png)
![panels17](https://user-images.githubusercontent.com/34775187/37405870-8fce2aba-2774-11e8-822b-d9d82393236e.png)
![panels18](https://user-images.githubusercontent.com/34775187/37405871-8fedaeb2-2774-11e8-8a8e-4930b2607a7e.png)

**Comment by Benau** [comment] 2018-03-14 14:08
I thnk mesa 18 is having serious regression like 17.3

U can try git and see if it works better for u (or mesa 17.2)

**Comment by auriamg** [comment] 2018-03-15 23:05
Some of these tracks (mathclass, pyramids track, scotland) are quite old and we already plan to re-make them, that should fix most issues

**Comment by qwertychouskie** [comment] 2023-04-04 03:41
Unable to reproduce (likely driver bug with that particular old version of Mesa on that specific hardware).  Issue should be closed, as reporter is no longer around to test with newer driver/STK versions.

**Comment by Alayan-stk-2** [comment] 2024-04-25 20:56
Closing, see qwerty's comment.

**Closed by Alayan-stk-2** 2024-04-25 20:56 UTC
Labels: R:not our bug
