### ISSUE TITLE
Kart not visible

### ISSUE THREAD

**Issue by ghost** [supertuxkart/stk-code#3058] opened 2017-11-22 08:52 UTC
Device: Samsung Galaxy Tab 8.4 Pro
Android version: 4.4.2 (stock)
Resolution: 2560:1600

Tried all of the "Graphical Effect Levels" with the same result. Wheels are visible and some kart add-ons, but not the kart itself. Check the screenshot.
![screenshot_2017-11-22-09-35-23](https://user-images.githubusercontent.com/7814432/33117988-ad907038-cf6a-11e7-926b-9597dad2f2c3.png)
![screenshot_2017-11-22-09-54-04](https://user-images.githubusercontent.com/7814432/33118139-26febb96-cf6b-11e7-9b88-e526deeeba25.png)

**Comment by Benau** [comment] 2017-11-22 09:25
Try disable steering animation?

Maybe i need unroll the for loop in skinning.vert...

**Comment by nenadperic** [comment] 2017-11-22 10:52
Hi,

Thanks for the reply! After some more digging, I figured out that option "Animated Characters" is causing the kart to become invisible. Setting this option to "Disabled" makes the kart visible, although not animated. This is good enough for me :).

As far as I'm concerned, this no longer an issue, feel free to close this ticket.

**Comment by Benau** [comment] 2017-11-22 16:50
(I assume skinned mesh shader compiling error is happening)

Do you know how to edit /sdcard/stk/data/shaders/skinning.vert ? (via adb push / edit it)

Replace it with this:
```
#ifdef GL_ES
uniform mat4 ModelMatrix;
uniform mat4 InverseModelMatrix;
uniform vec2 texture_trans;
#else
uniform mat4 ModelMatrix =
    mat4(1., 0., 0., 0.,
         0., 1., 0., 0.,
         0., 0., 1., 0.,
         0., 0., 0., 1.);
uniform mat4 InverseModelMatrix =
    mat4(1., 0., 0., 0.,
         0., 1., 0., 0.,
         0., 0., 1., 0.,
         0., 0., 0., 1.);

uniform vec2 texture_trans = vec2(0., 0.);
#endif
uniform int skinning_offset;
#ifdef GL_ES
uniform sampler2D skinning_tex;
#else
uniform samplerBuffer skinning_tex;
#endif

#ifdef Explicit_Attrib_Location_Usable
layout(location = 0) in vec3 Position;
layout(location = 1) in vec3 Normal;
layout(location = 2) in vec4 Color;
layout(location = 3) in vec4 Data1;
layout(location = 4) in vec4 Data2;
layout(location = 5) in ivec4 Joint;
layout(location = 6) in vec4 Weight;
#else
in vec3 Position;
in vec3 Normal;
in vec4 Color;
in vec4 Data1;
in vec4 Data2;
in ivec4 Joint;
in vec4 Weight;
#endif

out vec3 nor;
out vec3 tangent;
out vec3 bitangent;
out vec2 uv;
out vec4 color;

#stk_include "utils/getworldmatrix.vert"

void main(void)
{
    mat4 TransposeInverseModelView =  transpose(InverseModelMatrix * InverseViewMatrix);
    vec4 idle_position = vec4(Position, 1.);
    vec4 idle_normal = vec4(Normal, 0.);
    vec4 idle_tangent = vec4(Data1.z, Data1.w, Data2.x, 0.);
    vec4 idle_bitangent = vec4(Data2.y, Data2.z, Data2.w, 0.);
    vec4 skinned_position = vec4(0.);
    vec4 skinned_normal = vec4(0.);
    vec4 skinned_tangent = vec4(0.);
    vec4 skinned_bitangent = vec4(0.);

    mat4 joint_matrix =
        Weight[0] * mat4(
        texelFetch(skinning_tex, ivec2(0, clamp(Joint[0] + skinning_offset, 0, MAX_BONES)), 0),
        texelFetch(skinning_tex, ivec2(1, clamp(Joint[0] + skinning_offset, 0, MAX_BONES)), 0),
        texelFetch(skinning_tex, ivec2(2, clamp(Joint[0] + skinning_offset, 0, MAX_BONES)), 0),
        texelFetch(skinning_tex, ivec2(3, clamp(Joint[0] + skinning_offset, 0, MAX_BONES)), 0)) +
        Weight[1] * mat4(
        texelFetch(skinning_tex, ivec2(0, clamp(Joint[1] + skinning_offset, 0, MAX_BONES)), 0),
        texelFetch(skinning_tex, ivec2(1, clamp(Joint[1] + skinning_offset, 0, MAX_BONES)), 0),
        texelFetch(skinning_tex, ivec2(2, clamp(Joint[1] + skinning_offset, 0, MAX_BONES)), 0),
        texelFetch(skinning_tex, ivec2(3, clamp(Joint[1] + skinning_offset, 0, MAX_BONES)), 0)) +
        Weight[2] * mat4(
        texelFetch(skinning_tex, ivec2(0, clamp(Joint[2] + skinning_offset, 0, MAX_BONES)), 0),
        texelFetch(skinning_tex, ivec2(1, clamp(Joint[2] + skinning_offset, 0, MAX_BONES)), 0),
        texelFetch(skinning_tex, ivec2(2, clamp(Joint[2] + skinning_offset, 0, MAX_BONES)), 0),
        texelFetch(skinning_tex, ivec2(3, clamp(Joint[2] + skinning_offset, 0, MAX_BONES)), 0)) +
        Weight[3] * mat4(
        texelFetch(skinning_tex, ivec2(0, clamp(Joint[3] + skinning_offset, 0, MAX_BONES)), 0),
        texelFetch(skinning_tex, ivec2(1, clamp(Joint[3] + skinning_offset, 0, MAX_BONES)), 0),
        texelFetch(skinning_tex, ivec2(2, clamp(Joint[3] + skinning_offset, 0, MAX_BONES)), 0),
        texelFetch(skinning_tex, ivec2(3, clamp(Joint[3] + skinning_offset, 0, MAX_BONES)), 0));

    skinned_position = joint_matrix * idle_position;
    skinned_normal = joint_matrix * idle_normal;
    skinned_tangent = joint_matrix * idle_tangent;
    skinned_bitangent = joint_matrix * idle_bitangent;

    gl_Position = ProjectionViewMatrix * ModelMatrix * skinned_position;
    // Keep orthogonality
    nor = (TransposeInverseModelView * skinned_normal).xyz;
    // Keep direction
    tangent = (ViewMatrix * ModelMatrix * skinned_tangent).xyz;
    bitangent = (ViewMatrix * ModelMatrix * skinned_bitangent).xyz;
    uv = vec2(Data1.x + texture_trans.x, Data1.y + texture_trans.y);
    color = Color.zyxw;
}
```
And see if it works for you, otherwise do you have adb tools to show what was the error message?

use ```adb logcat | grep "SuperTux\|Irrlicht\|DEBUG"``` in terminal and paste output here

.....maybe deveee can help me add a workaround

**Comment by nenadperic** [comment] 2017-11-23 09:05
Hey, it works! Thank you so much. Please let me know if there is anything else I can test.

I've attached the screenshot and logcat output.
![screenshot_2017-11-23-09-49-02](https://user-images.githubusercontent.com/7814432/33164797-b430b220-d034-11e7-93f2-7d659bfc0c68.png)
[supertuxkart-logcat-20171123.txt](https://github.com/supertuxkart/stk-code/files/1498465/supertuxkart-logcat-20171123.txt)

**Comment by Benau** [comment] 2017-11-23 09:48
Maybe we can use the vertex id workaround so no c++ code is needed...

**Comment by JORGETECH** [comment] 2017-11-27 00:17
I can confirm the same bug happening on my device (Huawei G6-U10) running Android 4.4.2. I haven't tried the adb workaround though but I'll do it and report back. It would be nice if this was fixed upstream with the Google Play version so the workaround is not needes.

**Comment by goberghen** [comment] 2018-01-02 15:43
Same bug on PC.
OS: Debian GNU/Linux Unstable x86
GPU: Nvidia GeForce GT 220 with nouveau driver
No models on «choose a kart» screen, no models on a race. `skinning.vert` workaround above doesn't work right — models on «choose a kart» screen are visible now, but their positions broken, models' parts are broken.

**Comment by Benau** [comment] 2018-01-02 16:51
that skinning.vert is specific for gles, and do you see any shader compiling error?

**Comment by goberghen** [comment] 2018-01-02 18:17
@Benau, no there were no error messages in the game.

**Comment by goberghen** [comment] 2018-01-04 11:05
BTW, `force_legacy_device="true"` in _config.xml_ helped, now I can see kart models.

**Comment by qwertychouskie** [comment] 2018-01-06 17:24
@goberghen What version of Mesa and the Linux kernel are you using?

**Comment by goberghen** [comment] 2018-01-08 09:26
@qwertychouskie, Mesa 17.3.1 and Linux 4.14.12-2.

**Comment by deveee** [comment] 2018-01-08 19:25
@goberghen I tried it on nvidia 635m with nouveau (mesa 17.0.7 from repos) and it works for me.

And btw @Benau your sp works with nouveau too.

**Comment by Benau** [comment] 2018-01-23 07:45
@goberghen  try this for skinning.vert?
```
#ifdef GL_ES
uniform mat4 ModelMatrix;
uniform mat4 InverseModelMatrix;
uniform vec2 texture_trans;
#else
uniform mat4 ModelMatrix =
    mat4(1., 0., 0., 0.,
         0., 1., 0., 0.,
         0., 0., 1., 0.,
         0., 0., 0., 1.);
uniform mat4 InverseModelMatrix =
    mat4(1., 0., 0., 0.,
         0., 1., 0., 0.,
         0., 0., 1., 0.,
         0., 0., 0., 1.);

uniform vec2 texture_trans = vec2(0., 0.);
#endif
uniform int skinning_offset;
#ifdef GL_ES
uniform sampler2D skinning_tex;
#else
uniform samplerBuffer skinning_tex;
#endif

#ifdef Explicit_Attrib_Location_Usable
layout(location = 0) in vec3 Position;
layout(location = 1) in vec3 Normal;
layout(location = 2) in vec4 Color;
layout(location = 3) in vec4 Data1;
layout(location = 4) in vec4 Data2;
layout(location = 5) in ivec4 Joint;
layout(location = 6) in vec4 Weight;
#else
in vec3 Position;
in vec3 Normal;
in vec4 Color;
in vec4 Data1;
in vec4 Data2;
in ivec4 Joint;
in vec4 Weight;
#endif

out vec3 nor;
out vec3 tangent;
out vec3 bitangent;
out vec2 uv;
out vec4 color;

#stk_include "utils/getworldmatrix.vert"

void main(void)
{
    mat4 TransposeInverseModelView =  transpose(InverseModelMatrix * InverseViewMatrix);
    vec4 idle_position = vec4(Position, 1.);
    vec4 idle_normal = vec4(Normal, 0.);
    vec4 idle_tangent = vec4(Data1.z, Data1.w, Data2.x, 0.);
    vec4 idle_bitangent = vec4(Data2.y, Data2.z, Data2.w, 0.);
    vec4 skinned_position = vec4(0.);
    vec4 skinned_normal = vec4(0.);
    vec4 skinned_tangent = vec4(0.);
    vec4 skinned_bitangent = vec4(0.);
    mat4 joint_matrix =
        Weight[0] * mat4(
        texelFetch(skinning_tex, clamp(Joint[0] + skinning_offset, 0, MAX_BONES) * 4),
        texelFetch(skinning_tex, clamp(Joint[0] + skinning_offset, 0, MAX_BONES) * 4 + 1),
        texelFetch(skinning_tex, clamp(Joint[0] + skinning_offset, 0, MAX_BONES) * 4 + 2),
        texelFetch(skinning_tex, clamp(Joint[0] + skinning_offset, 0, MAX_BONES) * 4 + 3)) +
        Weight[1] * mat4(
        texelFetch(skinning_tex, clamp(Joint[1] + skinning_offset, 0, MAX_BONES) * 4),
        texelFetch(skinning_tex, clamp(Joint[1] + skinning_offset, 0, MAX_BONES) * 4 + 1),
        texelFetch(skinning_tex, clamp(Joint[1] + skinning_offset, 0, MAX_BONES) * 4 + 2),
        texelFetch(skinning_tex, clamp(Joint[1] + skinning_offset, 0, MAX_BONES) * 4 + 3)) +
        Weight[2] * mat4(
        texelFetch(skinning_tex, clamp(Joint[2] + skinning_offset, 0, MAX_BONES) * 4),
        texelFetch(skinning_tex, clamp(Joint[2] + skinning_offset, 0, MAX_BONES) * 4 + 1),
        texelFetch(skinning_tex, clamp(Joint[2] + skinning_offset, 0, MAX_BONES) * 4 + 2),
        texelFetch(skinning_tex, clamp(Joint[2] + skinning_offset, 0, MAX_BONES) * 4 + 3)) +
        Weight[3] * mat4(
        texelFetch(skinning_tex, clamp(Joint[3] + skinning_offset, 0, MAX_BONES) * 4),
        texelFetch(skinning_tex, clamp(Joint[3] + skinning_offset, 0, MAX_BONES) * 4 + 1),
        texelFetch(skinning_tex, clamp(Joint[3] + skinning_offset, 0, MAX_BONES) * 4 + 2),
        texelFetch(skinning_tex, clamp(Joint[3] + skinning_offset, 0, MAX_BONES) * 4 + 3));
    skinned_position = joint_matrix * idle_position;
    skinned_normal = joint_matrix * idle_normal;
    skinned_tangent = joint_matrix * idle_tangent;
    skinned_bitangent = joint_matrix * idle_bitangent;

    gl_Position = ProjectionViewMatrix * ModelMatrix * skinned_position;
    // Keep orthogonality
    nor = (TransposeInverseModelView * skinned_normal).xyz;
    // Keep direction
    tangent = (ViewMatrix * ModelMatrix * skinned_tangent).xyz;
    bitangent = (ViewMatrix * ModelMatrix * skinned_bitangent).xyz;
    uv = vec2(Data1.x + texture_trans.x, Data1.y + texture_trans.y);
    color = Color.zyxw;
}
```

**Comment by goberghen** [comment] 2018-01-23 07:56
@Benau, no result.

**Comment by goberghen** [comment] 2018-01-23 08:16
First I'll try it on a clean system, maybe test it with nvidia driver, and then I'll compile git version if the problem persists.

**Comment by goberghen** [comment] 2018-01-23 08:19
Also, the output of `glxinfo | grep -i version`:
```
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
    Version: 17.3.3
    Max core profile version: 3.3
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.0
OpenGL core profile version string: 3.3 (Core Profile) Mesa 17.3.3
OpenGL core profile shading language version string: 3.30
OpenGL version string: 3.0 Mesa 17.3.3
OpenGL shading language version string: 1.30
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 17.3.3
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
```
Is it ok? I mean GLX and GLES versions, all that stuff.

**Comment by Benau** [comment] 2018-01-23 08:26
ok it meets the minimum requirement, don't worry

**Comment by Benau** [comment] 2018-02-02 16:36
https://github.com/supertuxkart/stk-code/commit/e3483fccbe4796fea67acb111c12ee16749cde88 I always unroll the loop now

**Comment by deveee** [comment] 2018-02-02 20:41
Ok, so now it should work on android 4.4 with qualcomm. I'm not sure what about @goberghen issue. Can you check if current git works for you?

**Comment by Benau** [comment] 2018-02-03 03:02
btw deve will you have the interests to make a stk-git in google play / somewhere so people can try git-android stk?

**Comment by Benau** [comment] 2018-02-05 05:57
apitrace:
kobato.stan.hk/stk.trace.lzma
(Recorded in GT240 in nouveau, I can perfectly replay it in my amdgpu)
seems that texture buffer object is not properly supported, I can use gles build fine there

**Comment by goberghen** [comment] 2018-02-05 12:50
Hmm, I tested the game on a fresh OS installation, with the same hardware, but with a different architecture (amd64 instead of i386). And it works fine, no bugs. So I temporarily withdraw my bug report,  because it seems that the problem is on my side.

**Comment by goberghen** [comment] 2018-02-06 19:15
>Maybe your new system used old mesa so it works
Seems so, because the "new" system is debian stable/testing and the "old" system (the one with a bug) is unstable.

**Comment by deveee** [comment] 2018-02-26 13:06
It should work on android now. I'm not sure what about nouveau. Do we want ```version=">= 12.34.56 && <= 34.56.78"``` in graphical restrictions?

**Comment by deveee** [comment] 2018-06-18 20:40
It's now possible to set min and max version in graphical restrictions, for example:
```
<card os="linux" version=">1.2.3" version2="<4.5.6" disable="ForceLegacyDevice"/>
```

@Benau Do you know a workaround for this bug? Actually I can try to reproduce it on laptop with newer nouveau...

**Comment by Benau** [comment] 2018-06-19 01:09
workaround for this bug is to disable hardware skinning

**Comment by deveee** [comment] 2018-06-21 21:05
@Benau It may be different bug, because version 17.1.4 works for me. But I can confirm that it's broken on mesa 17.3.3 with nouveau. I will check which versions are affected.

And btw. you need "--enable-texture-float" for core profile support.

**Comment by Benau** [comment] 2018-06-22 02:57
sorry deve no time to test nvidia (only after network), and in theroy if that regression is not fixed, all version after that commit should stop working

**Comment by deveee** [comment] 2018-06-22 06:14
@Benau Ok. Actually you were right and this commit simply didn't go to stable 17.1.x branch.

**Closed** 2018-06-22 22:00 UTC

**Comment by deveee** [comment] 2018-06-22 22:10
I disabled samplerBuffer in skinning for broken nouveau versions and use GLES method instead.

And I wonder if we really need two different methods, because there is not much difference between texture buffer and standard texture without mipmaps. Indeed texture buffer is more correct, but GLES way is more portable, so maybe keep only this one?

**Comment by Benau** [comment] 2018-06-22 22:39
Because without buffer streaming for bones when uploading it it may be slower
