### ISSUE TITLE
Framerate inconsistent depending on how game is started.

### ISSUE THREAD

**Issue by stkAnon** [supertuxkart/stk-code#1479] opened 2014-08-24 14:46 UTC
If test my arena with -R --track=addon_temple --laps=99 --numkarts=1 --kart=xfcemouse #--check-debug --track-debug, the framerate I get is around 8-10.

If I launch the game with those parameters, but exit to the menu and reenter the arena, the framerate I get is around 20.

If I launch the game without any parameters, the framerate I get is around 30.

Tested on 2a473a550a966e5b353200d51c28e35604d8ca50, due to https://github.com/supertuxkart/stk-code/issues/1477.

**Comment by deveee** [comment] 2015-11-18 11:43
I'm marking as duplicate of #2355 because there are a bit more information.

**Closed by deveee** 2015-11-18 11:43 UTC
