### ISSUE TITLE
Image scaling issue: STK Latest git

### ISSUE THREAD

**Issue by UnMe0w** [supertuxkart/stk-code#3702] opened 2019-01-12 19:55 UTC
## Description

Build STK on MacOS. Run it and add someone as friend. Your friend must be online. Relaunch STK and you will see the deformed logo.

## Configuration

STK release version: git

STK Source (PPA, distribution package, official binary, etc.): latest git compiled by myself

System: MacBook Pro 13 inch 2012 4 GiB DDR3 1600 MacOS High Sierra 10.13.4

Graphics card: Intel HD Graphics 4000 OpenGL 4.1

CPU: Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz

Gamepads/keyboards models if related to the issue: 

## Additional information

stdout.log:
```

[stdout.log.txt](https://github.com/supertuxkart/stk-code/files/2752429/stdout.log.txt)

```

input.xml:
```xml

```

Error message:
```

```

**Comment by KMe0w** [comment] 2019-01-13 09:34
https://streamable.com/lggt5

**Comment by KMe0w** [comment] 2019-01-13 10:01
https://streamable.com/ii12e

**Comment by auriamg** [comment] 2019-01-13 23:37
Here's a direct screenshot of the issue in case the original disappears
![image](https://user-images.githubusercontent.com/4296971/51092158-439b5d00-1762-11e9-937d-f04416e2e502.png)

**Comment by KMe0w** [comment] 2019-01-14 11:16
I think it's from apple's openGL headers because I got multiple warnings on VM and MacBook

**Comment by KMe0w** [comment] 2019-01-14 11:17
I will send my compile log on 2 weeks

**Comment by deveee** [comment] 2019-01-14 11:31
@KMe0w After your comment edit now it shows GL 4.1 rather than GL 2.0. Does it happen with GL 4.1 too?

It's probably unrelated to GL headers, because it sometimes happens for me too. But it happened for me only with GL 2.x.

**Comment by auriamg** [comment] 2019-01-15 00:03
One important thing to note is that Apple has not updated OpenGL in ages ( https://venturebeat.com/2018/06/06/apple-defends-end-of-opengl-as-mac-game-developers-threaten-to-leave/ ), which means macOS currently ships with an old buggy version of OpenGL that hasn't received bugfixes in a really long time... I'm not very surprised to see this kind of bug and we might have a hard time keeping stk running on mac with Apple not maintaining the tools we need.

A mac user would need to try debugging our graphics engine

**Comment by qwertychouskie** [comment] 2019-01-15 01:47
STK -> Zink -> MoltenVK -> Metal.  Ironically enough, this will probably give better performance than Apple's OpenGL drivers. :joy:

**Comment by theTomasPat** [comment] 2019-01-17 04:57
> A mac user would need to try debugging our graphics engine

I'm having this issue too. I'm also using a 2012 MacBook Pro 13 inch with very similar specs. I can help debug if someone tells me how.

**Comment by KMe0w** [comment] 2019-01-19 17:20
I think there's a Metal integration in Irrlicht. I found this post : http://irrlicht.sourceforge.net/forum/viewtopic.php?f=2&t=52296

**Comment by qwertychouskie** [comment] 2019-01-20 00:16
STK doesn't use Irrlicht's renderer except for ancient graphics cards that only support GL2.1/GLES2.

**Comment by deveee** [comment] 2019-02-12 21:37
It can be reproduced with
```
<card os="linux" disable="NpotTextures"/>
```
in graphical restrictions.

We should probably check if extension is available or opengl version >= min required, because it does such things on macos.

Typically it may happen only for legacy pipeline.

**Comment by deveee** [comment] 2019-02-13 22:56
Fixed in https://github.com/supertuxkart/stk-code/commit/ade94465b3d84851bf23d41159a30df35254839f

**Closed by deveee** 2019-02-13 22:56 UTC

**Comment by qwertychouskie** [comment] 2019-02-13 23:14
Hmm...  This problem exists using OpenGL 3, so not sure why NPOT texture support is an issue here.  Especially since NPOT support has been required since OpenGL 2.0: https://www.khronos.org/opengl/wiki/NPOT_Texture

We should really figure out why STK thinks it can't use NPOT textures on macOS, and figure out why the auto-resizing of textures isn't working on systems that don't support NPOT textures.

Or maybe just remove support for systems that can't handle NPOT textures altogether?

**Comment by qwertychouskie** [comment] 2019-02-13 23:22
Actually it seems using only POT textures can have slightly better performance: https://software.intel.com/en-us/articles/opengl-performance-tips-power-of-two-textures-have-better-performance

I wonder if forcing POT textures for Android could help with performance a bit?  Maybe I'll run some tests on my S5 to see if it helps.

**Comment by deveee** [comment] 2019-02-14 10:14
It's a problem with opengl on macos, which doesn't report some extensions that it supports. Or maybe it's our problem, because we check only extensions and not opengl version.
