### ISSUE TITLE
[UX] When you fail a challenge, the selection defaults to "Return to map" instead of "Restart"

### ISSUE THREAD

**Issue by kryptot7** [supertuxkart/stk-code#2988] opened 2017-10-29 17:06 UTC
Defaulting to restart makes more sense, because if you accidentally press it instead of "Go back", there's no load times and you can just press return to map from the pause menu. Also, it encourages players to try, try again (which is likely what they want to do anyway).

**Comment by Benau** [comment] 2017-10-29 17:27
could be fixed by 
        middle->setFocusForPlayer(PLAYER_ID_GAME_MASTER); instead of bottom ~220 result screen cpp

auria do you really care?

**Comment by auriamg** [comment] 2017-10-29 17:31
@Benau sure, it's easy and makes sense

**Closed** 2017-10-29 17:35 UTC

**Comment by psypherium** [comment] 2017-11-05 23:25
The opposite issue is also present. When you succeed a challenge, the selection defaults to "restart" instead of "return to map" Should I have made a new issue for this instead of commenting to a closed issue? I thought it was just too similar to warrant a new issue post.

**Comment by auriamg** [comment] 2017-11-05 23:46
@psypherium I cannot reproduce this issue on latest git, the correct button is highlighted by default for me

**Comment by psypherium** [comment] 2017-11-06 00:56
I realise what is happening now, If you succeed the same challenge a second time, the restart option comes back.
