### ISSUE TITLE
Snow Peak reverse model bug

### ISSUE THREAD

**Issue by Arthur-D** [supertuxkart/stk-code#2262] opened 2015-08-05 03:07 UTC
Latest master as of writing.
![snowtuxpeak-2015 08 05_04 49 33](https://cloud.githubusercontent.com/assets/5515261/9077552/ccc2f6d2-3b2f-11e5-8c9e-24238e364b05.jpg)

**Comment by auriamg** [comment] 2015-09-08 23:31
duplicate of #2129, which has just been fixed

**Closed by auriamg** 2015-09-08 23:31 UTC
Labels: C: 3D Modelling, P3: normal, T: defect
