### ISSUE TITLE
The Snap package of STK for Ubuntu no longer loads

### ISSUE THREAD

**Issue by Joust8bit** [supertuxkart/stk-code#4029] opened 2019-08-01 15:07 UTC
I recently downloaded the Snap package of STK for Ubuntu 19.04 Disco Dingo. This Snap contains the 1.0 version of STK.  It worked beautifully for about a week.  Then, without warning or error messages of any kind, STK failed to load upon launch.  You click the icon and nothing happens.  I thought it was the slow launching nature of most Snaps.  But after leaving it for 10 minutes, then rebooting my system and launching it again, it would still fail to launch.  I have 42 other Snap packages in my Ubuntu 19.04 desktop but none have exhibited any problems.  

I also noticed that this Snap of STK 1.0 was developed by someone named Daniel Llewellyn of "diddlensnaps"  

https://github.com/diddlesnaps/supertuxkart/blob/master/snap/snapcraft.yaml

I will be posting this issue to his Github site as well.

My system specs are as follows.

HP Pavilion Desktop
AMD Bristol Ridge APU A9800 - 4 Cores - 3.2Ghz
Radeon R7 class graphics - 8 cores
16GB Ram DDR-4 Ram Dual Channel
1TB Western Digital Hard Drive

**Comment by deveee** [comment] 2019-08-01 20:09
Snap package is unofficial and maintained by someone else. You can download linux package from sourceforge and it should work.

**Comment by Alayan-stk-2** [comment] 2019-10-24 09:40
Closing, as debugging snap-specific issues without indication that they stem from bugs in our code base is outside our scope.

If the snap maintainers find the cause of this issue and it's in our code base, they're welcome to open a new issue with relevant information to allow a fix.

**Closed by Alayan-stk-2** 2019-10-24 09:40 UTC
