### ISSUE TITLE
Laps counting bug

### ISSUE THREAD

**Issue by DarkStar1997** [supertuxkart/stk-code#3257] opened 2018-05-17 17:04 UTC
In the latest version, when I am ahead of the other AI karts by one lap or more and then meet them, my position drops to 20 again. I have experienced this issue in Bovine Barnyard for SuperTux mode with 19AI  karts.

**Comment by Benau** [comment] 2018-05-17 17:06
Bovine Barnyard is 0.9.2?

**Comment by DarkStar1997** [comment] 2018-05-17 17:09
0.9.3

**Comment by Alayan-stk-2** [comment] 2018-05-17 17:17
You missed a checkline somewhere by trying to take a big shortcut. When you finish the lap, it is not counted as valid as the checkline was missed, and your position drops.

Don't use the invalid shortcut, and your laps will be counted fine.

Otherwise, this track is unsupported, so it won't be made impossible to take those huge invalid shortcuts. Future versions also make your rank drop sooner than at the lap line when you miss a checkline (as soon as another kart reach the checkline you missed, he will be counted ahead).

**Comment by DarkStar1997** [comment] 2018-05-17 18:25
There are no shortcuts in this track. It's a simple, straightforward track. Anyway, I'll be more careful this time and if I face it again I'll share a screen recording of the issue.

**Comment by auriamg** [comment] 2018-05-18 02:06
Closing as can't reproduce, though it it happens again and you can provide information such as a screen capture, please reopen

**Closed by auriamg** 2018-05-18 02:06 UTC
