### ISSUE TITLE
Should not need to wait until power slide boost has ended before beginning another slide

### ISSUE THREAD

**Issue by OzoneOne** [supertuxkart/stk-code#2739] opened 2017-01-16 03:31 UTC
This is a significant gameplay issue for people who play arcade-style racing games by continuously sliding, even through straight areas. Having to wait for the delay between each slide makes the game feel unresponsive.

It also restricts control over the kart, as (for example) if you come up to a sharp corner and are already boosting, you are unable to begin another slide when needed and are likely to crash due to the game's controls.

**Comment by Flakebi** [comment] 2017-01-16 19:41
You only have to wait until the graphical boost times out (you are still driving faster afterwards for a while, the bonus lasts longer than the animation).

If you want to take sharp turns with skidding, you can press the skid key only short so the jump animation is playing and you are turning, but you don’t get a boost and you don’t have to wait until the boost animation finishes (you can jump the whole time).
I think it is kinda fair to only get the boost for some tradeoff (in this case you have to skid for a while until the boost turns on and you can't skid again until the boost animation finishes). Also you need a bit more skill because you have to plan in advance when you want to skid. :wink:

That said, I agree that the cooldown that appears when you skid a bit longer (even when you don’t get a boost) is sometimes confusing and it would feel better without it.

**Comment by OzoneOne** [comment] 2017-01-16 21:13
I can see your point about not necessarily needing to slide until you get a boost, but doesn't that defeat the purpose of having a tiered boost system? STK rewards you with different strengths of boost depending on how long you slide for, and I think that if you're an experienced player, you should be able to pull off of the first-tier boost fairly consistently. Surely that's why it's there; to act as a base-level reward for sliding. The second-tier boost requires sliding for a longer time and is harder to achieve, but has a bigger payoff, so I don't think the game will become any less balanced/fair.

**Comment by stkAnon** [comment] 2017-03-13 08:39
I quite liked this personally. Forces you to be tactical in skidding. Otherwise it'd be too easy to just slide constantly.

**Comment by qwertychouskie** [comment] 2018-06-26 21:34
The real problem here is https://github.com/supertuxkart/stk-code/issues/2487.  Once that is fixed this can probably be fixed without making things too easy.

**Closed** 2018-11-24 02:36 UTC
Labels: R: wontfix

**Comment by qwertychouskie** [comment] 2018-11-27 02:59
If the concern is that it's too easy to get the yellow boost, that needs to be fixed a different way.  This issue is about the skidding button being unresponsive.  When I was in this code a while ago, I found the cause: https://github.com/supertuxkart/stk-code/blob/1e178cdcf927e2dcdd01f09b4da798c447f35f7f/src/karts/skidding.cpp#L418

This is actually a FIXME in the code and should be fixed.  If too much skidding is really a problem, maybe allow skidding in SKID_SHOW_GFX, but don't increase the bonus timer when in this state?

I vote to re-open.
