### ISSUE TITLE
Clean out old branches

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#2583] opened 2016-07-26 01:15 UTC
There are many branches which have already been merged, and are now just cluttering the list.
List:
- [ ] 2360_fix_attempt
- [ ] dijkstra-test
- [ ] fix_2073
- [ ] gles
- [ ] legacy_opengl
- [ ] lensdust
- [ ] lensflare2
- [ ] new_server
- [ ] revert_improved_bloom

All these say "This branch is x commits behind master."

**Comment by konstin** [comment] 2016-08-07 00:00
Duplicate of #1293

**Comment by nado** [comment] 2016-08-09 12:18
Maybe close #1293 and keep this one since qwertychouskie already made a list ?

**Comment by konstin** [comment] 2016-08-09 21:30
It doesn't matter which one we close as the list isn't complete.

**Comment by nado** [comment] 2016-08-24 14:25
Also, it would be nice to get a proper tag for 0.9.1 and 0.9.2

**Closed** 2016-12-01 03:05 UTC
