### ISSUE TITLE
Crash in particles manager

### ISSUE THREAD

**Issue by auriamg** [supertuxkart/stk-code#3072] opened 2017-12-06 22:58 UTC
Reported on the forum

https://forum.freegamedev.net/viewtopic.php?f=17&t=7714&p=75215#p75215

```
Today I installed STK on my HP Probook 4530s. It crashes when I start any level with the message below.

Laptop specs:
Intel Core i5
AMD Radeon HD 7400M, 1GB GDDR
4 GB ram

---------------------------
SuperTuxKart crashed :/
---------------------------
SuperTuxKart crashed!
Please hit Ctrl+C to copy to clipboard and signal the problem
to the developers on our forum: viewforum.php?f=16

Call stack:

memmove
cpu_particle_manager.cpp:CPUParticleManager::uploadAll:223
draw_calls.cpp:DrawCalls::prepareDrawCalls:704
shader_based_renderer.cpp:ShaderBasedRenderer::renderScene:247
shader_based_renderer.cpp:ShaderBasedRenderer::render:822
irr_driver.cpp:IrrDriver::update:1796
main_loop.cpp:MainLoop::run:242
main.cpp:main:1805
exe_common.inl:__scrt_common_main_seh:283
BaseThreadInitThunk
RtlUserThreadStart
---------------------------
OK 
---------------------------

```

**Comment by deveee** [comment] 2017-12-06 23:04
I think that it's a duplicate of https://github.com/supertuxkart/stk-code/issues/3001

It's very rare, but sometimes happens.

**Comment by Benau** [comment] 2017-12-29 15:18
```
        // Check "real" particle buffer size in opengl
        if (m_gl_particles.at(p.first)->m_size < vbo_size)
        {
            m_gl_particles.at(p.first)->m_size = vbo_size * 2;
            m_particles_generated.at(p.first).reserve(vbo_size * 2);
            glBufferData(GL_ARRAY_BUFFER, vbo_size * 2 * 20,
                m_particles_generated.at(p.first).data(), GL_DYNAMIC_DRAW);
            glBindBuffer(GL_ARRAY_BUFFER, 0);
            continue;
        }
        void* ptr = glMapBufferRange(GL_ARRAY_BUFFER, 0, vbo_size * 20,
            GL_MAP_WRITE_BIT | GL_MAP_UNSYNCHRONIZED_BIT |
            GL_MAP_INVALIDATE_BUFFER_BIT);
        memcpy(ptr, m_particles_generated[p.first].data(), vbo_size * 20);
        glUnmapBuffer(GL_ARRAY_BUFFER);
        glBindBuffer(GL_ARRAY_BUFFER, 0);
```
This may work for some stupid drivers....

**Comment by Benau** [comment] 2018-01-13 07:50
Using the above (re bufferdata instead of map for resize) should fix the issue, please re-open if needed

**Closed by Benau** 2018-01-13 07:50 UTC
