### ISSUE TITLE
Music bug : another song played on top of the track song

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#2782] opened 2017-02-09 19:14 UTC
As the title say.

I don't know where the issue stems from, but I have the issue on the latest trunck ; while there wasn't a few days ago. So it must be a recent change which introduced this regression.

**Comment by deveee** [comment] 2017-02-09 20:06
Is this duplicate of https://github.com/supertuxkart/stk-code/issues/2169 ?

**Comment by Alayan-stk-2** [comment] 2017-02-09 20:18
Duplicate indeed. It's the same sound.

**Comment by deveee** [comment] 2017-02-09 20:23
Ok, so closing as duplicate

**Closed by deveee** 2017-02-09 20:23 UTC
