### ISSUE TITLE
Make all karts equal again

### ISSUE THREAD

**Issue by brmbrmcar** [supertuxkart/stk-code#2722] opened 2017-01-04 19:35 UTC
It may make the game less complex, but that seems like what you want. It is almost impossible to create tracks to make it fairer for all, so stop trying. And it is annoying in multiplayer if one player has a small advantage over the other.

**Comment by Arthur-D** [comment] 2017-01-04 19:38
This is a suggestion, not a bug, and a rather inflammatory worded one. Closing.

**Closed by Arthur-D** 2017-01-04 19:38 UTC
