### ISSUE TITLE
Can't resize screen

### ISSUE THREAD

**Issue by alexandrevicenzi** [supertuxkart/stk-code#1880] opened 2015-01-04 15:09 UTC
I can't resize screen. Some buttons are missing.

![captura de tela de 2015-01-04 13 03 48](https://cloud.githubusercontent.com/assets/2637672/5606360/de5c61b8-9412-11e4-9e12-a89636c64a8b.png)

![captura de tela de 2015-01-04 13 03 38](https://cloud.githubusercontent.com/assets/2637672/5606361/de6124e6-9412-11e4-8f59-513c7ebc2e5c.png)

**Comment by deveee** [comment] 2015-01-04 15:21
STK uses non-resizable window by design :) You can change window size in properties or you can modify config.xml file if you want to set custom window size.

I was experimenting with resizable window, but it's not that easy atm. because some gui elements are remembered for previously specified resolution.

I leave it open because I'd like to have this feature in STK too.

**Comment by alexandrevicenzi** [comment] 2015-01-05 00:26
OK, I will take a look.

**Comment by fathulkirom22** [comment] 2018-02-15 17:02
i have same problem, how can i find file config.xml?

**Comment by qwertychouskie** [comment] 2018-02-15 17:52
@fathulkirom22 It is in `.config/supertuxkart/0.8.2/`, though in most cases you can just go into the game's settings and pick a resolution:

![](http://i.imgur.com/l7X4oYd.png)

**Comment by auriamg** [comment] 2018-02-18 23:41
Ideally we should prevent picking a resolution larger than the current screen size, that may be a bit hard to do in all cases due to multi-platform issues, multi-monitor setups, etc.

**Comment by Benau** [comment] 2020-06-03 20:32
not sure stk fans mind only resizing screen in main menu and options screen! (or auria / alayan!)

**Comment by 7wells** [comment] 2020-06-04 05:21
STK (git from May) shows only one resolution (1920x1080) on Fire TV stick 4K, whereas there are multiple possible resolutions and a toggle to de/activate full screen on Windows 10. In the latter case, the maximum offered STK resolution is the maximum resolution (or currently set OS resolution?) on the PC, correct?

**Comment by Benau** [comment] 2020-06-04 05:30
because mobile stk support only 1 resolution...
![](https://stk.kein.hk/hkpig/tgs20.gif)

**Comment by Benau** [comment] 2020-06-04 11:56
Not sure deve can ![](https://cdn.lihkg.com/assets/faces/pig/cook.gif) benau/master if it works for him so stk fans ![](https://cdn.lihkg.com/assets/faces/pig/dance.gif)

**Comment by Benau** [comment] 2020-06-11 19:55
now resizing is possible in game or main menu or first 2 option screens and no dialog open

unless auria has mood to make it possible to live change gui element size I think we can close it (now it's reset screen stack when screen size changed)

**Closed by Benau** 2020-06-11 19:55 UTC
Labels: T: task
