### ISSUE TITLE
I18N: Input methods not supported

### ISSUE THREAD

**Issue by Vdragon** [supertuxkart/stk-code#2112] opened 2015-04-24 11:47 UTC
Hi SuperTuxKart developers, 
please support input methods so that user can input CJK characters(for example, display name)

**Comment by hiker** [comment] 2015-08-23 03:09
It appears that some non-ascii characters work (special Norwegian characters), but others don't. it would be good if someone with a keyboard with special keys on them could debug it.

**Comment by Vdragon** [comment] 2015-08-23 15:22
@hiker Hi please checkout the following tutorial on CJK input issues
<https://docs.google.com/document/d/1HB3juffu0KgSUyg15y8hBZOLcJdHK9KDVPFyCwqHh-I/edit>

**Comment by hiker** [comment] 2015-08-24 08:10
Hmm - I just realised that we actually can not support CJK - the issue is that we have to restrict the number of characters that can be used (otherwise the textures are too big), so we only have the symbols available that are already used elsewhere in S'TK - not to useful for typing names I'd guess.

Changing this would be a significant effort (either adding support for ttf rendering or so), or even 'just' the ability to add missing characters 'on the fly to the textures used) is not trivial, I can't see us finding time for this in the near future - though patches are welcome :)  (though be aware that just converting all Chinese characters into the font textures will not work, since most graphics card will run out of texture space)

**Comment by Benau** [comment] 2015-10-16 18:52
https://github.com/Benau/stk-code/commit/a756f9f90e0d0406cdcf85e017984ffe56936f9a

Now lazy loading characters (on the fly loading) is implemented, @Vdragon do you know how to get stk to integrate with ibus/any input methods?

**Comment by Vdragon** [comment] 2015-10-17 04:10
@Benau Sorry, I have no idea how to do that.

**Comment by Benau** [comment] 2015-10-26 18:14
https://github.com/Benau/stk-code/commit/a20be892b82c39fdfed5dd8dcc809b979e2e2fd4
The above is mainly patched from official irrlicht svn and here: http://irrlicht.sourceforge.net/forum/viewtopic.php?f=6&t=6513&sid=38480dd2a5561c4584a747d3a988a4da&start=60

![ex](https://cloud.githubusercontent.com/assets/3252341/10737691/90449cbe-7c4e-11e5-86df-792199399a18.jpg)

![2015-10-27 01-59-45](https://cloud.githubusercontent.com/assets/3252341/10737658/6bb3283e-7c4e-11e5-9502-3e1650ec8bea.png)

Now you can type CJK in windows...
Ask some genius to do the same for linux/mac....

---------
Limitation:
No ime box is shown in fullscreen

(Windows)Only the used language in current setting of non-Unicode programs can type with its supported IME, as in the screenshot above, korean (韓國) is chosen so only typing using IME with korean is possible. I THINK(??) it can be get rid of by compiling irrlicht with UTF mode instead of Multi-byte char mode in VS, and change:

MultiByteToWideChar(CP_OEMCP, MB_PRECOMPOSED, bits, 2, &event.InputMethodEvent.Char, 1);

to

event.InputMethodEvent.Char = (wchar_t)wParam; (which is the official patch does)

But lots of compiling errors coming....

This may explain why #1591 can't show correct characters too.

Is the patch too "complicated" to test/merge?

**Comment by Benau** [comment] 2016-11-09 04:31
@Vdragon can you try this branch in your linux?
![screenshot](https://cloud.githubusercontent.com/assets/3252341/20127330/608edf90-a635-11e6-8bd7-44d1391f11a1.jpg)
In my gnome-shell testing, it works

**Comment by Vdragon** [comment] 2016-11-10 16:22
@Benau Looking at it, thanks for helping.

**Comment by Vdragon** [comment] 2016-11-12 17:12
@Benau Hi, I've build & tested, however the input method framework can't be activated in SuperTuxKart, I'm using Ubuntu's default IMF Fcitx in a KDE session.

Also if I pasted Chinese characters into the program it is displayed as question marks:
![supertuxkart_067](https://cloud.githubusercontent.com/assets/1192163/20239562/304501c8-a93e-11e6-8e1b-bf3abd6cb05d.png)

**Comment by Vdragon** [comment] 2016-11-12 17:16
Also for commit d166aa6 I would like to suggest using Adobe Source Han Sans region-specific font instead of wqy, which is following GB18030 chinese writing/stroke standard and is different with the Taiwan/HongKong standard.

**Comment by Benau** [comment] 2016-11-13 01:10
https://github.com/supertuxkart/stk-code/commit/a72f67015ca57016127a8f22b8e371a37a0ab899

Because it's too large (36MB), sorry

And for your problem, let me try to reproduce

**Comment by Benau** [comment] 2016-11-13 03:02
Using lastest kubuntu 16.04, it's working for me

![screenshot_20161113_105806](https://cloud.githubusercontent.com/assets/3252341/20243383/3cdf024c-a990-11e6-9f67-ae8dc1e893fd.jpeg)

Are you using unicode locale (shown in screenshot)? if you start linux with LANG=C, stk can't open IM

Regarding paste chinese issue, seems that currently it will only work if the target application is not using gtk/qt (which have their own clipboard), last time I tried I can paste chinese from libreoffice only :/

**Comment by Benau** [comment] 2016-11-13 03:12
Also if you start stk in terminal, don't use sudo / su - root (use the same login user), otherwise IMF won't open also

**Comment by Vdragon** [comment] 2016-11-13 06:06
> Are you using unicode locale (shown in screenshot)? if you start linux with LANG=C, stk can't open IM

```
$ locale
LANG=zh_TW.UTF-8
LANGUAGE=zh_TW:zh_HK:zh
LC_CTYPE="zh_TW.UTF-8"
LC_NUMERIC="zh_TW.UTF-8"
LC_TIME="zh_TW.UTF-8"
LC_COLLATE="zh_TW.UTF-8"
LC_MONETARY="zh_TW.UTF-8"
LC_MESSAGES="zh_TW.UTF-8"
LC_PAPER="zh_TW.UTF-8"
LC_NAME="zh_TW.UTF-8"
LC_ADDRESS="zh_TW.UTF-8"
LC_TELEPHONE="zh_TW.UTF-8"
LC_MEASUREMENT="zh_TW.UTF-8"
LC_IDENTIFICATION="zh_TW.UTF-8"
LC_ALL=
```

> which version you are using?
I'm using Ubuntu 16.04 with KDE installed separately, running /usr/local/bin/supertuxkart from the termnal

```
$ printenv | grep fcitx
QT_IM_MODULE=fcitx
XMODIFIERS=@im=fcitx
QT4_IM_MODULE=fcitx
GTK_IM_MODULE=fcitx
```

**Comment by Vdragon** [comment] 2016-11-13 06:11
Oops, I made a big mistake by cloning the official repo instead of the patch's, please ignore the previous test result as I'm doing the new one.

**Comment by Benau** [comment] 2016-11-13 06:12
ok

**Comment by Benau** [comment] 2016-11-13 06:13
I think I can fix the "?????" pasting chinese issue too, give me some time

**Comment by Vdragon** [comment] 2016-11-13 06:50
I can successfully input Chinese after using the right revision of STK, sorry for all the trouble.

![_070](https://cloud.githubusercontent.com/assets/1192163/20244140/55f024da-a9b0-11e6-84fe-d2732cdc87f2.png)

I still can't paste properly paste Chinese text from LibreOffice though, but it should be other issue.

**Comment by Benau** [comment] 2016-11-13 08:13
https://github.com/supertuxkart/stk-code/commit/e6e302af1cd7e127855845dca48dc84f2d7747e8

@Vdragon can you try again? (it's in the same branch, just do git pull should work)

**Comment by Benau** [comment] 2016-11-14 00:12
Notice: all chinese related commits merged into master, so just do git checkout master; git pull should work

I'm closing this now, feel free to tell me if you have any problems later

**Closed by Benau** 2016-11-14 00:12 UTC

**Comment by Vdragon** [comment] 2016-11-14 15:17
Hi, the pasting issue is resolved in the new revision of STK.

**Comment by Benau** [comment] 2016-11-14 15:32
Thx for your confirmation!
