### ISSUE TITLE
shifting sands skybox doesent look correct

### ISSUE THREAD

**Issue by tobyplowy** [supertuxkart/stk-code#2986] opened 2017-10-29 13:11 UTC
![sandtrack-2017 10 29_13 54 02](https://user-images.githubusercontent.com/16853304/32143977-219d5aa2-bcb2-11e7-837d-f10252ba3ad4.png)
you can clearly see the seams of the skybox top texture in shifting sands
this is visible if you go in one of the 2 temples and if you get hit with a bomb (aka cake)
it happens at all sides not only the side of the temple

this is also present on the android version of the game

this really needs to be fixed becouse it subtracts from the qwallity of the game 
(bdw nice work with this game)

**Comment by Benau** [comment] 2017-10-29 13:27
It's a duplicate of #2128

**Closed by Benau** 2017-10-29 13:27 UTC
