### ISSUE TITLE
Panel flickering, freezes and massive FPS drop

### ISSUE THREAD

**Issue by ghost** [supertuxkart/stk-code#3136] opened 2018-03-14 12:04 UTC
## Description

Playing the battle mode, there are some flickering on the top gray panels, freezes and FPS drop:

## Steps to reproduce
This battle map, some gray panels on the top are flickering.
![1panel](https://user-images.githubusercontent.com/34775187/37400453-c14a6a2e-2763-11e8-96c9-e4bbd9055e3a.png)
![2panel](https://user-images.githubusercontent.com/34775187/37400462-c82d80d8-2763-11e8-95cb-124a25ab97a7.png)

Also, I experienced 2 freezes for a few seconds and a massive FPS drop(went from 60 to 5) on this spot below, I was accelerating and moving using the arrow keys:
![3freeze_fpsdrop](https://user-images.githubusercontent.com/34775187/37400539-0176848e-2764-11e8-99fe-4dd60ea9cf25.png)

## Configuration
Quality 2
Fullscreen
VSync enabled

STK release version:
Version: 0.9.3-1

STK Source (ppa, distribution package, official bin,...):
`gnome-software`

System: 
```
Ubuntu 18.04 bionic (dev branch)
Kernel: x86_64 Linux 4.15.0-10-generic
Desktop: Gnome 3.27.92

CPU:       Dual core Intel Core i5-2410M (-MT-MCP-) 
           arch: Sandy Bridge rev.7 cache: 3072 KB
           flags: (lm nx sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx) bmips: 9179
           clock speeds: min/max: 800/2900 MHz 1: 801 MHz 2: 800 MHz
           3: 801 MHz 4: 805 MHz
Graphics:  Card: Intel 2nd Generation Core Integrated Graphics Controller
           bus-ID: 00:02.0 chip-ID: 8086:0116
           Display Server: x11 (X.Org 1.19.6 ) driver: i915
           Resolution: 1366x768@59.97hz
           OpenGL: renderer: Mesa DRI Intel Sandybridge Mobile
           version: 3.3 Mesa 18.0.0-rc4 (compat-v: 3.0) Direct Render: Yes
```
GPU: Intel HD Graphics 3000

log
[stdout.log](https://github.com/supertuxkart/stk-code/files/1810919/stdout.log)

**Comment by ssspacez** [comment] 2018-03-15 08:45
More info about the "panel" flickering/glitching: https://github.com/supertuxkart/stk-code/issues/3137

**Comment by qwertychouskie** [comment] 2023-04-04 03:42
Unable to reproduce (likely driver bug with that particular old version of Mesa on that specific hardware).  Issue should be closed, as reporter is no longer around to test with newer driver/STK versions.  Also issue is basically dupe of https://github.com/supertuxkart/stk-code/issues/3137

**Comment by Alayan-stk-2** [comment] 2024-04-25 20:56
Closing, see qwerty's comment.

**Closed by Alayan-stk-2** 2024-04-25 20:56 UTC
Labels: R:not our bug
