### ISSUE TITLE
Some extension characters are looking weird

### ISSUE THREAD

**Issue by utybo** [supertuxkart/stk-code#2012] opened 2015-02-28 13:35 UTC
They have texture problems and model problems (transparent parts). Happens in the game and in the character selection preview. This does not happen with the current stable release, only with the beta.
http://puu.sh/ggjGZ/57a7a17a30.jpg

(EDIT : Wrong screenshot, fixed)

**Comment by samuncle** [comment] 2015-02-28 17:58
It's most likely because the file format has changed. The beta uses a slightly different file format.

Currently the beta "still" support the old addons but it's planned to remove this support for the release candidate and the final version.

**Comment by hiker** [comment] 2015-03-01 21:04
Duplicate of #1784 basically, so closing this one.
The models need to be re-exported with a recent version of the exporter (and potentially the darkness of the texture needs to be adjusted to the new engine).

Thanks for the report!
   Joerg

**Closed by hiker** 2015-03-01 21:04 UTC
