### ISSUE TITLE
Gran Paradisio invisible solide mesh

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#2781] opened 2017-02-08 14:28 UTC
See screenshoot.

![tuxbug2b](https://cloud.githubusercontent.com/assets/25536748/22741334/2b71ca0e-ee13-11e6-8229-15bcb6fb4d8b.png)

**Comment by MTres19** [comment] 2017-02-09 01:24
Strange. I could not reproduce the problem. (Assets r16997)

**Comment by samuncle** [comment] 2017-02-12 01:08
Idem I can't reproduce it :( even with the physic visualization I have no issues

**Comment by qwertychouskie** [comment] 2017-09-20 02:03
Was able to reproduce: https://drive.google.com/open?id=0BzjStY528QA4eEFiNjVqZklwcHM

**Comment by MTres19** [comment] 2017-09-23 00:29
Does this only cause problems at the edges of the track? If so, I think I've fixed it in r17260.

**Comment by qwertychouskie** [comment] 2017-09-23 00:45
I think so.

**Comment by auriamg** [comment] 2017-09-24 00:14
Fixed by MTres19, thanks

**Closed by auriamg** 2017-09-24 00:14 UTC
Labels: R: worksforme
