### ISSUE TITLE
Make these tux, medals and clocks scale bigger in higher resolution

### ISSUE THREAD

**Issue by dumaosen** [supertuxkart/stk-code#3792] opened 2019-03-04 11:14 UTC
![_ _20190304191015](https://user-images.githubusercontent.com/35170687/53730004-aa5f0c00-3eb1-11e9-86b2-1bfe372c08e4.png)
![_ _20190304191043](https://user-images.githubusercontent.com/35170687/53730005-aa5f0c00-3eb1-11e9-9de7-22e0732b9b49.png)
![_ _20190304191322](https://user-images.githubusercontent.com/35170687/53730011-ac28cf80-3eb1-11e9-9547-49dac010410b.png)

**Comment by Alayan-stk-2** [comment] 2019-03-04 17:13
Mmmm. isn't this a duplicate of #3682 ? These are just particular examples ?

**Comment by dumaosen** [comment] 2019-03-06 13:50
Yes but all icons are fixed except these.

**Comment by qwertychouskie** [comment] 2019-05-16 23:15
@dumaosen Is this fixed or is it still an issue?

**Comment by dumaosen** [comment] 2019-05-18 02:01
> @dumaosen Is this fixed or is it still an issue?

Still an issue

**Closed** 2019-06-08 20:01 UTC
Labels: C:GUI, P3: normal, T: enhancement

**Comment by Staszek2312** [comment] 2019-06-08 21:24
photokrzys
