### ISSUE TITLE
New physics engine causes a little too much bounciness near the end of snow peak

### ISSUE THREAD

**Issue by psypherium** [supertuxkart/stk-code#3353] opened 2018-07-27 15:17 UTC
New physics engine causes a little too much bounciness near the end of snow peak

You will sometimes fall straight off the track

**Comment by auriamg** [comment] 2018-07-28 01:20
a video capture would help a lot so we know exactly where/how

**Comment by psypherium** [comment] 2018-07-28 11:32
https://youtu.be/gAlW_lv77aU?t=27 quality will improve in an hour or two when youtube finishes processing

**Comment by auriamg** [comment] 2018-07-29 22:21
Which version of STK is this? I just tried a few times using latest git version but was unable to reproduce this issue

**Comment by psypherium** [comment] 2018-07-29 23:51
git

**Comment by Alayan-stk-2** [comment] 2018-07-30 14:48
I can reproduce the issue in Snow Peak at the spot shown in the video.

**Comment by hiker** [comment] 2018-07-31 06:53
I will try to reproduce the issue, but tbh, I am very certain that this is more a track design problem. What (very likely) happens is:

the kart is too fast to stay on the track, so it starts flying forwards with high speed. At the same time it starts falling. After a while, the downward speed increases, till it falls fast enough to hit the ground - at which time it would very likely crash, which is bad in terms of game design ;)

So at this stage either because our extremely long suspensions kick in, or because we detect the upcoming crash after a fall and slow the vertical speed down to avoid the crash, the kart's downward speed is reduced (to close to 0). But the forward speed is still there - so the same thing happens again: the kart will move forward fast, starts flying, till the downward speed (gravity) is high enough for it to hit the track, ... and repeat.

So, there are a few options:
1) We could accept a crash. This might cause the kart to suddenly rotate (if one side/edge hits the ground first); and certainly to slow down - which is not fun at all :). And the kart will certainly slow quite abruptly - which isn't fun either.
2) We could artificially slow down the forward speed as well when we slow down the downward speed - while we avoid the crash compared with 1) above, it is still not fun to suddenly see the kart slowing down.
3) We modify the track to work as expected ... which would be either:
   - keep the kart connected to the track (so the track should start with a gentler slope, which then increases as the kart accumulates more gravity induced falling speed). This way the karts should be able to drive, which sounds fine;   or
   - make the kart even steeper, with a flatter landing area. This way the kart would clearly fly, and only on the landing area becomes controllable again - which sounds fine as well.

So imho track modifications is the way to go - what would be better? I don't know ;) Esp. considering being able to go in reverse, i.e. up the hill :)

**Comment by Alayan-stk-2** [comment] 2018-07-31 23:27
I don't agree it's a track issue.

The core issue here is quite clear : assuming that 0 is the good vertical speed to slow down to is wrong when there is a slope.

**Comment by auriamg** [comment] 2018-08-01 01:19
Fixed in svn with track changes

**Closed by auriamg** 2018-08-01 01:19 UTC
