### ISSUE TITLE
Volume control not available until registration complete

### ISSUE THREAD

**Issue by auriamg** [supertuxkart/stk-code#3553] opened 2018-11-12 23:12 UTC
Reported on the forum:

I just started up STK while watching Netflix. The music is very loud, and there is no option to turn it down. I signed up and tried to log in to get to the mute/volume buttons, but even after signing up I had to verify an email address first. All the while, no volume control. My suggestion is that the starting music either be very quiet or volume control be immediately presented. I ended up closing the program on my first use before even getting past the login prompt.

**Comment by Alayan-stk-2** [comment] 2018-11-12 23:19
Can't people use their operating system volume control to silence the program during that phase ?

Also, an online account is not required at all to proceed, creating a local account just require typing a name, validating, and the options menu with sound control becomes immediately available. Of course, it requires being able to see that there is a local account option.

I'm of the opinion to close this as a won't fix.

**Comment by auriamg** [comment] 2018-11-12 23:42
@Alayan-stk-2 the operating system volume control is weak since there may be something else playing on the computer that shouldn't be muted. Maybe the proper fix is a just a clearer UI so that players who want to skip account creation have an easier way of finding it, I guess that's actually the main issue here

**Comment by Alayan-stk-2** [comment] 2018-11-12 23:49
On windows and linux, I can control sound volume per application, that's what I meant here. (Actually, on my linux, I can only control it per application).

I don't disagree about making it more obvious that creating an online account is not required, however. How would you go about it ? iirc, we have 3 tabs at the top with what they do indicated in their name, and the online account tab selected by default.

**Comment by Wuzzy2** [comment] 2018-11-13 00:32
The problem is, STK forces you to create at least one account (offline or online) before you are allowed to access the settings.

I agree it's only a minor problem, however.

**Comment by Arthur-D** [comment] 2018-11-13 01:28
I'd say just setting the default in-game volume lower would be a quick and good fix. It's really loud at the moment compared to all other applications.

**Comment by Alayan-stk-2** [comment] 2018-11-13 01:32
Good point, I don't see why the in-game volume has to be maxed out as a default. Something like 7/7 would be more balanced.

**Comment by hiker** [comment] 2018-11-13 02:00
I agree with lowering the default. Also (technically), you can of course create the account later (just select a local account), but that's indeed not obvious. Alternatively, we only start music after a potential account window? Or play it very very quietly, and then go to default after account?

**Closed** 2018-11-13 20:37 UTC
Labels: C:Audio, P5: trivial

**Comment by Alayan-stk-2** [comment] 2018-11-13 20:49
To test the lowering of the default sound, I removed my previous profile data and got the standard account creation procedure.

It appears that the prompt about internet access and data collection decides what happens next : "yes" will put the online account tab as the default tab, "no" will put the offline account as the default tab.

This is actually quite reasonable.

The "offline account" tab is quite visible if one just look around.

The available options are : 
- Make the local account the default option in all cases. The downside is that an online account will have to be created later if the user wants to use it, and STK doesn't support creating a new online account on the base of a current offline account (having to create a different local account, then reusing the online credentials for the main local account : this is a real case of poor usability).
- Annoy the user with some distracting alert to make it known the offline account option. Whatever the way chosen to do this, I think it's not worth it. 
- Consider that the current setup is good enough.
