### ISSUE TITLE
Support last lap music

### ISSUE THREAD

**Issue by samuncle** [supertuxkart/stk-code#1613] opened 2014-10-10 12:19 UTC
In next gen track I'm trying to have a last lap music that is more stressful. 

Here is the original topic
http://forum.freegamedev.net/viewtopic.php?f=17&t=5872&sid=79a09538475615f54f829425258719c2&start=25

When the last lap is trigged, the alternate soundtrack should be played.

**Comment by hiker** [comment] 2015-02-05 04:29
@samuncle can you test again? I did a lot of work, and just fixed a bug in the last lap handling, though I am not sure if this is related to the flooding messages.

**Comment by Flakebi** [comment] 2015-02-05 14:31
I get only one error:
`[error  ] SFXManager: SFXOpenAL OpenAL error while positioning: AL_INVALID_NAME`
But I'm not sure if the last lap music works now, the music gets louder for a few second after passing the start line but after that the volume is much lower than normally (and I think it's the same music as before, though I don't know if it should be replaced).

**Comment by Flakebi** [comment] 2015-02-05 21:54
Ok, the previous comment was when I had sounds enabled, with sounds disabled there are more errors:
I get many `[warn   ] MusicOgg: Music not playing when it should be. Source state: 4116` warnings after some time, the music stops (or lags) until I begin the last lap (in chocolate) and the last lap music is played. The last lap music is played better than with sounds enabled, so it's staying loud, but there are still many lags and after I reached the wooden bridge, it stopped too.

Because the music stops when I reach the bridge, I'm quite sure it has something to do with sound effects as there is one, when you're racing over the wooden bridge. Activating a zipper item doesn't trigger the error, but racing over a zipper in the map does sometimes.
The easiest way to reproduce it, is dropping a bowling ball and driving into it.

**Comment by samuncle** [comment] 2015-02-11 01:34
with the last version of the master. When I do a race with 3 laps, after the second lap, the music just stop :(

I got 
[warn   ] MusicOgg: Music not playing when it should be. Source state: 4116

spammed on the terminal

**Comment by hiker** [comment] 2015-02-14 14:31
@samuncle - my understanding is that this is now fixed for you. If not, please reopen.

**Closed by hiker** 2015-02-14 14:31 UTC
Labels: P3: normal, T: task
