### ISSUE TITLE
Karts in mid-jump are eliminated from Follow The Leader

### ISSUE THREAD

**Issue by slicer69** [supertuxkart/stk-code#4517] opened 2021-04-09 19:11 UTC
## Description

Problem: When a kart is in mid-jump in a Follow The Leader competition, the kart is eliminated, regardless of their position in the race.

## Steps to reproduce

1. Start a Follow The Leader competition with multiple AI-controlled karts. 
2. Select Cornfield Crossing track as the race location.
3. On the opening lap, move into the middle of the pack and hit the jump into the barn when the elimination timer reaches zero.
4. The player is removed, regardless of their position in the field. possibly because they are not technical on the track.

## Configuration

STK release version:  1.0

STK Source (PPA, distribution package, official binary, etc.): Debian Stable repository.

System: Linux (x86_64)

Graphics card: AMD Radeon HD 6410D

CPU: Dual-core 2.8GHz AMD 64-bit

**Comment by PANCHO7532** [comment] 2021-04-09 20:38
Probably a duplicate of #4356 
But couldn't replicate the issue on the 1.2 release, the player is removed while is in the air and the timer reaches zero? Or when reaches zero and it's inside the barn?

**Comment by slicer69** [comment] 2021-04-09 20:58
The player is eliminated when the timer reaches zero and the player's kart is still in the air.

I've noticed during the victory lap after a race that karts get "stuck" at the jump and cannot proceed into the barn. Which makes me think the jump is sort of "outside" the track in some way.

**Comment by Alayan-stk-2** [comment] 2021-09-08 13:21
Actually this is a duplicate of #4356 

Closing this, use the other issue for further discussion.

**Closed by Alayan-stk-2** 2021-09-08 13:21 UTC
Labels: T: defect, P4: minor, C: Race Events
