### ISSUE TITLE
Shaky Tires under certain circumstances.

### ISSUE THREAD

**Issue by psypherium** [supertuxkart/stk-code#3051] opened 2017-11-18 09:58 UTC
Since 0.9.3, tires can shake about and look really weird sometimes. To my knowledge it happens on every graphics setting.

https://youtu.be/i0C0rTOxmZo

60 fps does not do justice to how shaky it is. Edit: 60 fps footage will very rarely capture it when recording from a near-144fps source, it must happen for exactly one frame.

**Comment by Benau** [comment] 2017-11-18 11:07
In official arch linux + kernel and latest release mesa?

**Comment by psypherium** [comment] 2017-11-18 11:13
All standard software, booted into regular kernel.

**Comment by Benau** [comment] 2017-11-18 12:26
From your other 0.9.3 videos, i don't see such shaking, so i wonder if it's happening only recently for you.... (after system upgrade?)

**Comment by psypherium** [comment] 2017-11-18 12:30
I just did some testing, it actually only happens on graphics setting 2 and 1.

**Comment by tobyplowy** [comment] 2017-11-19 23:06
i also get this every time i start a race 

i use windows 10 and SuperTuxKart version 0.9.3-rc1

**Comment by hiker** [comment] 2018-02-28 23:38
I believe this problem is caused by getting a dt (time step size) of 0, which is more likely to happen at higher frame rates (dt is measured in ms, so dt<1 would be less than 1 ms - but this is also affect by the clock resolution).
I could not reproduce the problem, even though I was running at >180 FPS.
Benau, can you reproduce this issue, and if so check if indeed dt=0. Best way probably: 
- go to kart_model.cpp, line 1042: "pos.Y +=   m_default_physics_suspension[i] ..."
- before that line add: if (suspension_length<0.001) Log::verbose("testdt=0", "susplen %f dt %f", suspension_length, dt)
- reproduce the issue, then check the log file for the testdt lines and see if susplen is very small (likely 0) and dt=).

If this can be confirmed I can port a patch for that from the network branch.

**Comment by Benau** [comment] 2018-04-06 13:03
With fix timestep in stk for network i no longer see this

maybe you can retry when all network branches are merged....
....though no more speedrun shortcut........
.....but in exchange you can play in network later.....

**Comment by hiker** [comment] 2018-04-19 09:35
@Benau can you check 8c420d68d and see if this is fixed? I am not sure why dt!=0 was in there, with the test (even after initialising suspension_length) the tires still did not move smoothly, while now it appears to work fine even with high fps.

**Comment by Benau** [comment] 2018-04-19 16:46
Yes it is fixed

**Closed** 2018-04-20 05:59 UTC
