### ISSUE TITLE
Control configuration

### ISSUE THREAD

**Issue by ghost** [supertuxkart/stk-code#2872] opened 2017-06-28 14:56 UTC
I use an Xbox 360 controller to play Super Tux Kart 0.9.2 and these are the game keys I would like to use:

Steer left - LS Left, Steer right - LS Right, **Accelerate - RT**, Brake - Y, Fire - B, Nitro - A, Skidding - LB, **Look back - LT**, Rescue - X and Pause Game - Start.

However, whenever I try and use both RT and LT, the two cancel out and my character comes to a stop. I'm not a huge fan on the standard controls; is there any way this issue can be resolved in 0.9.3?

**Comment by auriamg** [comment] 2017-06-29 22:37
Does anyone have an xbox gamepad to test with? With my own gamepad (logitech), I cannot reproduce this kind of issue, everything works fine for me

**Comment by cap44** [comment] 2017-07-07 17:33
I use an Xbox One controller, and I can verify that RT and LT cancel each other, 
@auriamg what input library does stk use?

**Comment by auriamg** [comment] 2017-07-08 00:31
Also, you didn't say on which OS you are.

STK input is processed by irrlicht, though we may have modified that code

**Comment by hiker** [comment] 2017-07-30 14:31
Confirmed - but I am not sure what we can do about it:
the two triggers are reported in irrlicht on one axis: if both are pressed, we receive this state as 'axis 2 = 0' - same as if no buttons are pressed :(
See https://en.sfml-dev.org/forums/index.php?topic=11933.0:
" it's just that triggers are merged into a single axis instead of being two separate axes."
Apparently the solution would be to use XInput, which apparently can distinguish the two triggers (but is an xbox controller only api). :
https://msdn.microsoft.com/en-us/library/windows/desktop/ee417014(v=vs.85).aspx:
" However, some functionality provided by XInput will be missing from the DirectInput implementation:

    The left and right trigger buttons will act as a single button, not independently
"

So, some additional potentially complicated work to integrate XInput with irrlicht :(
@auriamg: ideas, comments?

**Comment by auriamg** [comment] 2017-07-30 23:04
@hiker sigh, they can't ever do things the standard way, can't they. I have no obvious answer, maybe the solution is to find (or make) a library that "speaks" both DirectInput and XInput (though I am not aware of one already in existance)

**Comment by hiker** [comment] 2017-07-31 06:41
We can combine the old API (we are using irrlicht's before DirectInput implementation) and XInput (necessary to support 'legacy' i.e. non xbox 360 gamepads), but we need to find out how to find out which index of a old-api-joystick is the same as an index in the XInput api.
I am looking into that.

**Comment by hiker** [comment] 2017-08-01 02:16
I've started to work on implementing this. It will be a somewhat fragile change - so far I haven't found a way to determine if a device is XInput or not (there is a way to determine this if you are using DirectInput, but we are not using DirectInput :(  ). 

For now I will hardcode the device name, e.g. XBox 360 controller only to use the new approach and not as them as legacy device.

But other devices (steering wheels) might work with XInput as well, not sure how to distinguish them (for now they would deliver events twice: once via XInput, once via the legacy path - and they might even show up twice in the device list).

I'll try to come up with some heuristic to ensure a device is only added once (either as an XInput device, or as a legacy device, but not as both).

**Comment by hiker** [comment] 2017-08-01 12:33
There appears to be no connection between the indices of the XInput devices and the indices of the joy* API. I have a rock candy xbox 360, a generic, and last a wireless controller connected. The xbox controller are sorted: candy, wireless in XInput (generic is no xbox, so no XInput), but in the joy* interface they are sorted wireless, generic, candy :(
And various other orders depending in which order I connect them :(

**Comment by hiker** [comment] 2017-08-01 12:48
Compiling irrlicht with DirectInput surprisingly worked out of the box (though we probably need to add some .dll at install time). That might enable us to use an existing method to detect which directx device is actually an XInput device.
Any objections or problems if we use DirectInput?

**Comment by deveee** [comment] 2017-08-01 20:15
First words on wikipedia are "DirectInput is a deprecated Microsoft API" ;p
But if it's easier to use, then I'm fine.

And will it make compilation on windows more complicated? I.e. you have to
use DirectX SDK?

2017-08-01 14:48 GMT+02:00 hiker <notifications@github.com>:

**Comment by hiker** [comment] 2017-08-02 00:17
Well, atm we are using the pre-DirectInput api, which is I think so deprecated it's not even marked as deprecated anymore(?), e.g. https://msdn.microsoft.com/en-us/library/windows/desktop/dd743591(v=vs.85).aspx
Anyway, microsoft advises that older devices will not work with XInput (and probably certain non-microsoft gamepads ... ps4 controller??), so we need to find a way to support older devices anyway.

According to https://msdn.microsoft.com/en-us/library/windows/desktop/dd743591(v=vs.85).aspx:
"The core components, such as Direct3D and DirectInput, are considered part of the operating system"
I am not sure if this means we don't need to include an installer/redistributable for it, we need to test this on a clean windows install :(

**Comment by deveee** [comment] 2017-08-02 10:43
I have clean winxp and almost clean win7 installations on virtualbox, so I can make some tests. But if it's just few functions and API is stable, then you can check in runtime if the library exists and dynamically load these functions. Users with xbox controllers probably have it installed.

**Comment by hiker** [comment] 2017-08-02 12:22
Not sure about dynamically loading - if necessary I would prefer to include an installer otherwise (else we risk similar bug reports again from people who connect their xbox controller for the first time).

Let me finish the test implementation first.

**Comment by hiker** [comment] 2017-08-06 13:03
OK, the branch improve-xbox-gamepad-support should fix this issue, but now STK required DirectInput and XInput.

Leaving this open till we know the installer works, or it is updated to install the appropriate dependencies.

**Comment by deveee** [comment] 2017-08-07 20:25
I had to make one minor modification:
```
diff --git a/lib/irrlicht/source/Irrlicht/CIrrDeviceWin32.cpp b/lib/irrlicht/source/Irrlicht/CIrrDeviceWin32.cpp
index 04d568a363..270cfe94f1 100644
--- a/lib/irrlicht/source/Irrlicht/CIrrDeviceWin32.cpp
+++ b/lib/irrlicht/source/Irrlicht/CIrrDeviceWin32.cpp
@@ -20,7 +20,7 @@
 #include <regstr.h>
 #include <winuser.h>
 #if defined(_IRR_COMPILE_WITH_JOYSTICK_EVENTS_)
-#include <Xinput.h>
+#include <xinput.h>
 #ifdef _IRR_COMPILE_WITH_DIRECTINPUT_JOYSTICK_
 #define DIRECTINPUT_VERSION 0x0800
 #include <dinput.h>
```
and I compiled it with mingw 6.2 without any problems.

I tried to run it on clean WinXP SP2 and on Win7 SP1 and on both systems it complains about missing xinput1_3.dll. So it looks that include directx installer is necessary. I didn't try to install it, because I don't have any xbox controller anyway.

I can check it with Visual Studio if you want, but I suppose that it will be the same.

And btw. target_link_libraries with xinput should be probably placed in irrlicht cmake file.

And regarding to the dynamically loading dll, maybe a popup message in options "xbox controller has been detected. install xyz software, otherwise it may not work as expected"?

**Comment by deveee** [comment] 2017-08-07 22:11
Ok, I checked the VS 2015 too. It needs xinput1_4.dll that is missing in the system. Additionally it depends on dinput8.dll, but this file is available in system32, so it shouldn't be a problem.

**Comment by hiker** [comment] 2017-08-07 23:12
Hmm - that is a bit strange. One by one:
1) You have a dependency on xinput 1.3 - that indeed needs a redistributable (see https://msdn.microsoft.com/en-us/library/windows/desktop/hh405051(v=vs.85).aspx). Mine is build against 1.4, which _should_ be fine (see below).
2) Xinput.h vs xinput.h: I checked, on my system it is Xinput.h. Maybe it is because you were using xinput 1.3?
3) target_link - yes, you are right of course; I'll fix it.
4) When compiled with VS 2015 you have a missing xinput1_4.dll. That might be because it is windows 7? https://blogs.msdn.microsoft.com/chuckw/2012/04/25/xinput-and-windows-8/: "For XInput 1.4 on Windows 8 and Windows RT, no redistribution is required since XInput 1.4 is included with the OS. "  and "Since Xinput version 1.4 is not available on Windows 7, Win32 desktop games that support older versions of Windows can use either XInput 1.3 or the still supported older XInput 9.1.0 which is included in Windows Vista, Windows 7, and Windows 8.". So, we might have to build two binaries ... but it does not explain your first experiment, since it was linked with xinput 1.3 it should have worked (at least on your win7 sp1). :( Three binaries? Xinput 1.4, xinput 1.3, and the old non-directinput non-xinput version?? :( :( :(

**Comment by deveee** [comment] 2017-08-08 08:08
2. 
Here is what I found for windows.h, so maybe it's something similar with xinput.h:
```
The MinGW windows.h header always seems to be lower case. The Windows.h file provided with Microsoft's tools have used a variety of cases.
   - old VC++ installations (VC++98 and earlier) appear to install WINDOWS.H - all caps
   - newer VC++ installations and Windows SDKs seem to use Windows.h
   - some mobile device SDKs (PocketPC or Windows mobile) use windows.h - all lowercase.
```
In worst case I can just add an #ifdef.

4. 
The xinput 9.1.0 indeed is included in clean Win7, but unfortunately the 1.3/1.4 versions not :( I can't check it on newer OS.

But it looks that using xinput 1.4 requires win8 or newer: "XInput 1.4: XInput 1.4 ships as part of Windows 8. Use this version for building Windows Store apps or if your desktop app requires Windows 8."

What if you will try to link with xinput 9.1.0? Do you need functionality fron 1.3/1.4?

**Comment by hiker** [comment] 2017-08-08 11:46
Strange - my last comment didn't make it through - perhaps I forgot to click on 'comment'. Anyway, that's was what I was going to do, 9.1 is all I need.
Could you check bd5eb89cc ?

**Comment by deveee** [comment] 2017-08-08 21:05
I had to change few more details:
```
diff --git a/lib/irrlicht/CMakeLists.txt b/lib/irrlicht/CMakeLists.txt
index 545e857ca8..ae2b46f412 100644
--- a/lib/irrlicht/CMakeLists.txt
+++ b/lib/irrlicht/CMakeLists.txt
@@ -570,5 +570,5 @@ if(ENABLE_WAYLAND_DEVICE)
 endif()
 
 if(WIN32)
-    target_link_libraries(stkirrlicht imm32 XINPUT9_1_0.LIB)
+    target_link_libraries(stkirrlicht imm32 xinput9_1_0)
 endif()
diff --git a/lib/irrlicht/source/Irrlicht/CIrrDeviceWin32.cpp b/lib/irrlicht/source/Irrlicht/CIrrDeviceWin32.cpp
index b38c04b597..a323c3cddf 100644
--- a/lib/irrlicht/source/Irrlicht/CIrrDeviceWin32.cpp
+++ b/lib/irrlicht/source/Irrlicht/CIrrDeviceWin32.cpp
@@ -23,8 +23,9 @@
 // This define will switch to use XInput 9.1, which does not
 // require an installer and works on most windows platforms.
 // See https://blogs.msdn.microsoft.com/chuckw/2012/04/25/xinput-and-windows-8/
+#undef _WIN32_WINNT
 #define _WIN32_WINNT 0x0601
-#include <Xinput.h>
+#include <xinput.h>
 #ifdef _IRR_COMPILE_WITH_DIRECTINPUT_JOYSTICK_
 #define DIRECTINPUT_VERSION 0x0800
 #include <dinput.h>
```
and now it compiles and runs fine on Win7 :)

But there is other issue. I had to disable profiler because there was assertion failure (line 185, frame < m_all_markers.capacity()). It was on virtualbox with force_legacy_device="true", maybe this is the reason...

**Comment by hiker** [comment] 2017-08-09 10:49
OK, after one messed up commit, the proper version just went in (e03c0849ce908b1b3ba8c093118c0266de487b1a). Hope that it compiles now.

I also merged in the fix-profile branch. I had the xbox branch created from the work-in-progress fix-profile branch, not from master :(  I hope that explains the crash you had (?) The current fix-profile branch seems stable/ready to go to master. Let me know if you have still problems.

**Comment by deveee** [comment] 2017-08-09 19:46
Tbh. I would prefer the solution from my previous commit, because:
- we already use lowercase #include <windows.h> everywhere, so we can do the same with xinput
- linked libraries are already lowercase too
- it's simpler

But I'm ok with #ifdef if you want it.

So choose what do you prefer:
[xinput_ver1.diff.txt](https://github.com/supertuxkart/stk-code/files/1212670/xinput_ver1.diff.txt)
[xinput_ver2.diff.txt](https://github.com/supertuxkart/stk-code/files/1212673/xinput_ver2.diff.txt)

Both work with mingw and with VS.

And I don't have the crash on startup anymore :)

**Comment by hiker** [comment] 2017-09-06 00:27
Has all been merged to trunk.

**Closed by hiker** 2017-09-06 00:27 UTC
Labels: C: Other C++ code in STK

**Comment by Radu-Ioachim** [comment] 2020-03-29 17:11
You could (as a VERY lazy solution) run the game through Steam's engine and use their in-built controller configuration software to map the control keys you use on STK on a controller of choice.
Again, VERY lazy solution.

**Comment by Benau** [comment] 2020-03-29 17:41
...we will use sdl2 for gamepad soon ![](https://cdn.lihkg.com/assets/faces/pig/dance.gif)
