### ISSUE TITLE
Segfault on Clicking "Story mode" in main menu

### ISSUE THREAD

**Issue by 4Evergreen4** [supertuxkart/stk-code#1488] opened 2014-08-28 23:53 UTC
This is the error that the game gives me (without gdb):
```
[error  ] SFXBuffer: [SFXBuffer] LoadVorbisBuffer() - couldn't open file!

[error  ] SFXBuffer: Could not load sound effect ../data/../../stk-assets/sfx/button.ogg

[error  ] SFXBuffer: [SFXBuffer] LoadVorbisBuffer() - couldn't open file!

[error  ] SFXBuffer: Could not load sound effect ../data/../../stk-assets/sfx/spaceship_engine.ogg

[error  ] SFXBuffer: [SFXBuffer] LoadVorbisBuffer() - couldn't open file!

[error  ] SFXBuffer: Could not load sound effect ../data/../../stk-assets/sfx/spaceship_engine_short.ogg

[warn   ] material: Track uses deprecated texture 'grass.jpg'
[error  ] skybox: Using deprecated SkyDome
```

And this is the result of running ```bt full``` after the segfault in gdb:
```
#0  0x000000000068c1f5 in PostProcessing::renderMotionBlur(unsigned int, FrameBuffer&, FrameBuffer&) ()
No symbol table info available.
#1  0x000000000068d844 in PostProcessing::render(irr::scene::ICameraSceneNode*, bool) ()
No symbol table info available.
#2  0x0000000000686e17 in IrrDriver::renderGLSL(float) ()
No symbol table info available.
#3  0x00000000006c372d in IrrDriver::update(float) ()
No symbol table info available.
#4  0x0000000000880a73 in MainLoop::run() ()
No symbol table info available.
#5  0x00000000005dd976 in main ()
No symbol table info available.
```

If any more information is needed, I can give it.

**Comment by reesmichael1** [comment] 2015-04-07 03:24
This is happening for me (with essentially the same same output) with 0.9 RC-2 on Arch Linux. I get the segfault on clicking either "Story Mode" or "Singleplayer." If I click on "Multiplayer," I get to the "press fire" screen, but pressing fire also results in the segfault.

I'm happy to provide anything else you need.

**Comment by hiker** [comment] 2015-04-07 03:49
Not sure what exactly 0.9RC-2 from arch linux is :(  Probably our 0.9rc ?
Could you post the stdout.log file (likely in ~/.config/supertuxkart/0.8.2/stdout.log), and also try to run stk in gdb (instructions as above)?

Also can you try to reduce the graphical details to their lowest settings, and provide details about your graphics card and driver version?

**Comment by reesmichael1** [comment] 2015-04-07 05:54
Sorry, my mistake. Yes, it's the 0.9rc.

Graphics card:

```
lspci -k | grep -A 2 -E "(VGA|3D)"
01:00.0 VGA compatible controller: NVIDIA Corporation GK107M [GeForce GT 650M Mac Edition] (rev a1)
	Subsystem: Apple Inc. Device 00fc
	Kernel driver in use: nvidia
```

Driver information:

```
# modinfo nvidia
filename:       /lib/modules/3.19.2-1-ARCH/extramodules/nvidia.ko.gz
alias:          char-major-195-*
version:        346.47
supported:      external
license:        NVIDIA
alias:          pci:v000010DEd00000E00sv*sd*bc04sc80i00*
alias:          pci:v000010DEd00000AA3sv*sd*bc0Bsc40i00*
alias:          pci:v000010DEd*sv*sd*bc03sc02i00*
alias:          pci:v000010DEd*sv*sd*bc03sc00i00*
depends:        drm,i2c-core
vermagic:       3.19.2-1-ARCH SMP preempt mod_unload modversions 
parm:           NVreg_Mobile:int
parm:           NVreg_ResmanDebugLevel:int
parm:           NVreg_RmLogonRC:int
parm:           NVreg_ModifyDeviceFiles:int
parm:           NVreg_DeviceFileUID:int
parm:           NVreg_DeviceFileGID:int
parm:           NVreg_DeviceFileMode:int
parm:           NVreg_RemapLimit:int
parm:           NVreg_UpdateMemoryTypes:int
parm:           NVreg_InitializeSystemMemoryAllocations:int
parm:           NVreg_UsePageAttributeTable:int
parm:           NVreg_MapRegistersEarly:int
parm:           NVreg_RegisterForACPIEvents:int
parm:           NVreg_CheckPCIConfigSpace:int
parm:           NVreg_EnablePCIeGen3:int
parm:           NVreg_EnableMSI:int
parm:           NVreg_MemoryPoolSize:int
parm:           NVreg_RegistryDwords:charp
parm:           NVreg_RmMsg:charp
parm:           NVreg_AssignGpus:charp
```

OpenGL Information:

```
glxinfo | grep "OpenGL"        
OpenGL vendor string: VMware, Inc.
OpenGL renderer string: Gallium 0.4 on llvmpipe (LLVM 3.6, 256 bits)
OpenGL version string: 3.0 Mesa 10.5.2
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
```

[stdout.log](https://gist.github.com/reesmichael1/64fc3465d7c572fc2983)

With the Graphical Effects settings at their lowest:

```
# (gdb) bt full
#0  0x00007ffff529bc6e in _int_malloc () from /usr/lib/libc.so.6
No symbol table info available.
#1  0x00007ffff529c7ba in _int_memalign () from /usr/lib/libc.so.6
No symbol table info available.
#2  0x00007ffff529dcd8 in _mid_memalign () from /usr/lib/libc.so.6
No symbol table info available.
#3  0x00007ffff529f92f in posix_memalign () from /usr/lib/libc.so.6
No symbol table info available.
#4  0x00007fffef88833f in ?? () from /usr/lib/xorg/modules/dri/swrast_dri.so
No symbol table info available.
#5  0x00007fffef8885c0 in ?? () from /usr/lib/xorg/modules/dri/swrast_dri.so
No symbol table info available.
#6  0x00007fffef482028 in ?? () from /usr/lib/xorg/modules/dri/swrast_dri.so
No symbol table info available.
#7  0x00007fffef3f23bd in ?? () from /usr/lib/xorg/modules/dri/swrast_dri.so
No symbol table info available.
#8  0x00007fffef488437 in ?? () from /usr/lib/xorg/modules/dri/swrast_dri.so
No symbol table info available.
#9  0x00007fffef3e0f40 in ?? () from /usr/lib/xorg/modules/dri/swrast_dri.so
No symbol table info available.
#10 0x00000000007c1408 in compressTexture(irr::video::ITexture*, bool, bool) ()
No symbol table info available.
#11 0x00000000007e3f57 in ?? ()
No symbol table info available.
```

Just so you know, in the process of looking into this, I moved all of the files that I could find related to STK to a backup folder, but the crash still happened, so I don't *think* it's an issue with any local files.

Thanks for looking into this!

**Comment by deveee** [comment] 2015-04-07 06:57
Glxinfo shows that you have only software rendering using mesa driver.
Though still it shouldn't crash.

**Comment by reesmichael1** [comment] 2015-04-07 20:01
Thanks for your reply. I replaced mesa-libgl with nvidia-libgl, and was then able to complete a race on "Subsea" without a hitch, so it does seem to be an issue with mesa and texture compression.

**Comment by deveee** [comment] 2015-04-08 07:03
@reesmichael1 sure, best solution was to fix your graphics drivers :) But crash with texture compression and software rendering is separated issue, which I am able to reproduce in my system.

Anyway this was a different issue than originally reported. And I'm closing this ticket because of no feedback since September.

**Closed by deveee** 2015-04-08 07:03 UTC
Labels: R:Waiting for feedback
