### ISSUE TITLE
Laps not registered (online play)

### ISSUE THREAD

**Issue by Qtamo** [supertuxkart/stk-code#3915] opened 2019-05-13 14:13 UTC
## Description
Sometimes rarely the laps are not registered. This happened twice in online STK 1.0 on Linux Mint in global networking online play (normal race) within maybe 20 or so races. It happened once on Volcan Island and once in Black Forest, once to me and once to another player. I think both times there were only two players (it was the server Strasbourg ranked) although on one of the races there were first 3 players (Volcan island) before one of them left (on the first lap). I think both times the bug happened on the first lap (maybe).

## Steps to reproduce
Get unlucky and see above

## Configuration
STK 1.0 downloaded from the site and extracted, with the .config players.xml file edited to unlock everything. Graphics turned to minimum.

If you think other info is relevant GPU/CPU etc let me know.

I saw some other post https://github.com/supertuxkart/stk-code/issues/3257 which was talking about checklines and shortcuts. I took the train shortcut in Black Forest when it happened to me. I went on the tracks after the bridge. I might have had some difficulty getting on the tracks and I might have been saved by the bird. I don't remember exactly anymore.

**Comment by Mrxx99** [comment] 2019-05-13 15:19
You can start SuperTuxKart with --check-debug as command line argument and then you see the placement of the checklines in the track. Maybe you can find the spot where you missed one this way.

**Comment by Alayan-stk-2** [comment] 2019-05-14 00:15
Closing as a duplicate of #3509 and #3830.

I never heard of a lap counting issue in Volcano Island before, I'd be interested to know what way your kart went for the issue to happen. But please answer in #3509.

**Closed by Alayan-stk-2** 2019-05-14 00:15 UTC
